Feature/parameter requirements
GSA/fedramp-automation pull request #1013
Opened 2024-12-16 23:25 UTC by wandmagic

# Committer Notes

introduce
- has-required-parameter constraint

I'd like to also make sure that choice type constraints are one of the values but, i'll save that for another PR this one is heavy enough.

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-12-16 23:27 UTC, wandmagic commented
addresses [#1006](https://github.com/GSA/fedramp-automation/issues/1006)

2024-12-17 02:47 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            </expect>
Blocking: the rest looks solid, but was this inclusion intentional?

2024-12-17 19:52 UTC, DimitriZhurkin submitted a review, later dismissed
Well done.

2024-12-17 20:42 UTC, wandmagic commented
Thanks for the update, I wasn't aware of the aggregate params situation

2024-12-18 07:15 UTC, aj-stein-gsa requested changes
As requested, I reviewed the option's per @Rene2mt's review and I would like us to proceed with filtering on ODP parameters, and not require definiton of the classic (non-ODP parameters). More details in https://github.com/GSA/fedramp-automation/issues/1006#issuecomment-2550531101. Thanks for your patience in me sorting this decision out.

2024-12-18 14:38 UTC, wandmagic commented
> As requested, I reviewed the option's per @Rene2mt's review and I would like us to proceed with filtering on ODP parameters, and not require definiton of the classic (non-ODP parameters). More details in [#1006 (comment)](https://github.com/GSA/fedramp-automation/issues/1006#issuecomment-2550531101). Thanks for your patience in me sorting this decision out.

so to get this correct, we need only params that include the string "odp" ??

2024-12-18 15:02 UTC, aj-stein-gsa commented
> so to get this correct, we need only params that include the string "odp" ??

Correct, @wandmagic.

2024-12-18 16:10 UTC, Rene2mt commented
The following metapath should grab all params excluding ones that aggregate `//param[not(prop[@name="aggregates"])]`

2024-12-18 21:05 UTC, wandmagic commented
we now have a warning advising against the usage of aggregate params (instead of expressly forbidding them) and a constraint to make sure we have non-aggregate params

2024-12-19 05:16 UTC, aj-stein-gsa commented
> we now have a warning advising against the usage of aggregate params (instead of expressly forbidding them) and a constraint to make sure we have non-aggregate params

Sorry for the delayed reply. I know we discussed this earlier in chat, but wanted to make it explicit here: I would recommend a constraint with `level="WARNING"` for aggregate params (i.e. those that are `odp` within their `@id`s).

2024-12-19 13:39 UTC, wandmagic commented
> > we now have a warning advising against the usage of aggregate params (instead of expressly forbidding them) and a constraint to make sure we have non-aggregate params
> 
> 
> 
> Sorry for the delayed reply. I know we discussed this earlier in chat, but wanted to make it explicit here: I would recommend a constraint with `level="WARNING"` for aggregate params (i.e. those that are `odp` within their `@id`s).

Yes that is what is in the pr.

2024-12-20 15:40 UTC, DimitriZhurkin submitted a review, later dismissed

2024-12-20 16:45 UTC, DimitriZhurkin approved these changes

2024-12-20 17:38 UTC, kyhu65867 requested changes

2024-12-20 17:38 UTC, kyhu65867 commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>A FedRAMP SSP MUST NOT set aggregate parameters directly. Parameter {@param-id} is an aggregate parameter that should not be set in the SSP.</message>
Must implies error as opposed to warning. Change must to should, like this: 
```suggestion
                <message>A FedRAMP SSP SHOULD NOT set aggregate parameters directly. Parameter {@param-id} is an aggregate parameter that should not be set in the SSP.</message>
```

2024-12-20 17:46 UTC, kyhu65867 approved these changes

2024-12-20 18:19 UTC, DimitriZhurkin approved these changes

2024-12-20 18:21 UTC, merged

2024-12-20 18:21 UTC, Gabeblis approved these changes

2024-12-20 18:31 UTC, aj-stein-gsa reviewed
Too little too, this and more in another PR.

2024-12-20 18:31 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <description>All parameters defined in the SSP</description>
Can we be a little more descriptive here for the sake of downstream users?


```suggestion
                <description>This constraint indexes all parameters in a FedRAMP SSP.</description>
```

2024-12-20 18:31 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>All parameters defined in the baseline MUST have corresponding set-parameter values in the SSP. Missing parameter: ({@id}).</message>
Minor on active voice and style requirements.

```suggestion
                <message>A FedRAMP SSP must define all parameters for all controls from the imported baseline. The following parameters are defined in the baseline, but not properly set in the SSP: ({@id}).</message>
```

2024-12-20 18:51 UTC, wandmagic commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <description>All parameters defined in the SSP</description>
right on i'll include this in the next PR

2024-12-20 18:51 UTC, wandmagic commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>All parameters defined in the baseline MUST have corresponding set-parameter values in the SSP. Missing parameter: ({@id}).</message>
ditto

2024-12-20 19:11 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>All parameters defined in the baseline MUST have corresponding set-parameter values in the SSP. Missing parameter: ({@id}).</message>
Hold up on that there are a few others I'll just send it to you somewhere, no big deal.