Add connection-security constraint (issue #961)
GSA/fedramp-automation pull request #1021
Opened 2024-12-20 21:47 UTC by DimitriZhurkin

# Committer Notes

This constraint defines the list of allowed values for the `connection-security` property.

Related issue: [#961](https://github.com/GSA/fedramp-automation/issues/961).

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-12-20 23:57 UTC, aj-stein-gsa approved these changes

2024-12-23 21:43 UTC, Gabeblis requested changes

2024-12-23 21:43 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +                <description>Identifies connection security value.</description>
Can we add the help url?

2024-12-26 13:57 UTC, Gabeblis requested changes
This is good stuff! Just a couple small things that caught my attention.

2024-12-26 13:57 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +            <allowed-values id="connection-security" target="system-implementation/component/prop[@name='connection-security' and @ns='https://fedramp.gov/ns/oscal']/@value" allow-other="yes" level="
We should change this to `http` since we finally moved away from the `https` namespace. 
```suggestion
            <allowed-values id="connection-security" target="system-implementation/component/prop[@name='connection-security' and @ns='http://fedramp.gov/ns/oscal']/@value" allow-other="yes" level="WARNING">
```

2025-01-02 16:17 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +            <allowed-values id="connection-security" target="system-implementation/component/prop[@name='connection-security' and @ns='https://fedramp.gov/ns/oscal']/@value" allow-other="yes" level="
Thanks for catching it. Changed `https` to `http`.

2025-01-03 17:33 UTC, aj-stein-gsa approved these changes

2025-01-03 18:20 UTC, wandmagic approved these changes

2025-01-03 18:20 UTC, merged