Feature/poam link
GSA/fedramp-automation pull request #1024
Opened 2024-12-23 18:25 UTC by wandmagic

# Committer Notes

adding some poam item related constraints

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-12-23 19:08 UTC, wandmagic commented
see #934

2024-12-26 14:37 UTC, Gabeblis requested changes
Good stuff. Just a couple things related to the style guide and to help make this PR easier to look at.

2024-12-26 14:37 UTC, Gabeblis commented on src/validations/constraints/content/ssp-component-has-poam-link-INVALID.xml
> +<system-security-plan xmlns="http://csrc.nist.gov/ns/oscal/1.0" uuid="11111111-2222-4000-8000-000000000000">
Are we able to trim down this file to the minimum necessary content?

2024-12-26 14:37 UTC, Gabeblis commented on src/validations/constraints/content/ssp-poam-link-has-resource-fragment-INVALID.xml
> +<system-security-plan xmlns="http://csrc.nist.gov/ns/oscal/1.0" uuid="11111111-2222-4000-8000-000000000000">
Are we able to trim down this file to the minimum necessary content?

2024-12-26 14:37 UTC, Gabeblis commented on src/validations/constraints/content/ssp-poam-link-references-valid-resource-INVALID.xml
> +<system-security-plan xmlns="http://csrc.nist.gov/ns/oscal/1.0" uuid="11111111-2222-4000-8000-000000000000">
Are we able to trim down this file to the minimum necessary content?

2024-12-26 14:37 UTC, Gabeblis commented on src/validations/constraints/content/ssp-poam-resource-has-oscal-link-INVALID.xml
> +<system-security-plan xmlns="http://csrc.nist.gov/ns/oscal/1.0" uuid="11111111-2222-4000-8000-000000000000">
Are we able to trim down this file to the minimum necessary content?

2024-12-26 14:37 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +    <context>
This doesn't comply with [frr102](https://github.com/GSA/fedramp-automation/blob/develop/src/validations/styleguides/STYLE.md/#FRR102). Can we move this into the existing context block with the `/system-security-plan` target.

2024-12-26 14:37 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="ssp-component-has-poam-link" target="$network-components" test="exists($poam-uri) and count(link[@rel='poam-item']) = 1" level="ERROR">
These constraints don't comply with [frr103](https://github.com/GSA/fedramp-automation/blob/develop/src/validations/styleguides/STYLE.md#frr103).

2024-12-27 15:47 UTC, wandmagic commented
@Gabeblis  can you take a look? i added some more checks so we don't have to check alphabetical order, or duplicate constraints

2024-12-27 16:39 UTC, wandmagic commented
converting to draft while i pull out style guide edits

2024-12-30 17:09 UTC, closed without merging

2024-12-30 17:23 UTC, aj-stein-gsa commented
Are you reopening this? I also get part-way through a PR and then have to start over with reviews. 😅