Feature/style constraints
GSA/fedramp-automation pull request #1048
Opened 2024-12-27 17:19 UTC by wandmagic

# Committer Notes

include improvements to sorting and other style guide implementations:

frr102 uniqueness for single metapaths
frr105 uniqueness for constraints
frr119 line length for invalid sample content
frr103 sorting constraints alphabetically

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-12-27 17:24 UTC, aj-stein-gsa approved these changes

2024-12-27 17:26 UTC, aj-stein-gsa submitted a review, later dismissed

2024-12-27 17:26 UTC, aj-stein-gsa commented on src/validations/styleguides/STYLE.md
> +| [FRR118](#frr119) | Keep Invalid Sample Content under 100 lines | Recommended| Structure; Sorting |
Woops, please fix this and I will reapprove.

```suggestion
| [FRR119](#frr119) | Keep Invalid Sample Content under 100 lines | Recommended| Structure; Sorting |
```

2024-12-27 17:26 UTC, aj-stein-gsa commented on src/validations/styleguides/STYLE.md
Also, I know it is tedious, but please add a description as a target to the `frr119` anchor to match the others. It can be very short, we do not need a non-conformant example that is 101 lines long, just leave a comment. 😆

2024-12-27 17:41 UTC, wandmagic commented
Made some changes to the docs for the new style constraint

2024-12-27 20:41 UTC, aj-stein-gsa requested changes

2024-12-27 20:41 UTC, aj-stein-gsa commented on src/validations/styleguides/STYLE.md
> +#### FRR119 Non-conformant Example
Look at the other requirement above and mimic the rest. For the record, I was saying you do _not_ have to keep a full 100+ line example for the non-conformant bit, but we should add good explanation fro the other sub-sections for a requirement that all the others have.

2024-12-30 13:05 UTC, wandmagic commented on src/validations/styleguides/STYLE.md
> +#### FRR119 Non-conformant Example
fixed

2024-12-30 14:15 UTC, Gabeblis approved these changes

2024-12-30 14:23 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +        	</allowed-values>
Minor, non-blocking: could we indent this to match the other constraints?

2024-12-30 14:23 UTC, aj-stein-gsa commented on features/steps/fedramp_extensions_steps.ts
> +      if (lineCount > 200) {
Sorry I didn't notice this last week, but why double counting at 200, not 100?

2024-12-30 14:40 UTC, wandmagic commented
@aj-stein-gsa  thanks for noticing the 200 error, should be fixed now

2024-12-30 14:54 UTC, Gabeblis approved these changes

2024-12-30 14:56 UTC, merged