Add `issue-1032` Constraints
GSA/fedramp-automation pull request #1051
Opened 2024-12-30 15:13 UTC by Gabeblis

# Committer Notes
## Purpose
This PR aims to add the `component-has-authenticated-scan` and `inventory-item-has-authenticated-scan` constraints which help ensure that there is an "allow-authenticated-scan" prop in the inventory, and each Internal "service" component has "allows-authenticated-scan".
## Changes
Added constraints: 
- `component-has-authenticated-scan`
- `inventory-item-has-authenticated-scan`

Added valid/invalid test content:
- `ssp-component-has-authenticated-scan-INVALID.xml`
- `ssp-inventory-item-has-authenticated-scan-INVALID.xml`
- Edited `fedramp-ssp-example.oscal.xml` to align with constraints.

Added yaml files for testing:
- Pass/fail yaml tests added for each of the above constraints. 

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [x] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-12-30 15:25 UTC, wandmagic approved these changes
looks good nice work

2024-12-30 15:36 UTC, wandmagic commented
needs rebase

2024-12-30 18:27 UTC, wandmagic approved these changes

2024-12-31 21:33 UTC, Rene2mt submitted a review, later dismissed

2024-12-31 23:05 UTC, aj-stein-gsa approved these changes

2025-01-10 16:49 UTC, Rene2mt requested changes

2025-01-10 16:49 UTC, Rene2mt commented on src/validations/constraints/fedramp-external-constraints.xml
> +    </context>
BLOCKING: lines 672-681 are duplicates of 661-670

```suggestion
```

2025-01-10 16:49 UTC, Rene2mt commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="inventory-item-has-authenticated-scan" target="." test="count(prop[@name='allows-authenticated-scan']) >= 1 or count(../component[@uuid=$component-uuid]/prop[@name='allows-aut
NON-BLOCKING: The issue had the following target and test specified.  The implementation is different BUT seems to work fine.  Just confirming the changes in implementation were intended.

```
target=". | //component[@uuid=./implemented-component/@component-uuid]"

test="count(./prop[@name='allows-authenticated-scan']) >=1"
```

2025-01-10 18:47 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="inventory-item-has-authenticated-scan" target="." test="count(prop[@name='allows-authenticated-scan']) >= 1 or count(../component[@uuid=$component-uuid]/prop[@name='allows-aut
Yes, this was intended because we aren't able to implement it the way specified in the issue. The current implementation behaves as desired by the issue.

2025-01-10 18:51 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +    </context>
Thanks for catching this. Resolved: [8e5f6c9](https://github.com/GSA/fedramp-automation/pull/1051/commits/8e5f6c9ef11111e8afe03b3cacbe740dc8b18fe0)

2025-01-13 20:03 UTC, Rene2mt submitted a review, later dismissed

2025-01-14 19:39 UTC, wandmagic commented
conflicts need to be resolved

2025-01-15 14:13 UTC, Gabeblis commented
> conflicts need to be resolved

done 🫡

2025-01-16 18:11 UTC, Rene2mt approved these changes
looks good

2025-01-23 17:43 UTC, kyhu65867 submitted a review, later dismissed
LGTM

2025-01-23 19:10 UTC, wandmagic commented
yes it looks good bug conflicts need to be resolved again

2025-01-28 17:48 UTC, Gabeblis commented
@wandmagic @kyhu65867 @Rene2mt This PR was previously approved, but I had to rebase it. Please take another look when you have a moment 🙏

2025-01-31 20:44 UTC, Rene2mt approved these changes
@Gabeblis sorry I didn't see this sooner.  Looks good to me!!

2025-02-10 14:05 UTC, aj-stein-gsa approved these changes

2025-02-10 14:05 UTC, merged