poam-link constraints
GSA/fedramp-automation pull request #1052
Opened 2024-12-30 17:11 UTC by wandmagic

# Committer Notes

adding constraints for poam item linkage

  - ssp-component-has-poam-link 
  - ssp-poam-item-exists 
  - ssp-poam-link-has-resource-fragment 
  - ssp-poam-link-references-valid-resource 
  - ssp-poam-resource-has-oscal-link 
  - has-poam-resource 

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-12-30 17:49 UTC, wandmagic commented
new version of #1024

2024-12-30 18:04 UTC, Gabeblis submitted a review, later dismissed
Looks good, just some minor message changes.

2024-12-30 20:19 UTC, aj-stein-gsa requested changes
Some initial feedback on wording.

More generally, and maybe this warrants a discussion, do we need need to be careful with `//back-matter/resource`s across all model instances, and not focusing on SSP? Later on, this could cause over-generalized matches if we incidentally add such POAM linkage over time in other documents in a package (I know we don't do that now, but we should be precise here IMO). I would love feedback from the rest of the team during review and re-review.

2024-12-30 20:19 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-allowed-values.xml
There is a lot of noise in this file that seems separate of the change, are you using an auto-formatting configuration in your IDE or did you do these changes manually?

2024-12-30 20:19 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Each interconnection, service, or software connecting to external systems MUST have exactly one POAM item link.</message>
[FRR111 feedback](https://github.com/GSA/fedramp-automation/blob/develop/src/validations/styleguides/STYLE.md#frr111):

```suggestion
                <message>In a FedRAMP SSP, each interconnection, service, or software connecting to external systems MUST have exactly one link to an item the corresponding Plan of Actions and Milestones.</message>
```

2024-12-30 20:19 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>The POAM item referenced by resource-fragment ({@resource-fragment}) MUST exist within the POAM document.</message>
[FRR111 feedback](https://github.com/GSA/fedramp-automation/blob/develop/src/validations/styleguides/STYLE.md#frr111):

```suggestion
                <message>In a FedRAMP SSP, the item referenced by resource-fragment ({@resource-fragment}) MUST exist within the Plan of Actions and Milestones document.</message>
```

I am not sure we can avoid [FRR113 requirements](https://github.com/GSA/fedramp-automation/blob/develop/src/validations/styleguides/STYLE.md#frr113), and I cannot think of constructive recommendations here, so I may let it go.

2024-12-30 20:19 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Each POAM link MUST include a non-empty resource fragment identifier.</message>
[FRR111 feedback](https://github.com/GSA/fedramp-automation/blob/develop/src/validations/styleguides/STYLE.md#frr111):

```suggestion
                <message>In a FedRAMP SSP, each link to an item in the Plan of Actions Milestones MUST include a resource fragment identifier for that specific item in the document. It MUST NOT be empty.</message>
```

More generally, I am not sure how we get around [FRR113](https://github.com/GSA/fedramp-automation/blob/develop/src/validations/styleguides/STYLE.md#frr113) here, so we may have to let that go.

2024-12-30 20:19 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <let var="poam-resource" expression="//resource[prop[@name='type' and @value='plan' and @class='poam']]"/>
Are we sure we want a `poam-item` in _any_ OSCAL document instance in a package, not just a SSP?

2024-12-30 20:19 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <let var="poam-uri" expression="$poam-resource/rlink[@media-type='application/oscal+xml']/@href"/>
Are we sure we want a `poam-item` in _any_ OSCAL document instance in a package, not just a SSP?

2024-12-30 20:19 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <let var="poam-is-available" expression="doc-available(resolve-uri($poam-uri))"/>
Are we sure we want a `poam-item` in _any_ OSCAL document instance in a package, not just a SSP?

2024-12-30 20:19 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <let var="poam-doc" expression="if ($poam-is-available) then doc(resolve-uri($poam-uri)) else ()"/>
Are we sure we want a `poam-item` in _any_ OSCAL document instance in a package, not just a SSP?

2024-12-30 20:19 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <let var="poam-items-map" expression="map:merge($poam-doc//poam-item ! map:entry(@uuid, .))?*"/>
Are we sure we want a `poam-item` in _any_ OSCAL document instance in a package, not just a SSP?

2024-12-30 20:19 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Each POAM link MUST reference the system's POAM resource using its UUID ({substring-after(@href, '#')}) should be ({ $poam-resource/@uuid}).</message>
[FRR111 feedback](https://github.com/GSA/fedramp-automation/blob/develop/src/validations/styleguides/STYLE.md#frr111):

```suggestion
                <message>In a FedRAMP SSP, each link MUST reference the Plan of Actions and Milestones for the system by its unique identifier. Instead of ({substring-after(@href, '#')}), the value MUST be ({ $poam-resource/@uuid}).</message>
```

2024-12-30 21:01 UTC, wandmagic commented
That's a good point I'll adjust the targeting

2024-12-30 21:01 UTC, wandmagic commented on features/steps/fedramp_extensions_steps.ts
We accidentally removed in the last pr adjusting style

2024-12-30 21:02 UTC, wandmagic commented on src/validations/constraints/fedramp-external-allowed-values.xml
> There is a lot of noise in this file that seems separate of the change, are you using an auto-formatting configuration in your IDE or did you do these changes manually?

Auto formatting

2024-12-30 22:02 UTC, wandmagic commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <let var="poam-doc" expression="if ($poam-is-available) then doc(resolve-uri($poam-uri)) else ()"/>
Do any other assemblies include poam items

2024-12-30 23:38 UTC, wandmagic commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <let var="poam-is-available" expression="doc-available(resolve-uri($poam-uri))"/>
i can have it specify that it must be a poam that also imports this SSP if we want to get specific, i didn't consider a package might have multiple poams, but as far as I know its the only type of document that has the poam-item  assemblies

2024-12-31 13:38 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <let var="poam-is-available" expression="doc-available(resolve-uri($poam-uri))"/>
What happens if we add `poam-item` in the future? We are essentially going to get this requirement applied to other documents in the future when we meant it only for SSP, correct?

2024-12-31 14:00 UTC, aj-stein-gsa requested changes

2024-12-31 14:00 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <let var="poam-uri" expression="$poam-resource/rlink[@media-type='application/oscal+xml']/@href"/>
We might want to also be a little more permissive here because we have [not officially registered this file type in IANA media types registry](https://www.iana.org/assignments/media-types/media-types.xhtml), we may want to be more permissive here, but I like where your head is at. We would need to also accept `application/json`, `application/xml`, and `application/yaml` more generally.

Also, we need to presume there are multiple different data formats, not just one (e.g. JSON, XML, YAML). Maybe something more like this?

```suggestion
            <let var="poam-uri" expression="$poam-resource/rlink[matches(@media-type, '(application\/)(oscal\+)?(xml|json|yaml)']/@href"/>
```

I have test this locally later in the morning, but will follow up.

Source example with test strings: https://regex101.com/r/eAGwVq/1

2024-12-31 14:23 UTC, wandmagic commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <let var="poam-is-available" expression="doc-available(resolve-uri($poam-uri))"/>
the context is system-security-plan, shouldn't it only be based off the context?
maybe i'm incorrect about how metapath works

i've changed it to system-security-plan/back-matter/resource for clarity, but i'll have to figure out the effects of using the // findall directive because i understood it only looks inside the context target.

2024-12-31 14:24 UTC, wandmagic commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <let var="poam-is-available" expression="doc-available(resolve-uri($poam-uri))"/>
> What happens if we add `poam-item` in the future? We are essentially going to get this requirement applied to other documents in the future when we meant it only for SSP, correct?

i can add a negative case to test for this but i think not

2024-12-31 14:31 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <let var="poam-is-available" expression="doc-available(resolve-uri($poam-uri))"/>
Ugh nevermind! I was doing dumb stuff multi-tasking yesterday, the context is perfectly fine. Thanks for humoring me. 🤦

2025-01-02 17:46 UTC, wandmagic commented
@brian-ruf  please take a look at this solution, we add a fedramp-poam type to the accepted values enumuration under fedramp namespaces this allows us to differentiate between the fedramp poam resource, and other poam resources which may exist.

@aj-stein-gsa please take a look at the media-type information inside the valid poam resource, oscal-mode=poam let me know if this is the correct usage of the mime-type parameters you suggested. I filter this by media-type contains('oscal') to determine if the rlink is oscal or not.

2025-01-03 16:18 UTC, wandmagic commented
Converting to draft until requirements are full defined

2025-03-12 14:18 UTC, wandmagic commented
closing this for now

2025-03-12 14:18 UTC, closed without merging