Feature/cucumber tests
GSA/fedramp-automation pull request #609
Opened 2024-07-17 18:38 UTC by wandmagic

Introduce yaml test runner

2024-07-19 15:19 UTC, david-waltermire commented on features/steps/fedramp_extensions_steps.ts
> +  const result =await Object.entries(testCase.expectations)
Maybe rename `result` result to expectations or similar.

2024-07-19 20:40 UTC, david-waltermire commented on .github/workflows/content-artifacts.yml
> +        - uses: actions/checkout@v2
This should be pinned to a specific commit hash.

2024-07-19 20:41 UTC, david-waltermire commented on .github/workflows/content-artifacts.yml
> +          uses: stefanzweifel/git-auto-commit-action@v4.4.1
This should be pinned to a specific commit hash.

2024-07-19 20:41 UTC, david-waltermire commented on .github/workflows/run-tests.yml
>          uses: actions/setup-node@v1
This should be pinned to a specific commit hash.

2024-07-19 20:44 UTC, david-waltermire commented on .github/workflows/run-tests.yml
>  jobs:
This is setup to run on `master`. Should we run this on all development, feature, and PR branches as well?

2024-07-19 20:47 UTC, david-waltermire commented on .github/workflows/run-tests.yml
> +          make build
Does this include the validations? Is this in the right order with the previous steps?

2024-07-19 20:48 UTC, david-waltermire commented on @rerun.txt
> +features/steps/fedramp_extensions.feature:4:13:30:31:32:33:34
What is the purpose of this file?

2024-07-19 20:51 UTC, david-waltermire commented on src/content/rev5/baselines/xml/FedRAMP_rev5_HIGH-baseline_profile.xml
> -			<link href="https://fedramp.gov" rel="homepage"/>
Are these profile changes intended to be in this PR?

2024-07-19 20:53 UTC, david-waltermire requested changes
There are a few small refinements that I provided inline comments requesting.

There also appears to be some profile changes here, which looks like some of the work @Rene2mt is doing in a different branch. Could this be due to some merging/rebasing?

2024-07-22 14:52 UTC, wandmagic commented
> There are a few small refinements that I provided inline comments requesting.
> 
> There also appears to be some profile changes here, which looks like some of the work @Rene2mt is doing in a different branch. Could this be due to some merging/rebasing?

yes i merged in the changes renee made to the profiles in this branch

2024-07-22 14:53 UTC, wandmagic commented on @rerun.txt
> +features/steps/fedramp_extensions.feature:4:13:30:31:32:33:34
this has been removed, its an artifact that lets cucumber know which tests should be re-run that have failed

2024-07-22 15:00 UTC, wandmagic commented on .github/workflows/run-tests.yml
> +          make build
i trimmed this, looks like it was running it twice

2024-07-22 15:04 UTC, wandmagic commented on .github/workflows/run-tests.yml
>          uses: actions/setup-node@v1
done

2024-07-22 15:06 UTC, wandmagic commented on .github/workflows/run-tests.yml
>  jobs:
added develop and feature branches

2024-07-23 00:12 UTC, david-waltermire commented on src/content/rev5/baselines/xml/FedRAMP_rev5_HIGH-baseline_profile.xml
> -			<link href="https://fedramp.gov" rel="homepage"/>
Please rebase this branch to remove the merge commits. I can help you if you'd like some assistance.

2024-07-23 00:12 UTC, david-waltermire commented
> > There are a few small refinements that I provided inline comments requesting.
> > There also appears to be some profile changes here, which looks like some of the work @Rene2mt is doing in a different branch. Could this be due to some merging/rebasing?
> 
> yes i merged in the changes renee made to the profiles in this branch

Please rebase this branch to remove the merge commits. I can help you if you'd like some assistance.

2024-07-23 17:32 UTC, wandmagic commented
see #613 for an isolated only the yaml testing script pull request

2024-07-23 17:32 UTC, closed without merging