External constraints
GSA/fedramp-automation pull request #610
Opened 2024-07-19 20:46 UTC by Rene2mt

# Committer Notes

This DRAFT PR adds some FedRAMP external allowed-values constraints, and corresponding YAML unit tests.  

**NOTE: the SSP content file (referenced in unit tests) is not final yet and still pending many changes to ensure it aligns with the unit test expectations.**

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-07-22 14:58 UTC, david-waltermire commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +        <metapath target="."/>
This `target` identifies where in the model the constraints are added. The `target` in each constraint is evaluated relative to this location.

2024-07-22 14:59 UTC, david-waltermire commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +            <allowed-values id="address-type" target="party/address/@type" allow-other="no" level="ERROR">
This appears to apply to in the `/*/metadata` context.

2024-07-22 14:59 UTC, david-waltermire commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +            <allowed-values id="authorization-type" target="system-characteristics/prop[@name='authorization-type'][@ns='https://fedramp.gov/ns/oscal']" allow-other="no" level="ERROR">
This applies in the `/system-security-plan` context.

2024-07-22 19:55 UTC, DimitriZhurkin commented
In **fedramp-external-allowed-values.xml**, are `<allowed-values>` `@level` attributes legit?

2024-07-24 15:24 UTC, Rene2mt commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +        <metapath target="."/>
This is fixed now.

2024-07-24 15:24 UTC, Rene2mt commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +            <allowed-values id="address-type" target="party/address/@type" allow-other="no" level="ERROR">
This is fixed now.

2024-07-24 15:24 UTC, Rene2mt commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +            <allowed-values id="authorization-type" target="system-characteristics/prop[@name='authorization-type'][@ns='https://fedramp.gov/ns/oscal']" allow-other="no" level="ERROR">
This is fixed now.

2024-07-24 15:28 UTC, Rene2mt commented on src/validations/constraints/content/ssp-all-VALID.xml
This sample SSP is based on the FedRAMP-SSP-OSCAL-template.xml.  Updates to pass validations are ongoing but may replace this with the awesome OSCAL SSP instead and make updates there.

2024-08-26 15:28 UTC, aj-stein-gsa reviewed
Initial feedback below, really like what I see so far.

2024-08-26 16:33 UTC, david-waltermire commented
@Rene2mt You may want to do a rebase on the base branch to resolve the conflicts.

2024-08-27 01:30 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +                </allowed-values>
I am unsure myself. Maybe I'll make a note and we can close out this comment for now.

2024-08-28 23:08 UTC, Rene2mt commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +                <allowed-values id="deployment-model" target="system-characteristics/prop[@name='cloud-deployment-model'][@ns='https://fedramp.gov/ns/oscal']/@value" allow-other="no" level="ERROR">
I removed the 'cloud-deployment-model' constraint in the latest commits because core OSCAL already has [allowed values for cloud-deployment-model](https://github.com/usnistgov/OSCAL/blob/v1.1.2/src/metaschema/oscal_ssp_metaschema.xml#L148-L167) defined.  However, I just noticed that FedRAMP does not allow one of the core OSCAL allowed values ("**_community-cloud_**").  

![image](https://github.com/user-attachments/assets/93af079f-a6f8-4e3a-ba30-5bb6e1567c1d)

See https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#deployment-model

Seem like in this case, FedRAMP needs to override the core constraint.  Should we re-add the 'cloud-deployment-model' _allowed values_ constraint, restricting values to **_public-cloud_**, **_private-cloud_**, **_government-only-cloud_**, **_hybrid-cloud_**, and **_other_**?

2024-08-29 19:18 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +                </allowed-values>
I guess the real question is whether or not we will support "legacy" authorizations. I guess it is time for an email with a policy update/guidance from the brass.

I am going to surpress this comment _for now_ because we are merging into a feature branch and shouldn't hold up this PR and it is not a merge for prime time, so I will follow up.

2024-08-29 19:40 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +                <allowed-values id="deployment-model" target="system-characteristics/prop[@name='cloud-deployment-model'][@ns='https://fedramp.gov/ns/oscal']/@value" allow-other="no" level="ERROR">
I am cool with you reverting my recommendation. Next time you get to call me out more clearly for not verifying understanding on the automate.fedramp.gov docs.

So re discussion in standup today: go back to what you had, `@ns` scope it, and I will re-review post haste. Thanks for your attention to detail on this. Once my computer is set up correctly I can do more than quickly eyeball and guess without local testing, apologies!

2024-09-10 11:15 UTC, david-waltermire commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +        <metapath target="/plan-of-action-and-milestones"/>
These are all duplicated.
```suggestion
        <metapath target="/catalog"/>
        <metapath target="/profile"/>
        <metapath target="/component-definition"/>
        <metapath target="/system-security-plan"/>
        <metapath target="/assessment-plan"/>
        <metapath target="/assessment-results"/>
        <metapath target="/plan-of-action-and-milestones"/>
```

2024-09-10 11:16 UTC, david-waltermire commented on src/validations/constraints/fedramp-external-allowed-values.xml
>              <allowed-values id="attachment-type" target="back-matter/resource/prop[@name='type'][@ns='https://fedramp.gov/ns/oscal']/@value" allow-other="no" level="ERROR">
This constraint only applies to the SSP, SAP, SAR, and POAM models, but the context is all models.

2024-09-10 11:24 UTC, david-waltermire commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +                <enum value="fedramp">FedRAMP Authorization</enum>
We may want to consider keeping the old authorization types for compatibility and deprecating.
```suggestion
                <enum value="fedramp">FedRAMP Authorization</enum>
                <enum value="fedramp-jab" deprecated="fedramp-3.0.0">FedRAMP Joint Authorization Board Authorization</enum>
                <enum value="fedramp-agency" deprecated="fedramp-3.0.0">FedRAMP Agency Authorization</enum>
                <enum value="fedramp-li-saas" deprecated="fedramp-3.0.0">FedRAMP Tailored for LI-SaaS Authorization</enum>
```

2024-09-10 11:28 UTC, david-waltermire commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +        <metapath target="/plan-of-action-and-milestones"/>
Also, I don't think these constraints apply to catalogs, profiles, and component definitions. Lines 8-10 should be removed.

2024-09-10 11:31 UTC, david-waltermire requested changes
This PR has some issues. See other comments.

2024-09-10 14:42 UTC, aj-stein-gsa reviewed
These constraints look good, but we may need some docs.

2024-09-10 14:42 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +        <metapath target="/system-security-plan/system-characteristics/security-impact-level/(security-objective-confidentiality|security-objective-integrity|security-objective-availability)"/>
Blocking: these constraints look good generally, but the documentation is slightly out of alignment on these and a few others.

2024-09-10 14:42 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +            <allowed-values id="security-level" target="." allow-other="no" level="ERROR">
We don't seem to cover `security-level` at all in the FedRAMP docs at this point from using search.gov.

2024-09-10 14:42 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +        <metapath target="/system-security-plan/system-characteristics/system-information/information-type/(confidentiality-impact|integrity-impact|availability-impact)/(base|selected)"/>
Blocking: these constraints look good generally, but the documentation is slightly out of alignment on these and a few others.

2024-09-10 21:57 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +        <metapath target="/system-security-plan/system-characteristics/system-information/information-type/(confidentiality-impact|integrity-impact|availability-impact)/(base|selected)"/>
Will follow up in https://github.com/GSA/automate.fedramp.gov/issues/55.

2024-09-10 21:57 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +            <allowed-values id="security-level" target="." allow-other="no" level="ERROR">
Will follow up in https://github.com/GSA/automate.fedramp.gov/issues/55.

2024-09-10 21:57 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +        <metapath target="/system-security-plan/system-characteristics/security-impact-level/(security-objective-confidentiality|security-objective-integrity|security-objective-availability)"/>
Will follow up in https://github.com/GSA/automate.fedramp.gov/issues/55.

2024-09-11 02:20 UTC, aj-stein-gsa requested changes
One more thing to do is I noticed the OSCAL submodule has been moved around from the target branch. I want to be careful and intentional when we choose to move this up. Once it is aligned with f/e-c branch, I am ready to merge and approve and work the documentation out-of-band.

2024-09-18 20:16 UTC, Rene2mt commented
> One more thing to do is I noticed the OSCAL submodule has been moved around from the target branch. I want to be careful and intentional when we choose to move this up. Once it is aligned with f/e-c branch, I am ready to merge and approve and work the documentation out-of-band.

The submodule change crept in accidentally on one of the previous commits.  I dropped that commit and re-applied the changes.  Let me know if there's anything else outstanding.

2024-09-20 03:26 UTC, aj-stein-gsa requested changes
Just a heads up there is also an empty mystery empty file with a Unicode character name. I can help with removing the mystery file. Other than that, this may need some touch ups, but looks very good so far.

2024-09-25 23:52 UTC, closed without merging

2024-09-25 23:52 UTC, Rene2mt commented
Superseded by PR#732.  Closing 610 without merging.