automate content generation and validation via CLI
GSA/fedramp-automation pull request #614
Opened 2024-07-23 18:04 UTC by wandmagic

# Committer Notes

{Please provide a description of what this PR accomplishes. Be sure to reference any issues addressed. If the PR is a work-in-progress submitted for early review, please submit the PR as a draft PR using the "Draft pull request" dropdown.}

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-07-29 18:39 UTC, david-waltermire requested changes
Once the few comments are addressed, this will be ready.

2024-07-29 18:39 UTC, david-waltermire commented on .github/workflows/content-artifacts.yml
> +  # yamllint disable-line rule:truthy
Please remove the two preceeding spaces on each line.

2024-07-29 18:39 UTC, david-waltermire commented on .github/workflows/run-tests.yml
> +      - 'feature**'  # This will match any branch starting with "feature"
Maybe this to better follow gitflow naming?
```suggestion
      - 'feature/**'  # This will match any branch starting with "feature"
```

2024-07-29 18:39 UTC, david-waltermire commented on .github/workflows/run-tests.yml
> +        uses: test-summary/action@v2
Can you check that all actions are pinned to a hash?

2024-07-30 12:48 UTC, wandmagic commented on .github/workflows/run-tests.yml
> +        uses: test-summary/action@v2
pinned

2024-07-30 12:49 UTC, wandmagic commented on .github/workflows/content-artifacts.yml
> +  # yamllint disable-line rule:truthy
eslinted

2024-07-30 19:47 UTC, david-waltermire approved these changes

2024-07-30 19:48 UTC, merged