Feature/external constraints
GSA/fedramp-automation pull request #622
Opened 2024-08-02 20:38 UTC by wandmagic

# Committer Notes

Adjust allowed value constraints and unit tests, include valid and invalid SSPS
### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-08-03 13:21 UTC, david-waltermire commented on src/validations/constraints/fedramp-external-allowed-values-DZ.xml
> +
This already [exists](https://github.com/usnistgov/OSCAL/blob/4f02dac6f698efda387cc5f55bc99581eaf494b6/src/metaschema/oscal_implementation-common_metaschema.xml#L137) in OSCAL and should be removed.
```suggestion
```

2024-08-03 13:24 UTC, david-waltermire commented on src/validations/constraints/fedramp-external-allowed-values-DZ.xml
> +            </allowed-values>
This already [exists](https://github.com/usnistgov/OSCAL/blob/4f02dac6f698efda387cc5f55bc99581eaf494b6/src/metaschema/oscal_implementation-common_metaschema.xml#L132) in OSCAL and should be removed.
```suggestion
```

2024-08-03 13:26 UTC, david-waltermire commented on src/validations/constraints/fedramp-external-allowed-values-DZ.xml
> +            </allowed-values>
This [exists](https://github.com/usnistgov/OSCAL/blob/4f02dac6f698efda387cc5f55bc99581eaf494b6/src/metaschema/oscal_implementation-common_metaschema.xml#L127) in OSCAL and should be removed.
```suggestion
```

2024-08-03 13:34 UTC, david-waltermire commented on src/validations/constraints/fedramp-external-allowed-values-DZ.xml
> +            </allowed-values>
This [exists](https://github.com/usnistgov/OSCAL/blob/4f02dac6f698efda387cc5f55bc99581eaf494b6/src/metaschema/oscal_ssp_metaschema.xml#L727) in OSCAL and should be removed.
```suggestion
```

2024-08-03 13:44 UTC, david-waltermire commented on src/validations/constraints/fedramp-external-allowed-values-DZ.xml
> +            <allowed-values id="control-implementation-status" target="control-implementation/implemented-requirement/prop[@name='implementation-status']/@value" allow-other="no" level="ERROR">
This is located in the wrong place in the SSP model. It should be under [`by-component`](https://github.com/usnistgov/OSCAL/blob/4f02dac6f698efda387cc5f55bc99581eaf494b6/src/metaschema/oscal_ssp_metaschema.xml#L852). The [current](https://github.com/usnistgov/OSCAL/blob/4f02dac6f698efda387cc5f55bc99581eaf494b6/src/metaschema/oscal_implementation-common_metaschema.xml#L341) OSCAL constraint is `allow-other="yes"`, so this constraint is needed to close the values (i.e., `allow-other="no"`), so we should keep it, but target it differently.

```suggestion
            <allowed-values id="control-implementation-status" target="control-implementation/implemented-requirement/by-component/prop[@name='implementation-status']/@value" allow-other="no" level="ERROR">
```

2024-08-03 13:57 UTC, david-waltermire commented on src/validations/constraints/fedramp-external-allowed-values-DZ.xml
> +            </allowed-values>
The [current](https://github.com/usnistgov/OSCAL/blob/4f02dac6f698efda387cc5f55bc99581eaf494b6/src/metaschema/oscal_implementation-common_metaschema.xml#L236) OSCAL constraint is allow-other="yes", so this constraint is needed to close the values (i.e., allow-other="no"), so we should keep it.

Our values are out of sync with the OSCAL values, so we need to confirm that the documentation is correct.
```suggestion

            <allowed-values id="component-type" target="system-implementation/component/@type" allow-other="no" level="ERROR">
                <formal-name>Component Type</formal-name>
                <description>Identifies the component type.</description>
                <enum value="interconnection">A connection to something outside this system.</enum>
                <enum value="software">Any software, operating system, or firmware.</enum>
                <enum value="hardware">A physical device.</enum>
                <enum value="service">A service that may provide APIs.</enum>
                <enum value="policy">An enforceable policy.</enum>
                <enum value="physical">A tangible asset used to provide physical protections or countermeasures.</enum>
                <enum value="process-procedure">A list of steps or actions to take to achieve some end result.</enum>
                <enum value="plan">An applicable plan.</enum>
                <enum value="guidance">Any guideline or recommendation.</enum>
                <enum value="standard">Any organizational or industry standard.</enum>
                <enum value="validation">An external assessment performed on some other component, that has been validated by a third-party.</enum>
                <enum value="this-system">The system as a whole.</enum>
                <enum value="system">An external system, which may be a leveraged system or the other side of an interconnection.</enum>
                <enum value="network">A physical or virtual network.</enum>
            </allowed-values>
```

2024-08-03 13:59 UTC, david-waltermire commented on src/validations/constraints/fedramp-external-allowed-values-DZ.xml
> +            <allowed-values id="attachment-type" target="back-matter/resource/prop[@name='type']/@value" allow-other="yes" level="ERROR">
This constraint is not contextualized correctly. This applies to a back-matter resource. Please move this to a different context.

2024-08-03 14:00 UTC, david-waltermire commented on src/validations/constraints/content/ssp-all-VALID.xml
> +      <prop name="type" value="policy" ns="https://fedramp.gov/ns/oscal"/>
This is not an invalid case to test the resource constraint.

2024-08-03 14:05 UTC, david-waltermire requested changes
I provided some feedback on individual constraints.

Some are targeted improperly and their context or target need to be updated as indicated in my comments.  It also looks like the negative tests are not sufficient, since these were passing. We need to add negative test cases for these to confirm proper operation.

Others duplicate existing OSCAL constraints, which we don't need unless we are trying to close the value list for something that is `allow-other="yes"`. If the value set is already closed, we need to mark these as "drop" in the tracker and remove them as indicated.

2024-08-03 14:08 UTC, david-waltermire commented
This looks like good progress. Overall, we need to check that every constraint has both a negative and positive test case. There we some in this set that are improperly targeted, which may mean the testing is not robust enough to find the problem.

2024-08-13 15:30 UTC, wandmagic commented on src/validations/constraints/content/ssp-all-VALID.xml
> +      <prop name="type" value="policy" ns="https://fedramp.gov/ns/oscal"/>
this is fixed

2024-08-13 15:32 UTC, wandmagic commented on src/validations/constraints/fedramp-external-allowed-values-DZ.xml
> +            <allowed-values id="attachment-type" target="back-matter/resource/prop[@name='type']/@value" allow-other="yes" level="ERROR">
what context does it belong to?
ssp.sch shows attachment type only applies to backmatter resources

2024-08-14 09:51 UTC, wandmagic reviewed
added more robust reporting and a new failure test option "mixed" for if a single failing test counts as a negative test case

2024-08-14 12:48 UTC, wandmagic reviewed
looks good to me now

2024-08-14 12:50 UTC, wandmagic reviewed
looks good

2024-08-14 18:16 UTC, wandmagic commented
this is ready to be looked at again @david-waltermire

2024-08-16 21:30 UTC, Rene2mt requested changes

2024-08-16 21:30 UTC, Rene2mt commented on src/validations/constraints/content/profile-all-INVALID.xml
> +          <p>This is a test statement with a non-string response point.</p>
We currently don't have any constraints around `response-point` value, however, a given (control) part shouldn't have more than one `response-point`.  
```suggestion
          <p>This is a test checking that profiles validation fails if more than one response point is specified for a given (control) part.</p>
```

2024-08-16 21:30 UTC, Rene2mt commented on src/validations/constraints/content/test-valid-response-point-use.xml
For consistency, recommend we use the following naming convention for validation constraint file names:
* *{model}-{assembly, field, or flag name}-{VALID or INVALID}.xml*.  Following this convention, this unit test content file would be renamed **profile-response-point-INVALID.xml**

Following the same pattern, instances where the content covers **all** data in an OSCAL document, the naming convention would be *{model}-all-{VALID or INVALID}.  For example **profile-all-INVALID.xml**.

2024-08-16 21:30 UTC, Rene2mt commented on src/validations/constraints/unit-tests/response-point-FAIL.yaml
> +  content: ../content/test-valid-response-point-use.xml # the content to run
see other comment on naming convention for validation constraint content file names.  If the file is changes, please also update the reference here

```suggestion
content: ../content/profile-response-point-INVALID.xml # the content to run
```

2024-08-17 03:54 UTC, wandmagic commented on src/validations/constraints/content/fedramp-tailoring-profile.xml
> +    <prop ns="https://fedramp.gov/ns/oscal" name="fedramp-version" value="2.0.0"/>
removed

2024-08-20 15:19 UTC, david-waltermire requested changes
It still looks like the mime types have not been addressed yet.

2024-08-20 16:08 UTC, wandmagic commented on src/validations/module.mk
> +	npx oscal@latest use oscal-cli-2.0.2.rc1
we no longer specify version here, we just use latest which should get automatically latest from maven

2024-08-20 16:10 UTC, wandmagic commented on src/content/rev5/baselines/xml/FedRAMP_rev5_LI-SaaS-baseline_profile.xml
> +            <rlink media-type="application/xml" href="https://raw.githubusercontent.com/usnistgov/oscal-content/v1.2.0/nist.gov/SP800-53/rev5/xml/NIST_SP-800-53_rev5_catalog.xml"/>
it has been changed to oscal+xml in the latest version

2024-08-20 16:13 UTC, david-waltermire commented on .github/workflows/run-tests.yml
> +        os: [ubuntu-20.04, windows-latest]
Can we pin to a windows version?

2024-08-20 16:59 UTC, wandmagic commented on .github/workflows/run-tests.yml
> +        os: [ubuntu-20.04, windows-latest]
pinned

2024-08-20 19:09 UTC, david-waltermire commented
As follow-on work, #628 will be used to address OSCAL CLI versioning.

2024-08-20 19:09 UTC, wandmagic commented on src/validations/module.mk
> +	npx oscal@latest use oscal-cli-2.0.2.rc1
See issue  #628 for tracking a better resolution to this issue in a future PR

2024-08-20 19:11 UTC, david-waltermire requested changes

2024-08-20 19:11 UTC, david-waltermire commented on src/validations/module.mk
> +	$(OSCAL_CLI) use latest
See #628

2024-08-20 19:11 UTC, david-waltermire commented on src/validations/module.mk
> +OSCAL_CLI = npx oscal@latest
See #628

2024-08-20 19:11 UTC, david-waltermire commented on src/content/module.mk
> +	$(OSCAL_CLI) use latest
See #628

2024-08-20 19:21 UTC, wandmagic commented on .github/workflows/run-tests.yml
> +        if: runner.os == 'Windows'
it would take more time is all, it appears that ubuntu comes with java version suitable for oscal-cli

2024-08-20 19:24 UTC, wandmagic commented on .github/workflows/run-tests.yml
> +        if: runner.os == 'Windows'
added java to ubuntu and only took an extra 5 seconds

2024-08-20 21:25 UTC, david-waltermire approved these changes

2024-08-20 21:29 UTC, merged