introduce user sensitivity level constraint + refactor
GSA/fedramp-automation pull request #634
Opened 2024-08-22 21:21 UTC by wandmagic

# Committer Notes

{Please provide a description of what this PR accomplishes. Be sure to reference any issues addressed. If the PR is a work-in-progress submitted for early review, please submit the PR as a draft PR using the "Draft pull request" dropdown.}

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-08-26 19:34 UTC, Rene2mt requested changes

2024-08-26 19:34 UTC, Rene2mt commented on src/validations/constraints/content/ssp-all-INVALID.xml
> +      <prop name='sensitivity' value='unsupported-risk'/>
Under core NIST OSCAL, the ```user``` assembly does not have a **sensitivity** prop, so this needs to have the FedRAMP namespace added:

```suggestion
      <prop ns="https://fedramp.gov/ns/oscal" name="sensitivity" value="unsupported-risk" />
```
See the [OSCAL Metaschema](https://github.com/usnistgov/OSCAL/blob/4f02dac6f698efda387cc5f55bc99581eaf494b6/src/metaschema/oscal_implementation-common_metaschema.xml#L394-L412)

2024-08-26 19:34 UTC, Rene2mt commented on src/validations/constraints/content/ssp-all-INVALID.xml
> +      <prop name='sensitivity' value='unsupported-risk'/>
Under core NIST OSCAL, the ```user``` assembly does not have a **sensitivity** prop, so this needs to have the FedRAMP namespace added:

```suggestion
      <prop ns="https://fedramp.gov/ns/oscal" name="sensitivity" value="unsupported-risk" />
```
See the [OSCAL Metaschema](https://github.com/usnistgov/OSCAL/blob/4f02dac6f698efda387cc5f55bc99581eaf494b6/src/metaschema/oscal_implementation-common_metaschema.xml#L394-L412)

2024-08-26 19:34 UTC, Rene2mt commented on src/validations/constraints/content/ssp-all-VALID.xml
> +      <prop name='sensitivity' value='high-risk'/>
Under core NIST OSCAL, the ```user``` assembly does not have a **sensitivity** prop, so this needs to have the FedRAMP namespace added:

```suggestion
      <prop ns="https://fedramp.gov/ns/oscal" name="sensitivity" value="unsupported-risk" />
```
See the [OSCAL Metaschema](https://github.com/usnistgov/OSCAL/blob/4f02dac6f698efda387cc5f55bc99581eaf494b6/src/metaschema/oscal_implementation-common_metaschema.xml#L394-L412)

2024-08-26 19:34 UTC, Rene2mt commented on features/fedramp_extensions.feature
> +  | fedramp-external-user-allowed-values.xml |
I wonder if it might be just easier to keep these constraints in the **fedramp-external-allowed-values.xml** constraints file?  ```user``` doesn't have that many *allowed-value* constraints.

Let's come up with guidance / rule of thumb for when we should use add constraints to the existing **fedramp-external-allowed-values.xml** and **fedramp-external-constraints.xml** versus when we should create separate constraint files.

2024-08-28 15:53 UTC, wandmagic commented on features/fedramp_extensions.feature
> +  | fedramp-external-user-allowed-values.xml |
I've migrated this file to the main allowed values file as per our discussion today

2024-08-28 19:17 UTC, Rene2mt approved these changes

2024-08-28 22:05 UTC, aj-stein-gsa requested changes

2024-08-28 22:05 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +              </allowed-values>
Blocking: it seems we are diverging from the NIST OSCAL upstream and have some custom values here, where is `privileged` coming from, for example?

2024-08-28 22:05 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-allowed-values.xml
> -              </allowed-values>
Blocking: if remove this then the above has to be addressed and aligned with NIST upstream. I am just pointing this out so my feedback makes sense to others on the team and they know these two changes in this PR are related.

2024-08-29 18:00 UTC, wandmagic commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +              </allowed-values>
privileged was added in error

2024-08-29 18:00 UTC, wandmagic commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +              </allowed-values>
this has been removed

2024-08-29 19:28 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-allowed-values.xml
> -              </allowed-values>
Did we check existing docs (especially on automate.fedramp.gov) about what FedRAMP expects, just beside the upstream docs?

2024-08-29 19:36 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-allowed-values.xml
> -              </allowed-values>
Hmmm, unclear. You're good, need to add a quick issue on that repo to cover that. We talk about roles in SAP and SAR, but not user type as discussed in the context of this PR.

2024-08-29 19:39 UTC, aj-stein-gsa approved these changes

2024-09-20 01:48 UTC, aj-stein-gsa requested changes

2024-09-20 01:48 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +              </allowed-values>
Blocking: while working on docs, we diverge from upstream core OSCAL constraints. I am not sure this is a critical issue, I would like to discuss with the team and internal staff if we need to diverge or align with upstream or not.

2024-09-20 01:48 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +              </allowed-values>
Blocking: while working on docs, I realized this is a FedRAMP-specific constraint, this does not exist in core upstream OSCAL.

```suggestion
              <allowed-values id="user-sensitivity-level" target="prop[@ns='https://fedramp.gov/ns/oscal' and @name='sensitivity']/@value"  allow-other="no" level="ERROR">
                <formal-name>User Sensitvity Level</formal-name>
                <description>Sensitivity level of the user.</description>
                <enum value="high-risk">High Risk</enum>
                <enum value="severe">Severe</enum>
                <enum value="moderate">Moderate</enum>
                <enum value="limited">Limited</enum>
                <enum value="not-applicable">Not Applicable</enum>
              </allowed-values>
```

2024-09-26 01:30 UTC, aj-stein-gsa requested changes
Hi @wandmagic, I rebased this to take a look where are at.

Can you split out the INVALID tests to individual fixture data files for negative tests per ADR 8 and then request re-review? Thanks.

2024-10-01 10:58 UTC, wandmagic commented
closing this, just going to make a new branch

2024-10-01 10:58 UTC, closed without merging