Add README.md to OSCAL CLI instructions
GSA/fedramp-automation pull request #636
Opened 2024-08-28 19:55 UTC by DimitriZhurkin

# Committer Notes

Initial draft of the README.md document for using OSCAL CLI. This document is intended for FedRAMP OSCAL end-users (implementers and practitioners).

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-08-28 21:10 UTC, aj-stein-gsa requested changes
There are some typos and missing info (that I missed in previous review, apologies).

2024-08-28 21:10 UTC, aj-stein-gsa commented on src/validations/constraints/README.md
> +
Sorry I did not notice this until reading later in the day, we could specifically say how to unzip if you want.

```suggestion
8. Extract the downloaded ZIP archive into the created **oscal-cli** directory.
   `unzip oscal-cli-enhanced.zip -d /opt/oscal-cli`
```

2024-08-28 21:10 UTC, aj-stein-gsa commented on src/validations/constraints/README.md
> +   `<shell-root>/opt/oscl-cli`
Minor typo:

```suggestion
   `<shell-root>/opt/oscal-cli`
```

2024-08-28 21:32 UTC, kyhu65867 commented on src/validations/constraints/README.md
> +3. To verify that you are on the correct branch
Specify here that the correct branch is the external constraints branch

2024-08-28 21:32 UTC, kyhu65867 commented on src/validations/constraints/README.md
> +	* `<sarif-output>` is the auto-generated validation results file in the SARIF format (for more information about SARIF, visit [https://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.html](https
(I'm writing this for other cybersecurity folx that are new that may be using this without having a coding background)-- specify that this is the file name for the output of this program, where the validation results will be written upon running the command. I could imagine someone wondering what they need to do to generate a SARIF format because they didn't know what the difference between -c and -o are

2024-08-28 21:32 UTC, kyhu65867 commented on src/validations/constraints/README.md
> +
Maybe add to the above sentence "by comparing OSCAL-formatted SSPs, SAPs, etc. with FedRAMP-provided external restraints. This tool produces a sarif-formatted validation file that identifies where your OSCAL content meets and does not meet FedRAMP OSCAL requirements." (It could make it a little less concise, but I like having specific information about inputs and outputs in the readme)

2024-08-28 21:32 UTC, kyhu65867 commented on src/validations/constraints/README.md
> +2. JDK version 11 or newer
Add link here to download JDK if needed?

2024-08-28 21:32 UTC, kyhu65867 commented on src/validations/constraints/README.md
> +Cloning the FedRAMP Automation GitHub repository gives you access to the latest FedRAMP-specific OSCAL extensions, making your validations more robust.
Could anyone run this without using the FedRAMP specific OSCAL extensions? Like can you validate your OSCAL against another constraints file? If there are more ways of using this tool right now, it might be worth adding sections like "here's how you compare against fedramp stuff, here's how you do x y or z, etc." but if this is the only way to do it right now, it might be worth taking out the line "making your validations more robust" because it implies that you can get validations without FedRAMP external constraints.

2024-08-28 21:32 UTC, kyhu65867 commented on src/validations/constraints/README.md
> +4. In the **decoratedName** field, note the XPath expression (for example, "/system-security-plan/metadata\[1\]").
What are you doing with the XPath expression? Is that what you use to find the location? If so, add that to step 6 (that you find the location referenced in the XPath expression for the decoratedName field

2024-08-28 21:43 UTC, DimitriZhurkin commented on src/validations/constraints/README.md
> +2. Under the latest release, click **Download**.
I believe, on the download page, there's only ZIP download. And, following AJ's suggestion, I have added the command to extract a ZIP archive.

2024-08-28 21:45 UTC, DimitriZhurkin commented on src/validations/constraints/README.md
> +3. To verify that you are on the correct branch
It's just a placeholder, since we don't know yet which branch we'll be using. It probably will be the master branch. I'll update that instruction, when we know for sure.

2024-08-28 21:48 UTC, DimitriZhurkin commented on src/validations/constraints/README.md
> +2. JDK version 11 or newer
I thought about providing a link for JDK, but there are many, many flavors of JDK. I'm not sure which source to recommend.

2024-08-28 21:49 UTC, DimitriZhurkin commented on src/validations/constraints/README.md
> +Cloning the FedRAMP Automation GitHub repository gives you access to the latest FedRAMP-specific OSCAL extensions, making your validations more robust.
Specifics for custom constraints will be in the CONTRIBUTE.md document, which is intended for developer audience. This README is for end-users.

2024-08-28 21:52 UTC, DimitriZhurkin commented on src/validations/constraints/README.md
> +4. In the **decoratedName** field, note the XPath expression (for example, "/system-security-plan/metadata\[1\]").
Good point. Fixed.

2024-08-28 22:46 UTC, aj-stein-gsa approved these changes

2024-08-29 00:11 UTC, david-waltermire approved these changes

2024-08-29 00:18 UTC, merged