Feature/data center constraints
GSA/fedramp-automation pull request #639
Opened 2024-08-28 23:42 UTC by wandmagic

# Committer Notes

Introducing fully covered data center constraints

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-08-29 00:34 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +        </allowed-values>
Blocking: I appreciate the thoroughness of adding all the ISO-3611 entries, I do. I would think that for FedRAMP we only check for value binding to one of them, we should push this upstream with NIST's models and not make maintenance our problem.

@david-waltermire, thoughts?

2024-08-29 13:08 UTC, aj-stein-gsa requested changes

2024-08-29 13:08 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-all-INVALID.xml
> +      <prop name='data-center' value='aws-us-east-1' class='tertiary' ns="https://fedramp.gov/ns/oscal"/>
Also, appreciate the relevance, but maybe for these tests not something specific to one CSP, even if example?

```suggestion
      <prop name='data-center' value='dc-zone-1' class='tertiary' ns="https://fedramp.gov/ns/oscal"/>
```

2024-08-29 13:08 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-all-VALID.xml
> +      <prop name='data-center' value='aws-us-east-1' class='primary' ns="https://fedramp.gov/ns/oscal"/>
Re previous feedback:

```suggestion
      <prop name='data-center' value='dc-zone-1' class='primary' ns="https://fedramp.gov/ns/oscal"/>
```

2024-08-29 13:08 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-location-INVALID.xml
> +      <prop name='data-center' value='aws-us-east-1' class='tertiary' ns="https://fedramp.gov/ns/oscal"/>
Re previous feedback:

```suggestion
      <prop name='data-center' value='dc-zone-1' class='tertiary' ns="https://fedramp.gov/ns/oscal"/>
```

2024-08-29 21:06 UTC, wandmagic commented on src/validations/constraints/fedramp-external-constraints.xml
> +        </allowed-values>
I've removed it for now so we can merge this in and address it later

2024-09-10 16:57 UTC, aj-stein-gsa requested changes

2024-09-10 16:57 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-all-INVALID.xml
> +        <country>USA</country>
Woops, should be alpha two code, still need to fix this.

2024-09-10 16:58 UTC, aj-stein-gsa approved these changes

2024-09-10 17:14 UTC, aj-stein-gsa submitted a review, later dismissed
Feedback to my feedback, paying attention is valuable.

2024-09-10 17:14 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-all-INVALID.xml
> +        <country>US</country>
Teachable moment and fun irony of ironies: the reason the tests broke is because I thought I was being "smart" and aligning the correct version, but that is an invalid test. We want a wrong 2-alpha code, so let's pick one that is more obviously wrong and in spirit get back to where Paul was in the first place. 😆 

```suggestion
        <country>WRONG</country>
```

2024-09-10 21:42 UTC, aj-stein-gsa approved these changes

2024-09-10 21:49 UTC, merged