Create ADR 007-signal-unsupportent-content-in-github.md
GSA/fedramp-automation pull request #645
Opened 2024-08-30 17:29 UTC by Rene2mt

# Committer Notes

This PR adds an ADR, describing proposed approach for signaling legacy  unsupported content in the FedRAMP Automation repository.

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- ~Have you added an explanation of what your changes do and why you'd like us to include them?~
- ~If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?~
- ~If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?~

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-08-30 20:40 UTC, aj-stein-gsa reviewed
Some questions and initial thoughts on leaning into deletion. I would love feedback from you, Rene, and rest of team, and of course the community soon enough.

2024-08-30 20:40 UTC, aj-stein-gsa commented on documents/adr/007-signal-unsupportent-content-in-github.md
> + - deleting **OBSOLETE** content after some period of time or at specified release
Thanks to the power of `git` and services like GitHub, GitLab, Codeberg, we get this for free.

```suggestion
 - deleting **OBSOLETE** content from future releases and leaving archival copies in an archive branch for posterity
```

2024-08-30 20:40 UTC, aj-stein-gsa commented on documents/adr/007-signal-unsupportent-content-in-github.md
> +    * Update with latest OSCAL Implementers slides
Why not move to the automate.fedramp.gov site? These artifacts balloon git history and are really for documentation and communication, they are not code artifacts. Thoughts from the others?

2024-08-30 20:40 UTC, aj-stein-gsa commented on documents/adr/007-signal-unsupportent-content-in-github.md
> +  * Move all current contents to archived subfolder (e.g., **src/examples/archived** )
With git we can delete and still keep history, no?

```suggestion
  * Delete all current contents
```

2024-08-30 20:40 UTC, aj-stein-gsa commented on documents/adr/007-signal-unsupportent-content-in-github.md
> +  * Move all current contents to archive subfolder (e.g., **src/examples/archived** )
With git we can delete and still keep history, no?

```suggestion
  * Delete all current contents
```

2024-08-30 20:40 UTC, aj-stein-gsa commented on documents/adr/007-signal-unsupportent-content-in-github.md
> +  * Move all current contents to archive subfolder (e.g., **src/validations/archived** )
With git we can delete and still keep history, no?

```suggestion
  * Delete all current contents
```

2024-09-03 17:37 UTC, Rene2mt reviewed
Will updated the PR with the requested changes shortly

2024-09-03 17:37 UTC, Rene2mt commented on documents/adr/007-signal-unsupportent-content-in-github.md
> +    * Update with latest OSCAL Implementers slides
Good point.  I'll update the ADR accordingly

2024-09-04 00:33 UTC, aj-stein-gsa requested changes
Apologies for the delayed feedback on this ADR. The exploration of solution space and and the inventory are good. I have some more editorial changes and think we ought to more closely relate it to the [current release strategy and semantic versioning](https://github.com/GSA/automate.fedramp.gov/blob/f085168bc485cf764a37c148d3a3109507d4695a/content/about/release.md), since this allows us to lean into the strengths of `git` and delete it in the future and let everyone use the older releases as archival references for free (including with durable links through git tags).

2024-09-04 00:33 UTC, aj-stein-gsa commented on documents/adr/007-signal-unsupportent-content-in-github.md
> +The FedRAMP OSCAL automation team needs to cleanup the repository periodically, and establish a way to signal to the community areas of the repository that are no longer maintened (e.g., legacy proof
Non-blocking: some more typos and cleanup.

```suggestion
The FedRAMP Automation Team must maintain organization of its repositories, including deprecation and migration information for data, tools, and documentation as part of its release strategy.
```

2024-09-04 00:33 UTC, aj-stein-gsa commented on documents/adr/007-signal-unsupportent-content-in-github.md
> + - deleting **OBSOLETE** content from future releases and leaving archival copies in an archive branch for posterity
```suggestion
1. Leverage [the current release strategy and semantic versioning](https://github.com/GSA/automate.fedramp.gov/blob/f085168bc485cf764a37c148d3a3109507d4695a/content/about/release.md):
  - identify deprecation of relevant data, tools, and documentation in README with an **OBSOLETE** label in the relevant READMEs;
    - make a minor release with deprecation information in those READMEs;
    - make a major release with deprecated content deleted and new data, tools, and documentation released
```

2024-09-04 00:33 UTC, aj-stein-gsa commented on documents/adr/007-signal-unsupportent-content-in-github.md
> +Signal unsupported code / content in the repository by:
```suggestion
Several possible solutions for identifying deprecated and migrated data, tools, and documentation are below.

```

2024-09-04 00:33 UTC, aj-stein-gsa commented on documents/adr/007-signal-unsupportent-content-in-github.md
> +3. marking the content as **ARCHIVED** and moving to an “archived” folder
```suggestion
1. Mark deprecated content by labelling relevant READMEs as **ARCHIVED** and move all relevant content to “archive” folder
```

2024-09-04 00:33 UTC, aj-stein-gsa commented on documents/adr/007-signal-unsupportent-content-in-github.md
> +1. marking the content as **DEPRECATED** in a README
```suggestion
1. Do nothing, leave all data, tools, and documentation as-is
1. Marking the content as **DEPRECATED** in the relevant READMEs
```

2024-09-04 00:33 UTC, aj-stein-gsa commented on documents/adr/007-signal-unsupportent-content-in-github.md
> +The above will be applied to the current repository as follows:
```suggestion
For the purposes of this ADR, there is an inventory for this repository of different tools, data, documentation, and their future deprecation below.

```

2024-09-10 23:47 UTC, aj-stein-gsa requested changes

2024-09-10 23:47 UTC, aj-stein-gsa commented on documents/adr/007-signal-unsupportent-content-in-github.md
> +  * Update README clarifying intent of FedRAMP “template” and documenting known validation issues with each template.  Where possilbe, FedRAMP will attempt to fix template validation issues to reduce
Non-blocking question: what is the intent?

2024-09-10 23:47 UTC, aj-stein-gsa commented on documents/adr/007-signal-unsupportent-content-in-github.md
> +    * Move to automte.fedramp.gov and update with latest Data Bites slides
Minor, non-blocking: the domain is misspelled.

```suggestion
    * Move to [https://automate.fedramp.gov](https://automate.fedramp.gov) and update with latest Data Bites slides  
```

2024-09-12 12:12 UTC, Rene2mt commented on documents/adr/007-signal-unsupportent-content-in-github.md
> +  * Update README clarifying intent of FedRAMP “template” and documenting known validation issues with each template.  Where possilbe, FedRAMP will attempt to fix template validation issues to reduce
Community often has questions about errors when trying to validate the templates.   I've been able to find and fix a lot of the SSP template validation failures using our new tooling, but there's a handful of errors that remain (some seem like false positives).  I'm thinking we should document those remaining errors somewhere, so the community knows these are known issues.

2024-09-16 14:50 UTC, aj-stein-gsa commented on documents/adr/007-signal-unsupportent-content-in-github.md
> +  * Update README clarifying intent of FedRAMP “template” and documenting known validation issues with each template.  Where possilbe, FedRAMP will attempt to fix template validation issues to reduce
Per conversation with you and Dave on Friday, we can put a deprecation warning and defer deletion as necessary, it doesn't necessarily have to be immediately. I will close this out for now.

2024-09-17 04:51 UTC, aj-stein-gsa requested changes
Minor review feedback, getting ready for merge.

2024-09-17 04:51 UTC, aj-stein-gsa commented on documents/adr/007-signal-unsupportent-content-in-github.md
> +Date: 2024-08-30
Important to change the date accordingly.

```suggestion
Date: 2024-09-17
```

2024-09-17 04:51 UTC, aj-stein-gsa commented on documents/adr/007-signal-unsupportent-content-in-github.md
> +Pending Community Feedback
Ditto, mark it accepted as no feedback has been received by community over two meetings.

```suggestion
Accepted
```

2024-09-17 04:51 UTC, aj-stein-gsa commented on documents/adr/007-signal-unsupportent-content-in-github.md
> +
It is time to make a decision, so we shall picture Solution 3.

```suggestion
 ## Decision
 
 The FedRAMP Automation Team will implement Solution 3: identify tools, data, and content for migration, deprecation, remove content accordingly by saving them in an archival minor release and deleting them in a major version release.
   
```

2024-09-17 04:52 UTC, aj-stein-gsa approved these changes

2024-09-17 04:52 UTC, merged