Add back-matter constraints resource-has-{title,rlink}
GSA/fedramp-automation pull request #650
Opened 2024-09-03 14:26 UTC by Gabeblis

# Committer Notes

### Description
Added back-matter constraints and tests for each of the constraints. These should be added as they are part of the effort write all of the constraints from the constraint tracker. 
### Changes
- Added constraints resource-has-title and resource-has-rlink to fedramp-external-constraints.xml.
- Added pass and fail yaml tests for both of the above constraints.
- Edited ssp-all-INVALID to ensure both constraints fail correctly.

{Please provide a description of what this PR accomplishes. Be sure to reference any issues addressed. If the PR is a work-in-progress submitted for early review, please submit the PR as a draft PR using the "Draft pull request" dropdown.}

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-09-03 23:31 UTC, aj-stein-gsa requested changes
Can you base this against #649? I tested this locally before rebase and got errors with the tests other than we discussed when pairing today. I will stitch than in here, but errors went away rebasing and want to make sure before we pull all this in.

Thanks in advance for doing that.

2024-09-04 01:20 UTC, Gabeblis commented
> Can you base this against #649? I tested this locally before rebase and got errors with the tests other than we discussed when pairing today. I will stitch than in here, but errors went away rebasing and want to make sure before we pull all this in.
> 
> Thanks in advance for doing that.

Thanks for the review! I rebased and have no errors. All tests are passing.

2024-09-04 01:34 UTC, aj-stein-gsa commented
> > Can you base this against #649? I tested this locally before rebase and got errors with the tests other than we discussed when pairing today. I will stitch than in here, but errors went away rebasing and want to make sure before we pull all this in.
> > Thanks in advance for doing that.
> 
> Thanks for the review! I rebased and have no errors. All tests are passing.

Was the constraints and failing test the ones you showed me earlier today with the UUID look up to cross-ref a logo for party's logo in metadata back to a resource? Or is that work going into a separate PR to be filed later and just had issues WIPing locally on your computer?

2024-09-04 01:39 UTC, aj-stein-gsa submitted a review, later dismissed
Aside from my questions about the test discussed when pairing, this looks good to go from my perspective. 🚢

2024-09-04 01:39 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-all-INVALID.xml
> +      <!-- <title>Access Control Policy</title> -->
Non-blocking: why comment this out? Since we have a new people on the team, you _may_ want to explain why.

```suggestion
      <!-- There is no <title/> to purposefully to trigger an error for negative testing. -->
```

2024-09-04 01:39 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-all-INVALID.xml
> +      <!-- <rlink href="https://example.com/policies/access-control.pdf"/> -->
Ditto, why comment it out this one out without explanation?

```suggestion
      <!-- There is no <rlink/> to purposefully to trigger an error for negative testing. -->
```

2024-09-04 01:41 UTC, Gabeblis commented
> > > Can you base this against #649? I tested this locally before rebase and got errors with the tests other than we discussed when pairing today. I will stitch than in here, but errors went away rebasing and want to make sure before we pull all this in.
> > > Thanks in advance for doing that.
> > 
> > 
> > Thanks for the review! I rebased and have no errors. All tests are passing.
> 
> Was the constraints and failing test the ones you showed me earlier today with the UUID look up to cross-ref a logo for party's logo in metadata back to a resource? Or is that work going into a separate PR to be filed later and just had issues WIPing locally on your computer?

I was working on the constraint we were discussing earlier in a local branch, and I haven't pushed anything to GitHub yet. That was the resource-is-referenced constraint, and it isn't part of this PR. I'll open a separate PR for it when I have the issue resolved.

2024-09-04 01:43 UTC, aj-stein-gsa commented
> I was working on the constraint we were discussing earlier in a local branch, and I haven't pushed anything to GitHub yet. That was the resource-is-referenced constraint, and it isn't part of this PR. I'll open a separate PR for it when I have the issue resolved.

No worries, we can carry on convo outside of this PR review. I have approved, you get to pull the trigger to merge in. 🫡

2024-09-04 01:45 UTC, Gabeblis commented on src/validations/constraints/content/ssp-all-INVALID.xml
> +      <!-- <title>Access Control Policy</title> -->
This line is commented out to trigger a fail result for the fail case. The constraint checks that each resource has a title, so this proves it catches the error. That is a valid point to add the comment as to why it is commented out. Thank you.

2024-09-04 01:46 UTC, Gabeblis commented on src/validations/constraints/content/ssp-all-INVALID.xml
> +      <!-- <rlink href="https://example.com/policies/access-control.pdf"/> -->
Same case as above. Thanks!

2024-09-04 04:07 UTC, aj-stein-gsa approved these changes

2024-09-04 04:15 UTC, aj-stein-gsa requested changes
Before final merge tomorrow, we should determine what we expect to see in the corresponding documentation. I did notice automate.fedramp.gov talks about the title for resources but doesn't say it is mandatory. Also I now see there is a little more nuance to the constraint requirements than I knew from memory per below and information about base64, rlink, neither or both being permissible in different contexts. Apologies.

https://automate.fedramp.gov/documentation/general-concepts/oscal-citations-and-attachments/

2024-09-05 13:47 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +        </expect>
So re my comment I just wanted to clarify: I know it is a `WARNING`, but our docs say that it can be a base64 or rlink.

> Tools may either embed an attachment using the base64 field, or point to an attachment using an rlink field. If no base64 embedded content is present, at least one rlink field must exist with either an absolute path to content that is accessible by FedRAMP and Agency reviewers from government systems, or a relative path.

Source: https://automate.fedramp.gov/documentation/general-concepts/oscal-citations-and-attachments/

The FedRAMP-specific guidance (in https://automate.fedramp.gov/documentation/general-concepts/4-expressing-common-fedramp-template-elements-in-oscal/#attachments-and-embedded-content) is similar that it represents both.

So what happens is we have only `<base64/>` and no `<rlink/`> is it still a warning?

So we have to adjust the docs, or adjust the constraint. I would think the constraint ought to match the docs in this case, not the other way around, so it should check for `<base64/>` or `<rlink/>`, not one or the other separately.

I may want to double check with @david-waltermire later on his impressions, because I know 3-4 years ago there was some desire to exclude base64 content altogether after my first posting in the program and before his detail. I am not sure that stricter position matters anymore, and the docs do not reflect it.

2024-09-05 15:59 UTC, aj-stein-gsa requested changes

2024-09-05 15:59 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <message>Every supporting artifact found in a citation must have a rlink element.</message>
Also, per pairing discussion:

```suggestion
            <message>Every supporting artifact found in a citation must have at least one base64 or rlink element.</message>
```

2024-09-05 16:00 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +        </expect>
Per discussion I will pick up some docs tweaks from @Gabeblis to align them with this constraint.

2024-09-05 16:05 UTC, aj-stein-gsa submitted a review, later dismissed
I will approve, but let's make sure https://github.com/GSA/automate.fedramp.gov/issues/49 PR is merged along with this for docs alignment, but this is looking good.

2024-09-05 16:05 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +        <expect id="resource-has-rlink" target="back-matter/resource" test="count(./rlink) >= 1 or count(./base64) >= 1" level="WARNING">
Also minor nit, non-blocking: we should update the name to state the obvious and not mislead.

```suggestion
        <expect id="resource-has-base64-or-rlink" target="back-matter/resource" test="count(./rlink) >= 1 or count(./base64) >= 1" level="WARNING">
```

2024-09-05 16:07 UTC, aj-stein-gsa commented on features/fedramp_extensions.feature
> +  | resource-has-rlink |
And I forgot this too! 🤦 

```suggestion
  | resource-has-base64-or-rlink |
```

2024-09-05 16:08 UTC, aj-stein-gsa commented on src/validations/constraints/unit-tests/resource-has-rlink-FAIL.yaml
> +    - constraint-id: resource-has-rlink
And here, sigh 🤦 

```suggestion
    - constraint-id: resource-has-base64-or-rlink
```

2024-09-05 16:08 UTC, aj-stein-gsa commented on src/validations/constraints/unit-tests/resource-has-rlink-FAIL.yaml
> +  name: Negative Test for resource-has-rlink
```suggestion
  name: Negative Test for resource-has-base64-or-rlink
```

2024-09-05 16:10 UTC, aj-stein-gsa commented on src/validations/constraints/unit-tests/resource-has-rlink-FAIL.yaml
> +      result: fail
```suggestion
test-case:
  name: Negative Test for resource-has-rlink
  description: This test case validates the behavior of constraint resource-has-rlink
  content: ../content/ssp-all-INVALID.xml
  expectations:
    - constraint-id: resource-has-base64-or-rlink
      result: fail
```

2024-09-05 16:28 UTC, aj-stein-gsa approved these changes
Thanks for humoring the feedback and the file renames after the constraint changes.

2024-09-10 12:57 UTC, Rene2mt approved these changes

2024-09-10 17:58 UTC, aj-stein-gsa approved these changes

2024-09-10 17:58 UTC, merged