WIP Add responsible-party-is-person constraint
GSA/fedramp-automation pull request #652
Opened 2024-09-05 17:36 UTC by Rene2mt

# Committer Notes

This WIP PR adds responsible-party-is-person constraint, which checks that ```responsible-party``` assemblies with ```role-id``` set to certain values (e.g., "system-owner", "authorizing-official", "authorizing-official-poc", "system-poc-management", "system-poc-technical", "system-poc-other", and "information-system-security-officer") must reference a ```party``` of type "person".

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-09-11 22:43 UTC, Rene2mt commented
Added issue https://github.com/GSA/automate.fedramp.gov/issues/57 for required documentation updates.

2024-09-16 14:33 UTC, aj-stein-gsa requested changes
Will possibly approve after rebase and merge once documentation for the referenced doc PR is complete.

In the meantime, rebase, please and thank you. 🙏

2024-09-18 18:36 UTC, Rene2mt commented
Hey @aj-stein-gsa once I rebased, some of the validations were no longer passing due to modifications I had made to the ssp-all-INVALID.xml test content, so the latest commit rolled those changes back and created a separate test SSP for this new responsible-party-is-person constraint.

2024-09-26 01:14 UTC, aj-stein-gsa requested changes

2024-09-26 01:14 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-all-INVALID.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Blocking: I rebsaed but could not adjust this file and you need to spread it into multiple invalid files, can you delete this and replace with split out per ADR 8 style? Thanks.

2024-09-26 01:35 UTC, Rene2mt commented on src/validations/constraints/content/ssp-all-INVALID.xml
> +<?xml version="1.0" encoding="UTF-8"?>
adjusted so it follows ADR 8 guidance now, with the negative unit test having its own fail content file.

2024-09-26 04:22 UTC, aj-stein-gsa approved these changes

2024-09-26 04:22 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-responsible-party-is-person-INVALID.xml
> +        </responsible-party>
Minor, non-blocking: all good changes but should we show example content even in a negative test for roles we recently confirm should not be included in FR requirements?

```suggestion
```

2024-10-04 13:35 UTC, Rene2mt commented on src/validations/constraints/content/ssp-responsible-party-is-person-INVALID.xml
> +        </responsible-party>
Here's how interpreted the role requirements:

The following roles must be defined, and must have `responsible-party` with a `party` of type "person":
- system-owner
- authorizing-official-poc
- information-system-security-officer

The following roles are not required (are option). But if they are specified,  they should have `responsible-party` with a `party` of type "person":
- system-poc-management
- system-poc-technical
- system-poc-other

Note the 3 system-poc-* roles are considered optional (for now) because that information seems to have been removed from the latest legacy SSP template, however, this is very useful information.

2024-10-04 14:27 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-responsible-party-is-person-INVALID.xml
> +        </responsible-party>
Up to you, so you are saying you want to keep them?

2024-10-04 14:27 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-responsible-party-is-person-INVALID.xml
> +        </responsible-party>
If so we add the prop and end it?

2024-10-09 12:41 UTC, Rene2mt commented on src/validations/constraints/content/ssp-responsible-party-is-person-INVALID.xml
> +        </responsible-party>
yep, lets keep the roles for now.  will update this PR the constraint help prop today

2024-10-24 19:08 UTC, kyhu65867 requested changes
Minor changes and questions

2024-10-24 19:08 UTC, kyhu65867 commented on src/validations/constraints/fedramp-external-constraints.xml
> +            	<formal-name>In-Scope UUIDs for party assemblies of type "person".</formal-name>
Lines 173 and 174 feel jargony to me, but that could just come with the territory. What I would say in description is, "this index  is a list of the UUIDs of all of the parties that are type "person" in the document". The formal name might need to have the "party assemblies" terminology, but description should be more clear and not use the words "party assemblies" because that confuses me.

2024-10-24 19:08 UTC, kyhu65867 commented on src/validations/constraints/content/ssp-responsible-party-is-person-INVALID.xml
> +        </responsible-party>
Are we going to add any constraints related to the optional roles, and making sure if they are included they are of type person? I don't even know if that type of logic is possible, but I was just wondering.

2024-10-25 14:50 UTC, DimitriZhurkin submitted a review, later dismissed
Other reviewers' comments aside, looks good to me.

2024-10-25 17:59 UTC, Rene2mt commented on src/validations/constraints/content/ssp-responsible-party-is-person-INVALID.xml
> +        </responsible-party>
Thats a good point @kyhu65867.  I removed the optinal roles for now, since all FedRAMP is actually looking for in an SSP (based on the word SSP template) is the required roles.  So those are "must haves".  

We haven't fully explored if FedRAMP would make use of any optional roles provided and how we'd handle them, so I view those as "could haves", but it won't block and SSP package review; its just extra data.  We can queue up a separate issue in the future if needed.

2024-10-25 18:27 UTC, Rene2mt commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <index name="index-person-party-uuid" target="map:merge(party[@type='person'] ! map:entry(@uuid,.))?*">
Fixed in commit 5e2b2504719cf162ea1cce901e47c48a71d02c79

2024-10-25 18:28 UTC, Rene2mt commented on src/validations/constraints/fedramp-external-constraints.xml
> +            	<formal-name>In-Scope UUIDs for party assemblies of type "person".</formal-name>
Fixed in commit 5e2b2504719cf162ea1cce901e47c48a71d02c79

2024-10-25 19:55 UTC, Rene2mt commented on src/validations/constraints/content/ssp-all-VALID.xml
> +         <p>The highest level manager who responsible for system operation on behalf of the System Owner.</p>
Fixed in commit https://github.com/GSA/fedramp-automation/commit/5e2b2504719cf162ea1cce901e47c48a71d02c79

2024-10-28 14:57 UTC, kyhu65867 approved these changes
This looks good to me, thanks!

2024-10-28 15:49 UTC, wandmagic approved these changes

2024-10-28 16:02 UTC, aj-stein-gsa approved these changes

2024-10-28 16:02 UTC, merged