Add back-matter 'has' constraints
GSA/fedramp-automation pull request #654
Opened 2024-09-06 05:30 UTC by Gabeblis

# Committer Notes

### Description 
Added back-matter 'has' constraints and tests for each of the constraints. These should be added as they are part of the effort write all of the constraints from the constraint tracker.

### Changes 
- Added constraints has-user-guide, has-rules-of-behavior, has-information-system-contingency-plan, has-configuration-management-plan, has-incident-response-plan, has-separation-of-duties-matrix to fedramp-external-constraints.xml.  
- Added pass and fail yaml tests for all of the above constraints.  
- Edited ssp-all-VALID to ensure all constraints pass correctly.  

{Please provide a description of what this PR accomplishes. Be sure to reference any issues addressed. If the PR is a work-in-progress submitted for early review, please submit the PR as a draft PR using the "Draft pull request" dropdown.}

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-09-10 12:48 UTC, Rene2mt submitted a review, later dismissed

2024-09-10 20:57 UTC, Gabeblis commented
> This is all good, do we have docs on automate.fedramp.gov to align with the attachment requirements for a SSP? In [the SSP guidance](https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping), we call out an interconnection agreement, network diagram, and dataflow diagram, but not many of the attachments needed here.

All of them except for has-separation-of-duties-matrix are addressed here: https://automate.fedramp.gov/documentation/ssp/5-attachments/ 
There is an issue (https://github.com/GSA/fedramp-automation/issues/534) and draft PR (https://github.com/GSA/fedramp-automation/pull/594) for adding documentation for separation of duties.

2024-09-10 20:57 UTC, aj-stein-gsa requested changes

2024-09-10 20:57 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +        <expect id="has-user-guide" target="back-matter" test="resource[prop[@name eq 'type' and @value eq 'users-guide']]" level="WARNING">
This section of attachment constraints are great. We may want to make sure we align these attachment checks with the current public list of required documents.

https://automate.fedramp.gov/documentation/ssp/5-attachments/

2024-09-10 20:57 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +        <expect id="has-user-guide" target="back-matter" test="resource[prop[@name eq 'type' and @value eq 'users-guide']]" level="WARNING">
And also, I am not sure we want _only_ a warning and not an error? These are important requirements for FR review, did the previous Schematron rules mark them warning too? (I know a reason that could have been when I was last here, but not the latest of the Schematron rules).

2024-09-10 21:01 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +        <expect id="has-user-guide" target="back-matter" test="resource[prop[@name eq 'type' and @value eq 'users-guide']]" level="WARNING">
These are all currently marked as a warning in the Schematron.

2024-09-10 21:08 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +        <expect id="has-user-guide" target="back-matter" test="resource[prop[@name eq 'type' and @value eq 'users-guide']]" level="WARNING">
> This section of attachment constraints are great. We may want to make sure we align these attachment checks with the current public list of required documents.
> 
> https://automate.fedramp.gov/documentation/ssp/5-attachments/

These constraints align with those checks. Should we mention that they are required in the SSP, or is that implied?

2024-09-10 21:16 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +        <expect id="has-user-guide" target="back-matter" test="resource[prop[@name eq 'type' and @value eq 'users-guide']]" level="WARNING">
Ah I see your above comment, disregard!

2024-09-10 21:16 UTC, aj-stein-gsa commented
> > This is all good, do we have docs on automate.fedramp.gov to align with the attachment requirements for a SSP? In [the SSP guidance](https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping), we call out an interconnection agreement, network diagram, and dataflow diagram, but not many of the attachments needed here.
> 
> All of them except for has-separation-of-duties-matrix are addressed here: https://automate.fedramp.gov/documentation/ssp/5-attachments/ There is an issue (#534) and draft PR (#594) for adding documentation for separation of duties.

OK then we are in a good place, I will re-review in a bit.

2024-09-11 12:51 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +        <expect id="has-user-guide" target="back-matter" test="resource[prop[@name eq 'type' and @value eq 'users-guide']]" level="WARNING">
I had some discussions with @david-waltermire and thought about it some given our docs. You cannot really submit a valid SSP without them, so we need these to be ERROR.

2024-09-11 12:55 UTC, aj-stein-gsa requested changes
See https://github.com/GSA/fedramp-automation/pull/654/files#r1754412173 for updated review and proposed changes.

2024-09-11 12:55 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +        <expect id="has-user-guide" target="back-matter" test="resource[prop[@name eq 'type' and @value eq 'users-guide']]" level="WARNING">
See https://github.com/GSA/fedramp-automation/pull/654/files#r1754412173.

```suggestion
        <expect id="has-user-guide" target="back-matter" test="resource[prop[@name eq 'type' and @value eq 'users-guide']]" level="ERROR">
```

2024-09-11 12:55 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +        <expect id="has-rules-of-behavior" target="back-matter" test="resource[prop[@name eq 'type' and @value eq 'rules-of-behavior']]" level="WARNING">
See https://github.com/GSA/fedramp-automation/pull/654/files#r1754412173.

```suggestion
        <expect id="has-rules-of-behavior" target="back-matter" test="resource[prop[@name eq 'type' and @value eq 'rules-of-behavior']]" level="ERROR">
```

2024-09-11 12:55 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +        <expect id="has-information-system-contingency-plan" target="back-matter" test="resource[prop[@name eq 'type' and @value eq 'plan' and @class eq 'information-system-contingency-plan']]" level
See https://github.com/GSA/fedramp-automation/pull/654/files#r1754412173.

```suggestion
        <expect id="has-information-system-contingency-plan" target="back-matter" test="resource[prop[@name eq 'type' and @value eq 'plan' and @class eq 'information-system-contingency-plan']]" level="ERROR">
```

2024-09-11 12:55 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +        <expect id="has-configuration-management-plan" target="back-matter" test="resource[prop[@name eq 'type' and @value eq 'plan' and @class eq 'configuration-management-plan']]" level="WARNING">
See https://github.com/GSA/fedramp-automation/pull/654/files#r1754412173.

```suggestion
        <expect id="has-configuration-management-plan" target="back-matter" test="resource[prop[@name eq 'type' and @value eq 'plan' and @class eq 'configuration-management-plan']]" level="ERROR">
```

2024-09-11 12:55 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +        <expect id="has-incident-response-plan" target="back-matter" test="resource[prop[@name eq 'type' and @value eq 'plan' and @class eq 'incident-response-plan']]" level="WARNING">
See https://github.com/GSA/fedramp-automation/pull/654/files#r1754412173.

```suggestion
        <expect id="has-incident-response-plan" target="back-matter" test="resource[prop[@name eq 'type' and @value eq 'plan' and @class eq 'incident-response-plan']]" level="ERROR">
```

2024-09-11 12:55 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +        <expect id="has-separation-of-duties-matrix" target="back-matter" test="resource[prop[@name eq 'type' and @value eq 'separation-of-duties-matrix']]" level="WARNING">
See https://github.com/GSA/fedramp-automation/pull/654/files#r1754412173.

```suggestion
        <expect id="has-separation-of-duties-matrix" target="back-matter" test="resource[prop[@name eq 'type' and @value eq 'separation-of-duties-matrix']]" level="ERROR">
```

2024-09-11 13:16 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +        <expect id="has-user-guide" target="back-matter" test="resource[prop[@name eq 'type' and @value eq 'users-guide']]" level="WARNING">
> See https://github.com/GSA/fedramp-automation/pull/654/files#r1754412173.

Adressed in 393b1dbdc1edd1fb49bbe9e244f10f4f04454973

2024-09-11 13:17 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +        <expect id="has-rules-of-behavior" target="back-matter" test="resource[prop[@name eq 'type' and @value eq 'rules-of-behavior']]" level="WARNING">
adressed in 393b1dbdc1edd1fb49bbe9e244f10f4f04454973

2024-09-11 13:18 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +        <expect id="has-separation-of-duties-matrix" target="back-matter" test="resource[prop[@name eq 'type' and @value eq 'separation-of-duties-matrix']]" level="WARNING">
> See https://github.com/GSA/fedramp-automation/pull/654/files#r1754412173.

adressed in 393b1dbdc1edd1fb49bbe9e244f10f4f04454973

2024-09-11 13:19 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +        <expect id="has-incident-response-plan" target="back-matter" test="resource[prop[@name eq 'type' and @value eq 'plan' and @class eq 'incident-response-plan']]" level="WARNING">
> See https://github.com/GSA/fedramp-automation/pull/654/files#r1754412173.

addressed in 393b1dbdc1edd1fb49bbe9e244f10f4f04454973

2024-09-11 13:19 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +        <expect id="has-configuration-management-plan" target="back-matter" test="resource[prop[@name eq 'type' and @value eq 'plan' and @class eq 'configuration-management-plan']]" level="WARNING">
> See https://github.com/GSA/fedramp-automation/pull/654/files#r1754412173.

addressed in 393b1dbdc1edd1fb49bbe9e244f10f4f04454973

2024-09-11 13:19 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +        <expect id="has-information-system-contingency-plan" target="back-matter" test="resource[prop[@name eq 'type' and @value eq 'plan' and @class eq 'information-system-contingency-plan']]" level
> See https://github.com/GSA/fedramp-automation/pull/654/files#r1754412173.

addressed in 393b1dbdc1edd1fb49bbe9e244f10f4f04454973

2024-09-11 13:55 UTC, aj-stein-gsa approved these changes

2024-09-11 14:03 UTC, aj-stein-gsa approved these changes

2024-09-11 14:03 UTC, merged