Add system-characteristics 'has-security' constraints
GSA/fedramp-automation pull request #669
Opened 2024-09-10 13:53 UTC by Gabeblis

# Committer Notes

### Description 
Added system-characteristics 'has-security' constraints and tests for each of the constraints. These should be added as they are part of the effort write all of the constraints from the constraint tracker.

### Changes 
- Added constraints has-security-sensitivity-level, has-security-impact-level, has-security-objective-confidentiality, has-security-objective-integrity, has-security-objective-availability to fedramp-external-constraints.xml.   
- Added pass and fail yaml tests for all of the above constraints.  
- Edited ssp-all-INVALID.xml to ensure all constraints fail correctly.  

{Please provide a description of what this PR accomplishes. Be sure to reference any issues addressed. If the PR is a work-in-progress submitted for early review, please submit the PR as a draft PR using the "Draft pull request" dropdown.}

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-09-10 16:41 UTC, aj-stein-gsa commented
> Can you @Rene2mt sync on this PR and #610. I know they are different but there is some overlap, so I would like to review synchronously while we are on a call, perhaps tail end of standup today?

AJ will disregard his own remark given our discussion during today's standup, a more comprehensive review is needed and warranted. @Gabeblis gets tell me "Overruled!" 😆

2024-10-29 20:03 UTC, DimitriZhurkin requested changes

2024-10-29 20:03 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>An OSCAL SSP document must specify a security impact level.</message>
Ditto.

2024-10-29 20:03 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>An OSCAL SSP document must specify a FIPS 199 categorization.</message>
Looking at newer constraints, I think it should say, `A FedRAMP SSP document MUST...`.

2024-10-29 20:04 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>An OSCAL SSP document must specify a FIPS 199 categorization.</message>
So valid. Thanks for catching that.

2024-10-29 20:13 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>An OSCAL SSP document must specify a FIPS 199 categorization.</message>
Resolved: [b5e36cf](https://github.com/GSA/fedramp-automation/pull/669/commits/b5e36cf92b1f9ba97e4245fca6caaf5c69623eb3)

2024-10-29 20:39 UTC, DimitriZhurkin requested changes

2024-10-29 20:39 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>An OSCAL SSP document MUST specify a FIPS 199 categorization.</message>
Since it's a FedRAMP-specific test, the message probably should say, `A FedRAMP SSP document...`

2024-10-29 20:39 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>An OSCAL SSP document MUST specify a security impact level.</message>
Ditto.

2024-10-29 20:43 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>An OSCAL SSP document MUST specify a FIPS 199 categorization.</message>
Another good catch. Resolved: [fe823d3](https://github.com/GSA/fedramp-automation/pull/669/commits/fe823d3ed4d026adf871d349839097eebea1c5d9)

2024-10-29 20:43 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>An OSCAL SSP document MUST specify a security impact level.</message>
Resolved: [fe823d3](https://github.com/GSA/fedramp-automation/pull/669/commits/fe823d3ed4d026adf871d349839097eebea1c5d9)

2024-10-29 21:30 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>An OSCAL SSP document must specify a security impact level.</message>
Resolved: [fe823d3](https://github.com/GSA/fedramp-automation/pull/669/commits/fe823d3ed4d026adf871d349839097eebea1c5d9)

2024-10-30 12:32 UTC, aj-stein-gsa approved these changes

2024-10-30 13:50 UTC, DimitriZhurkin approved these changes

2024-10-30 19:56 UTC, merged