Add three SSP metadata role constraints
GSA/fedramp-automation pull request #676
Opened 2024-09-10 17:51 UTC by DimitriZhurkin

# Committer Notes

Add the following three constraints:
1. role-defined-authorizing-official-poc
2. role-defined-information-system-security-officer
3. role-defined-system-poc-other

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-09-10 19:46 UTC, aj-stein-gsa commented on src/scripts/dev-constraint.cjs
>      }
Non-blocking: can we explain why these changes were made and what the intended goal is? These changes seem separate of a constraint update, so I want to check we know what we're doing here and if it is necessary now.

2024-09-10 19:50 UTC, DimitriZhurkin commented on src/scripts/dev-constraint.cjs
>      }
Hmm, I'm not sure where these changes came from. I have not modified the dev-constraint.cjs file.

2024-09-10 19:58 UTC, aj-stein-gsa commented on src/scripts/dev-constraint.cjs
>      }
If you know how to revert individual file changes from a commit, please do so. Otherwise, I read out the diff output to make a suggestion, just accept this change and I _think_ you will get it back to the way it was. Let me know. If successful, there will be no change on this file afterward.

```suggestion
    let scenarioLines = getScenarioLineNumbers(featureFile, constraintId,testFiles);

    if (scenarioLines.length === 0) {
        console.error(`No scenarios found for constraintId: ${constraintId}`);
        execSync("npm run test:coverage",{stdio:'ignore'});
        scenarioLines = getScenarioLineNumbers(featureFile, constraintId,testFiles);
        if(scenarioLines.length===0){
        return false;
        }
    }
```

2024-09-10 20:04 UTC, DimitriZhurkin commented on src/scripts/dev-constraint.cjs
>      }
I don't even see that file in my commit, and I couldn't find when it had been changed in history.

2024-09-10 20:18 UTC, aj-stein-gsa requested changes

2024-09-10 20:18 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +        <metapath target="/system-security-plan"/>
Blocking: I may be misinterpreting the current documentation (which does explain this in the SSP guide, I will give you that), but the legacy implementation in Schematron defines these "generically" and does not bind the context to one document type. For these, it could apply potentially be defined or redefined in independent OSCAL documents (you may share a SAR and not a SSP with people who need to know the authorizing official). I will consult "The Oracle" for 100% confirmation, but I would say this is a good case where we want it for all docs.

I think this will work but not %100 sure, you get the idea.

```suggestion
        <metapath target="//metadata"/>
```

2024-09-10 20:18 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +    </context>
More follow-on from my previous comment ☝️.

```suggestion
        <constraints>
        	<expect id="role-defined-authorizing-official-poc" target="role" test=".[@id eq 'authorizing-official-poc']" level="ERROR">
            	<message>Metadata must have the authorizing official POC role.</message>
            </expect>
        	<expect id="role-defined-information-system-security-officer" target="role" test=".[@id eq 'information-system-security-officer']" level="ERROR">
                <message>Metadata must have the information system security officer POC role.</message>
            </expect>
        	<expect id="role-defined-system-poc-other" target="role" test=".[@id eq 'system-poc-other']" level="ERROR">
                <message>Metadata must have the system other POC role.</message>
            </expect>
        </constraints>
    </context>
```

I would want a weigh-in from @david-waltermire on this one, but I presume he'll agree to this take. I am not 100% sure it will work, but this structure I think it's the impression.

2024-09-10 21:08 UTC, DimitriZhurkin commented on src/scripts/dev-constraint.cjs
>      }
AJ,

I think Paul had made these changes some time ago, and when I pulled the repo yesterday, it overwrote `dev-constraint.cjs` on my local system.

Then, when I pushed my constraints today, the push also picked up the modified `dev-constraint.cjs` file.

It's a bit confusing now, which version of `dev-constraint.cjs` is correct. Might wanna wait for Paul's input on that puppy.

2024-09-10 21:32 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +        <metapath target="/system-security-plan"/>
Disregard this feedback, I had a thought it through and decided you were right and I was wrong on this recommendation.

2024-09-10 21:32 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +    </context>
Disregard this feedback, I had a thought it through and decided you were right and I was wrong on this recommendation.

2024-09-10 21:33 UTC, aj-stein-gsa commented on src/scripts/dev-constraint.cjs
>      }
Perhaps it is a rebase issue (where you made a branch of your PR code from a copy of feature/external-constraints, but slightly old). So do not worry about it, I can look. I will resolve this when it is approved so I do not forget to check. Re the code I don't want to change functionality and revert the Javascript because it may bork the tests for you and others if not careful, so I totally agree.

2024-09-11 01:15 UTC, aj-stein-gsa reviewed
Looks good, but I too have questions about `role-defined-system-poc-other`.

2024-09-11 01:15 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            </expect>
This PR looks good and the others roles make sense, I looked up current docs and will need to do some history study in old Schematron and pre-website docs, I have never seen a requirement for this role before. I see you noted the same in the spreadsheet. Can we discuss this tomorrow morning?

2024-09-11 11:30 UTC, wandmagic commented on src/scripts/dev-constraint.cjs
>      }
yes looks like an out dated version of the dev constraint script, that line is meant to handle the case where a new constraint is made but the full test runner hasn't been run and the feature file needs to be updated. but its best to rebase or leave as is on the feature/external-constraints, it shouldn't alter how the tests run at all since it is a different path

2024-09-11 13:50 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +            </expect>
I also have doubts about this `system-poc-other role`.
I couldn't find it in the rev 5 documentation at all. Wonder if it has been deprecated.

2024-09-11 18:46 UTC, aj-stein-gsa commented
I am going to close this out in favor of https://github.com/GSA/fedramp-automation/pull/686. Thanks for the update, Dimtri.

2024-09-11 18:46 UTC, closed without merging