Add system-characteristics 'information-type' constraints
GSA/fedramp-automation pull request #685
Opened 2024-09-11 18:10 UTC by Gabeblis

# Committer Notes

{Please provide a description of what this PR accomplishes. Be sure to reference any issues addressed. If the PR is a work-in-progress submitted for early review, please submit the PR as a draft PR using the "Draft pull request" dropdown.}

### Description 
Added system-characteristics 'information-type' constraints and tests for each of the constraints. These should be added as they are part of the effort write all of the constraints from the constraint tracker.  

### Changes 
- Added constraints information-type-has-confidentiality-impact, information-type-has-integrity-impact, information-type-has-availability-impact to fedramp-external-constraints.xml.  
- Added pass and fail yaml tests for all of the above constraints.  
- Edited ssp-all-INVALID.xml to ensure all constraints fail correctly.  

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-09-11 18:55 UTC, aj-stein-gsa requested changes
Does this also have overlap with #610? Seems so.

2024-09-11 19:14 UTC, Gabeblis commented
> Does this also have overlap with #610? Seems so.

These constraints should all exist. The only overlap is the issue that we discussed yesterday with Dave regarding allowed-values constraints and expect constraints sharing the same ssp-all-INVALID file.

2024-09-11 20:34 UTC, aj-stein-gsa commented
> > Does this also have overlap with #610? Seems so.
> 
> These constraints should all exist. The only overlap is the issue that we discussed yesterday with Dave regarding allowed-values constraints and expect constraints sharing the same ssp-all-INVALID file.

OK disregard, I can see what you mean. I am still going to need to wrap up some docs pertaining to the doc gaps for this and #610 tracked in https://github.com/GSA/automate.fedramp.gov/issues/55. Sorry for the delayed reply.

2024-10-29 20:54 UTC, DimitriZhurkin requested changes

2024-10-29 20:54 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>An OSCAL SSP information type MUST have a confidentiality impact.</message>
The message should probably start with `A FedRAMP SSP...`

2024-10-29 20:54 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>An OSCAL SSP information type MUST have an integrity impact.</message>
Ditto message.

2024-10-29 20:54 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>An OSCAL SSP information type MUST have an availability impact.</message>
Ditto message.

2024-10-29 20:54 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#system-informat
Ditto `help-url`.

2024-10-29 20:54 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#system-informat
Ditto `help-url`.

2024-10-29 20:54 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#system-informat
In the `help-url` URL, the `#system-information-and-information-types` anchor  didn't work for me.

Is it work in progress?

2024-10-29 20:54 UTC, DimitriZhurkin commented on src/validations/constraints/unit-tests/information-type-has-availability-impact-FAIL.yaml
> +  description: Test that a SSP system-characteristics system-information information-type element does not have an availability-impact element.
`a SSP` should be `an SSP`.

2024-10-29 20:54 UTC, DimitriZhurkin commented on src/validations/constraints/unit-tests/information-type-has-availability-impact-PASS.yaml
> +  description: Test that a SSP system-characteristics system-information information-type element has an availability-impact element.
Ditto `a SSP`.

2024-10-29 20:54 UTC, DimitriZhurkin commented on src/validations/constraints/unit-tests/information-type-has-confidentiality-impact-FAIL.yaml
> +  description: Test that a SSP system-characteristics system-information information-type element does not have a confidentiality-impact element.
Ditto `a SSP`.

2024-10-29 20:54 UTC, DimitriZhurkin commented on src/validations/constraints/unit-tests/information-type-has-confidentiality-impact-PASS.yaml
> +  description: Test that a SSP system-characteristics system-information information-type element has a confidentiality-impact element.
Ditto `a SSP`.

2024-10-29 20:54 UTC, DimitriZhurkin commented on src/validations/constraints/unit-tests/information-type-has-integrity-impact-FAIL.yaml
> +  description: Test that a SSP system-characteristics system-information information-type element does not have an integrity-impact element.
Ditto `a SSP`.

2024-10-29 20:54 UTC, DimitriZhurkin commented on src/validations/constraints/unit-tests/information-type-has-integrity-impact-PASS.yaml
> +  description: Test that a SSP system-characteristics system-information information-type element has an integrity-impact element.
Ditto `a SSP`.

2024-10-29 21:32 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>An OSCAL SSP information type MUST have a confidentiality impact.</message>
Thanks. Resolved: [1311a8d](https://github.com/GSA/fedramp-automation/pull/685/commits/1311a8de68b0f4d6ff507640fdd2e041cd912557)

2024-10-29 21:32 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>An OSCAL SSP information type MUST have an integrity impact.</message>
Resolved: [1311a8d](https://github.com/GSA/fedramp-automation/pull/685/commits/1311a8de68b0f4d6ff507640fdd2e041cd912557)

2024-10-29 21:32 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>An OSCAL SSP information type MUST have an availability impact.</message>
Resolved: [1311a8d](https://github.com/GSA/fedramp-automation/pull/685/commits/1311a8de68b0f4d6ff507640fdd2e041cd912557)

2024-10-29 21:59 UTC, Gabeblis commented on src/validations/constraints/unit-tests/information-type-has-availability-impact-FAIL.yaml
> +  description: Test that a SSP system-characteristics system-information information-type element does not have an availability-impact element.
Thanks! Resolved: [d5768dc](https://github.com/GSA/fedramp-automation/pull/685/commits/d5768dcd9df6f71e97829806125b7cff449faa20)

2024-10-29 21:59 UTC, Gabeblis commented on src/validations/constraints/unit-tests/information-type-has-availability-impact-PASS.yaml
> +  description: Test that a SSP system-characteristics system-information information-type element has an availability-impact element.
Resolved: [d5768dc](https://github.com/GSA/fedramp-automation/pull/685/commits/d5768dcd9df6f71e97829806125b7cff449faa20)

2024-10-29 21:59 UTC, Gabeblis commented on src/validations/constraints/unit-tests/information-type-has-confidentiality-impact-FAIL.yaml
> +  description: Test that a SSP system-characteristics system-information information-type element does not have a confidentiality-impact element.
Resolved: [d5768dc](https://github.com/GSA/fedramp-automation/pull/685/commits/d5768dcd9df6f71e97829806125b7cff449faa20)

2024-10-29 22:00 UTC, Gabeblis commented on src/validations/constraints/unit-tests/information-type-has-confidentiality-impact-PASS.yaml
> +  description: Test that a SSP system-characteristics system-information information-type element has a confidentiality-impact element.
Resolved: [d5768dc](https://github.com/GSA/fedramp-automation/pull/685/commits/d5768dcd9df6f71e97829806125b7cff449faa20)

2024-10-29 22:00 UTC, Gabeblis commented on src/validations/constraints/unit-tests/information-type-has-integrity-impact-FAIL.yaml
> +  description: Test that a SSP system-characteristics system-information information-type element does not have an integrity-impact element.
Resolved: [d5768dc](https://github.com/GSA/fedramp-automation/pull/685/commits/d5768dcd9df6f71e97829806125b7cff449faa20)

2024-10-29 22:00 UTC, Gabeblis commented on src/validations/constraints/unit-tests/information-type-has-integrity-impact-PASS.yaml
> +  description: Test that a SSP system-characteristics system-information information-type element has an integrity-impact element.
Resolved: [d5768dc](https://github.com/GSA/fedramp-automation/pull/685/commits/d5768dcd9df6f71e97829806125b7cff449faa20)

2024-10-29 22:03 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#system-informat
Thanks for catching that. Yes, the [documentation](https://github.com/GSA/automate.fedramp.gov/pull/87) has been merged into develop in automate.fedramp. The develop branch hasn't been merged into main with this updated content just yet, so you will not see in on the website until that happens.

2024-10-29 22:03 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#system-informat
Thanks for catching that. Yes, the [documentation](https://github.com/GSA/automate.fedramp.gov/pull/87) has been merged into develop in automate.fedramp. The develop branch hasn't been merged into main with this updated content just yet, so you will not see in on the website until that happens.

2024-10-29 22:03 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#system-informat
Thanks for catching that. Yes, the [documentation](https://github.com/GSA/automate.fedramp.gov/pull/87) has been merged into develop in automate.fedramp. The develop branch hasn't been merged into main with this updated content just yet, so you will not see in on the website until that happens.

2024-10-30 14:35 UTC, DimitriZhurkin approved these changes

2024-10-30 19:03 UTC, wandmagic approved these changes

2024-10-30 19:31 UTC, aj-stein-gsa approved these changes

2024-10-30 19:32 UTC, merged