Add system-characteristics 'cia-has' and 'has-system-name-short' constraints
GSA/fedramp-automation pull request #689
Opened 2024-09-13 13:14 UTC by Gabeblis

# Committer Notes

### Description 
Added system-characteristics 'cia-has' and 'has-system-name-short' constraints and tests for each of the constraints. These should be added as they are part of the effort write all of the constraints from the constraint tracker. 

### Changes 
- Added constraints cia-impact-has-selected, cia-impact-has-adjustment-justification, and has-system-name-short to fedramp-external-constraints.xml. 
- Added pass and fail yaml tests for all of the above constraints.  
- Edited ssp-all-INVALID.xml to ensure all constraints fail correctly.  
- Edited ssp-all-VALID.xml to ensure all constraints pass correctly.  

{Please provide a description of what this PR accomplishes. Be sure to reference any issues addressed. If the PR is a work-in-progress submitted for early review, please submit the PR as a draft PR using the "Draft pull request" dropdown.}

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-09-13 15:30 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +        <expect id="cia-impact-has-adjustment-justification" target="//system-characteristics/system-information/information-type/confidentiality-impact | //system-characteristics/system-information/
Non-blocking for now: quick question for the team, as this style actually has me confused and was part of the reason I wanted to move forward with #675. We have a parent context of `/system-security-plan`, then the target has `//...` what does that mean? This would not mean accepting a system-characteristics anywhere, not just at `/system-security-plan/system-characteristics` alone correct? Can we not be "tighter" here?

Other than that, I love a good clean constraint and this was a great read!

```suggestion
        <expect id="cia-impact-has-adjustment-justification" target="//system-characteristics/system-information/information-type/confidentiality-impact | //system-characteristics/system-information/information-type/integrity-impact | //system-characteristics/system-information/information-type/availability-impact" test="if (base ne selected or not(exists(selected))) then exists(adjustment-justification) else true()" level="ERROR">
```

```suggestion
        <expect id="cia-impact-has-adjustment-justification" target="system-characteristics/system-information/information-type/confidentiality-impact | system-characteristics/system-information/information-type/integrity-impact | system-characteristics/system-information/information-type/availability-impact" test="if (base ne selected or not(exists(selected))) then exists(adjustment-justification) else true()" level="ERROR">
```

2024-09-13 21:40 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +        <expect id="cia-impact-has-adjustment-justification" target="//system-characteristics/system-information/information-type/confidentiality-impact | //system-characteristics/system-information/
> /system-security-plan/system-characteristics

This would mean that it targets every occurrence of 'system-characteristics' within the parent element 'system-security-plan'. I wrote it this way just so it was cleaner and the target was clear. It could've also been written specifying the full path as /system-security-plan/metadata/system-characteristics.

2024-09-16 12:30 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +        <expect id="cia-impact-has-adjustment-justification" target="//system-characteristics/system-information/information-type/confidentiality-impact | //system-characteristics/system-information/
I think in terms of style and with the use of the wrapping `/system-security-plan` we may want to adjust the notation to make it a little more clear.

2024-09-16 12:41 UTC, aj-stein-gsa requested changes

2024-09-16 12:41 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +        <expect id="has-system-name-short" target="//system-characteristics" test="system-name-short" level="ERROR">
Recommended change

```suggestion
        <expect id="has-system-name-short" target="./system-characteristics" test="system-name-short" level="ERROR">
```

2024-09-16 12:50 UTC, aj-stein-gsa reviewed
Woops, meant to be an approval.

2024-09-16 12:51 UTC, aj-stein-gsa submitted a review, later dismissed
These looks good, thanks for the work here. We still need documentation updates. I will approve but hold for merge.

Hold for GSA/automate.fedramp.gov#55 and GSA/automate.fedramp.gov#58.

2024-10-29 21:16 UTC, DimitriZhurkin requested changes

2024-10-29 21:16 UTC, DimitriZhurkin commented on src/validations/constraints/content/ssp-all-VALID.xml
> +          <!-- adjustment-justification removed to ensure cia-impact-has-adjustment-justification passes when base and selected have the same impact level -->
Are you planning to restore `<adjustment-justification>`?

I don't see it--and `<selected>`--in the current `ssp-all-VALID.xml` (the file has probably changed since you created this PR.

2024-10-29 21:16 UTC, DimitriZhurkin commented on src/validations/constraints/content/ssp-all-VALID.xml
> +          </adjustment-justification>
Ditto. I don't see either `<selected>` or `<adjustment-justification>` in the current `ssp-all-VALID.xml` file.

2024-10-29 21:16 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>When SP 800-60 base and selected impacts levels differ for a given information type, the SSP MUST include a justification for the difference.</message>
I would change `the SSP` into `a FedRAMP SSP`.

2024-10-29 21:16 UTC, DimitriZhurkin commented on src/validations/constraints/unit-tests/cia-impact-has-adjustment-justification-FAIL.yaml
> +  description: Test that if a SSP system-characteristics system-information information-type (confidentiality-impact/integrity-impact/availability-impact) base element is not equal to the selected el
`a SSP` should be `an SSP`.

2024-10-29 21:16 UTC, DimitriZhurkin commented on src/validations/constraints/unit-tests/cia-impact-has-adjustment-justification-PASS.yaml
> +  description: Test that if a SSP system-characteristics system-information information-type (confidentiality-impact/integrity-impact/availability-impact) base element is not equal to the selected el
Ditto `a SSP`.

2024-10-29 21:16 UTC, DimitriZhurkin commented on src/validations/constraints/unit-tests/cia-impact-has-selected-FAIL.yaml
> +  description: Test that a SSP system-characteristics system-information information-type (confidentiality-impact/integrity-impact/availability-impact) element does not have a selected element.
Ditto `a SSP`.

2024-10-29 21:16 UTC, DimitriZhurkin commented on src/validations/constraints/unit-tests/cia-impact-has-selected-PASS.yaml
> +  description: Test that a SSP system-characteristics system-information information-type (confidentiality-impact/integrity-impact/availability-impact) element has selected element.
Ditto `a SSP`.

2024-10-29 21:16 UTC, DimitriZhurkin commented on src/validations/constraints/unit-tests/has-system-name-short-FAIL.yaml
> +  description: Test that a SSP system-characteristics element does not have a system-name-short element.
Ditto `a SSP`.

2024-10-29 21:16 UTC, DimitriZhurkin commented on src/validations/constraints/unit-tests/has-system-name-short-PASS.yaml
> +  description: Test that a SSP system-characteristics element has a system-name-short element.
Ditto `a SSP`.

2024-10-29 21:48 UTC, Gabeblis commented on src/validations/constraints/content/ssp-all-VALID.xml
> +          <!-- adjustment-justification removed to ensure cia-impact-has-adjustment-justification passes when base and selected have the same impact level -->
These changes are necessary for the constraint to fire and pass correctly. This isn't in the current ssp-all-VALID because these constraints are not in the develop branch. They are being added with this PR

2024-10-29 21:49 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>When SP 800-60 base and selected impacts levels differ for a given information type, the SSP MUST include a justification for the difference.</message>
These changes are necessary for the constraint to fire and pass correctly. This isn't in the current ssp-all-VALID because these constraints are not in the develop branch. They are being added with this PR

2024-10-29 21:56 UTC, Gabeblis commented on src/validations/constraints/content/ssp-all-VALID.xml
> +          </adjustment-justification>
These changes are necessary for the constraint to fire and pass correctly. This isn't in the current ssp-all-VALID because these constraints are not in the develop branch. They are being added with this PR

2024-10-29 21:57 UTC, Gabeblis commented on src/validations/constraints/unit-tests/cia-impact-has-adjustment-justification-FAIL.yaml
> +  description: Test that if a SSP system-characteristics system-information information-type (confidentiality-impact/integrity-impact/availability-impact) base element is not equal to the selected el
Thanks! Resolved: [ad156ce](https://github.com/GSA/fedramp-automation/pull/689/commits/ad156ceacde6c92f520efbc77d5736b1a26c288c)

2024-10-29 21:57 UTC, Gabeblis commented on src/validations/constraints/unit-tests/cia-impact-has-selected-FAIL.yaml
> +  description: Test that a SSP system-characteristics system-information information-type (confidentiality-impact/integrity-impact/availability-impact) element does not have a selected element.
Resolved: [ad156ce](https://github.com/GSA/fedramp-automation/pull/689/commits/ad156ceacde6c92f520efbc77d5736b1a26c288c)

2024-10-29 21:57 UTC, Gabeblis commented on src/validations/constraints/unit-tests/cia-impact-has-adjustment-justification-PASS.yaml
> +  description: Test that if a SSP system-characteristics system-information information-type (confidentiality-impact/integrity-impact/availability-impact) base element is not equal to the selected el
Resolved: [ad156ce](https://github.com/GSA/fedramp-automation/pull/689/commits/ad156ceacde6c92f520efbc77d5736b1a26c288c)

2024-10-29 21:57 UTC, Gabeblis commented on src/validations/constraints/unit-tests/has-system-name-short-FAIL.yaml
> +  description: Test that a SSP system-characteristics element does not have a system-name-short element.
Resolved: [ad156ce](https://github.com/GSA/fedramp-automation/pull/689/commits/ad156ceacde6c92f520efbc77d5736b1a26c288c)

2024-10-29 21:57 UTC, Gabeblis commented on src/validations/constraints/unit-tests/has-system-name-short-PASS.yaml
> +  description: Test that a SSP system-characteristics element has a system-name-short element.
Resolved: [ad156ce](https://github.com/GSA/fedramp-automation/pull/689/commits/ad156ceacde6c92f520efbc77d5736b1a26c288c)

2024-10-30 14:39 UTC, DimitriZhurkin submitted a review, later dismissed

2024-10-30 21:58 UTC, Rene2mt submitted a review, later dismissed
PR looks good!

2024-10-30 22:30 UTC, aj-stein-gsa submitted a review, later dismissed
I am happy with this PR as it progressed, but we need to rebase. I can look into this because, per our style guide reqs, that rebase should include alphabetically sorting (the target branch on rebase screwed that up when I merged, not @Gabeblis).

2024-10-30 22:35 UTC, aj-stein-gsa commented
> I am happy with this PR as it progressed, but we need to rebase. I can look into this because, per our style guide reqs, that rebase should include alphabetically sorting (the target branch on rebase screwed that up when I merged, not @Gabeblis).

You know what? Nevermind, no. I will open a chore PR to fix that lest I mess things up. 😆

2024-10-30 22:46 UTC, merged