Add ADR for constraint-based help documentation by URL for SARIF-based results output
GSA/fedramp-automation pull request #735
Opened 2024-09-26 20:08 UTC by aj-stein-gsa

# Committer Notes

{Please provide a description of what this PR accomplishes. Be sure to reference any issues addressed. If the PR is a work-in-progress submitted for early review, please submit the PR as a draft PR using the "Draft pull request" dropdown.}

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-09-27 14:31 UTC, aj-stein-gsa commented on documents/adr/0009-constraint-based-help-docs.md
> +1. Allow for Metaschema properties to optionally define a URL for help information, text for help information without formatting, and/or formatted Markdown text for help information to interpolate in
@brian-ruf, you had mentioned you wanted some clarity around the flavor of Markdown, I can link to this part of the specification and say CommonMark in particular if that helps.

```suggestion
1. Allow for Metaschema properties to optionally define a URL for help information, text for help information without formatting, and/or formatted Markdown text (conformant with the [CommonMark specification, as required by the Metaschema specification](https://pages.nist.gov/metaschema/specification/datatypes/#markup-data-types)) for help information to interpolate into SARIF results. Require one, some, or all of these properties in a constraint style guide per [GSA/fedramp-automation#675](https://github.com/GSA/fedramp-automation/issues/675).
```

2024-09-27 14:48 UTC, aj-stein-gsa commented on documents/adr/0009-constraint-based-help-docs.md
> +1. The FedRAMP Team will request the maintainers of [metaschema-java](https://github.com/metaschema-framework/metaschema-java) and [oscal-cli](https://github.com/metaschema-framework/oscal-cli) to im
Also per discussion with @brian-ruf, I can add this to make it very clearly that `prop/@value` in Metaschema is of type string now and we are not proposing a change there, just simply shunting/tunneling/insert-relevant-verbing Markdown data in the string value.

```suggestion
1. The FedRAMP Team will request the maintainers of [metaschema-java](https://github.com/metaschema-framework/metaschema-java) and [oscal-cli](https://github.com/metaschema-framework/oscal-cli) to implement code to map props `help-url`, `help-text`, and `help-text-markdown` to the SARIF `helpUri` and `help` fields for constraints result outputs. The team will tunnel formatted help text data in Markdown syntax in a `prop`'s `value` with its current `string` data type as-is. We will _not_ propose a change to change its type or request an alternate Metschema structure to support inline Markdown with a [`markup-multiline`](https://pages.nist.gov/metaschema/specification/datatypes/#markup-data-types).
```

2024-09-27 15:56 UTC, aj-stein-gsa commented on documents/adr/0009-constraint-based-help-docs.md
> +```
@david-waltermire, when you have bandwidth, this is the only part I want quick feedback on from you as good enough, just right, or needs tweaks per its relationship to upcoming work on metaschema-framework/metaschema-java#131. Lemme know and I can adjust both issues as @brian-ruf is out of pocket for a bit.

2024-09-27 15:57 UTC, aj-stein-gsa commented on documents/adr/0009-constraint-based-help-docs.md
> +```
@david-waltermire, when you have bandwidth, this is the only part I want quick feedback on from you as good enough, just right, or needs tweaks per its relationship to upcoming work on metaschema-framework/metaschema-java#131. Lemme know and I can adjust both issues as @brian-ruf is out of pocket for a bit.

2024-09-29 21:22 UTC, david-waltermire commented on documents/adr/0009-constraint-based-help-docs.md
> +                <prop namespace="https://json.schemastore.org/sarif/2.1.0" name="help-markdown" value="# Data Center Requirements\nData centers must have a country.\nOnly certain countries allowed.\n
To align with https://github.com/metaschema-framework/metaschema-java/pull/139
```suggestion
                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#data-center"/>
                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-text" value="Data centers must have a country. Only certain countries allowed. See the list below: Country 1; Country 2; Country 3."/>
                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-markdown" value="# Data Center Requirements\nData centers must have a country.\nOnly certain countries allowed.\nSee the list below.\n- Country 1\n - Country 2\n - Country 3\n\n"/>
```

2024-09-30 12:22 UTC, Rene2mt submitted a review, later dismissed
Reviewed the draft ADR.  The ADR is clear and I'm onboard with the proposed option 4.

2024-09-30 18:29 UTC, Gabeblis submitted a review, later dismissed
Looks good. Context, possible solutions, and consequences are all clear. Solution 4 feels like the right balance of flexibility, scalability, and ease of implementation for all parties. 😄

2024-09-30 20:02 UTC, kyhu65867 requested changes
Just some small tweaks to make. I think comment numbers 1, 3, and 5 are blocking, and 2 and 4 are just suggestions that you can take or leave. Let me know what you think

2024-09-30 20:02 UTC, kyhu65867 commented on documents/adr/0009-constraint-based-help-docs.md
> +## Consequences
I would maybe structure this doc differently (although it could be counter to the ADR methodology) but it makes more sense to me if you start with the decision made, then walk through the different options considered and then looked at their various pros and cons. That way the most important info is right up at the top and if people are interested they can read more.

2024-09-30 20:09 UTC, aj-stein-gsa commented on documents/adr/0009-constraint-based-help-docs.md
> +1. Always embed help text directly into the constraints themselves for interpolation into SARIF results, in the `message` field or some other SARIF element, by use of the existing Metaschema `message
I get the confusion. Markdown allows you to use this syntax, so you can treat numbered lists like unordered lists and change the order. When it is later converted to HTML, they all end up incrementing 1 to N in the right order. GitHub and a lot of IDEs actually automatically do it for you in text, I leave it this way to re-order things. The only time it doesn't work well is when you have a multi-line code block between two items in the list, and then it starts over. You will notice this scenario is when I explicitly use numbering or you get 1; 2; code block for 2; 1; 2; 3 instead of 1; 2; code block for 2; 3; 4; 5 like we would often want!

I will close this, but I am willing to discuss more if you want it explicit or want a clearer explanation.

2024-09-30 20:12 UTC, aj-stein-gsa commented on documents/adr/0009-constraint-based-help-docs.md
> +2. After Step 1 is complete, A FedRAMP constraint style guide should recommend or require the use of `help-url`, `help-text`, and `help-markdown` props. Below is an example of how these properties ca
The should is sadly because it does not exist, but I am hinting with this proposal that if we agree to AJ's proposal and the decision (with group consent) moves forward, that is an immediate next step.

See #675 for more details. Does that clear things up a little more? I could adjust the wording if it would make more sense to say "will" or be more aggressive with "thou shalt." I was in a hurry Friday to wrap this PR up, but now I have time to edit accordingly! 😄

2024-09-30 20:12 UTC, aj-stein-gsa commented on documents/adr/0009-constraint-based-help-docs.md
> +1. This approach requires moderate effort for FedRAMP Automation Team developers maintaining constraints and developers of software for the FedRAMP ecosystem. The former will have to carefully editin
OK, can we talk about the careful edits in DM?

2024-09-30 20:13 UTC, aj-stein-gsa commented on documents/adr/0009-constraint-based-help-docs.md
> +## Consequences
I mean, I do not oppose that. Perhaps a change to the template is in order. I just like the idea of taking the time to write the content down, I am not dogmatic about the order. If a different order resonates with people, I am all for it!

2024-09-30 20:18 UTC, Gabeblis commented on documents/adr/0009-constraint-based-help-docs.md
> +1. This approach requires moderate effort for FedRAMP Automation Team developers maintaining constraints and developers of software for the FedRAMP ecosystem. The former will have to carefully editin
> OK, can we talk about the careful edits in DM?

```suggestion
1. This approach requires moderate effort for FedRAMP Automation Team developers maintaining constraints and developers of software for the FedRAMP ecosystem. The former will have to carefully edit new and existing constraints to track inserting additional information into the `message` field of a constraint. Downstream developers of software for the FedRAMP ecosystem will have to customize their tools to parse each message and extract different kinds of error information from the Metaschema modules or SARIF output without consistency and added complexity. It will, however, require little to no additional effort for maintainers of data and tool dependencies. Operationally, this may increase the size of constraint files and resulting results output in SARIF if guidance requires them to be output in all cases.
```

2024-09-30 21:56 UTC, kyhu65867 submitted a review, later dismissed
Good job AJ :) And with that, my first review is done!!

2024-09-30 22:21 UTC, aj-stein-gsa commented on documents/adr/0009-constraint-based-help-docs.md
> +There are multiple approaches for the team and larger community to consider.
I saw you or someone resolved it, but I thought still worth addressing.

https://github.com/GSA/fedramp-automation/pull/735/commits/6db699c2aa9b949ba0edfbbd14ad5d50b20ee64d

2024-10-01 18:51 UTC, david-waltermire commented on documents/adr/0009-constraint-based-help-docs.md
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-markdown" value="# Data Center Requirements\nData centers must have a country.\nOnly certain countries allo
```suggestion
                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-markdown" value="# Data Center Requirements\n\nData centers must have a country.\n\nOnly certain countries allowed.\n\nSee the list below.\n\n- Country 1\n - Country 2\n - Country 3\n"/>
```

2024-10-01 18:52 UTC, david-waltermire submitted a review, later dismissed

2024-10-01 19:15 UTC, merged