number of controls implimented constraints
GSA/fedramp-automation pull request #736
Opened 2024-09-27 11:10 UTC by wandmagic

# Committer Notes

constraints to assure the entire profile is implemented

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-09-27 16:07 UTC, aj-stein-gsa requested changes

2024-09-27 16:07 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Incomplete controls: {count(//implemented-requirement)} required: {count($all-imports//control)}</message>
Some controls can be there but a status that does not warrant counting them (e.g. planned). Can we please check the status for each constraint as well?

As an aside: did this approach come from intuition or the legacy Schematron rules? If the latter, I am surprised, so I just wanted to know if that is where you picked this query logic from.

2024-09-30 19:32 UTC, Rene2mt commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Incomplete controls: {count(//implemented-requirement)} required: {count($all-imports//control)}</message>
I see two scenarios for **incomplete-implemented-requirements**:

1. **no missing controls** - here, we'd want to confirm that all f the controls are accounted for, regardless of status.  In the early  stages (pre-authorization) when CSOs are designated as "FedRAMP Ready" or "FedRAMP In Process", many if not most of the controls will not be fully implemented yet.  If CSPs send preliminary versions of their SSPs to FedRAMP during these early stages, FedRAMP should ensure the CSP is at least accounting for all controls in the baseline.  IMO, missing control should be an ERROR level constraint.
2. **all controls are implemented** - My understanding is that all baseline controls should be "implemented" before being authorized, but there are exceptions though.  For example, during the transition from the rev 4 to rev 5 baselines, FedRAMP requested updated SSPs, with the understanding that some of the new controls would be "partially implemented" or "planned", and CSPs were given a timeframe for eventually implementing all controls. For that reason, I think might be a WARNING level constraint.

2024-09-30 21:43 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Incomplete controls: {count(//implemented-requirement)} required: {count($all-imports//control)}</message>
I agree with 1 and 2 for the record. I am worried that if we left the constraint as-is, the following _could_ be construed as implemented, we mislead people into writing a tool that emits just enough OSCAL to write this:

```xml
    <implemented-requirement uuid="bbbbbbbb-0000-4000-9000-00000000000b" control-id="pe-2">
       <!-- snipped everything above, because the prop below is what matters --> 
       <!--  <prop ns="https://fedramp.gov/ns/oscal" name="implementation-status" value="none-by-implication-commented-out"/> -->
      </by-component>
    </implemented-requirement
```

That said, I will try to review the updated PR later tonight, apologies for the delayed response.

2024-10-01 14:24 UTC, wandmagic commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Incomplete controls: {count(//implemented-requirement)} required: {count($all-imports//control)}</message>
Added a constraint 

> I see two scenarios for **incomplete-implemented-requirements**:
> 
> 1. **no missing controls** - here, we'd want to confirm that all f the controls are accounted for, regardless of status.  In the early  stages (pre-authorization) when CSOs are designated as "FedRAMP Ready" or "FedRAMP In Process", many if not most of the controls will not be fully implemented yet.  If CSPs send preliminary versions of their SSPs to FedRAMP during these early stages, FedRAMP should ensure the CSP is at least accounting for all controls in the baseline.  IMO, missing control should be an ERROR level constraint.
> 2. **all controls are implemented** - My understanding is that all baseline controls should be "implemented" before being authorized, but there are exceptions though.  For example, during the transition from the rev 4 to rev 5 baselines, FedRAMP requested updated SSPs, with the understanding that some of the new controls would be "partially implemented" or "planned", and CSPs were given a timeframe for eventually implementing all controls. For that reason, I think might be a WARNING level constraint.

updated the PR to match this design, i agree i feel like this is a good approach

2024-10-24 16:48 UTC, wandmagic commented
@aj-stein-gsa  this is ready for review again, i've moved to an index-has key approach

2024-10-24 17:22 UTC, DimitriZhurkin submitted a review, later dismissed
Looks good to me; super job!

I also learned something new: how you can pull in XML inside `<message>` elements. In the past, I tried `<xsl:value-of>` inside `<message>`, but that didn't work. :-)

2024-10-24 18:37 UTC, kyhu65867 reviewed
Minor non-blocking

2024-10-25 08:15 UTC, wandmagic commented on features/steps/fedramp_extensions_steps.ts
> +      sarifMessages = constraintResults.map(x=>x.message.text)
added comments

2024-10-25 08:15 UTC, wandmagic commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Implemented requirement (Control ID: {@control-id}) must have at least one by-component reference to the source component implementing it found ({count(./by-component)}).</me
fixed see latest

2024-10-25 13:25 UTC, aj-stein-gsa reviewed
These are all minor things, I am testing it locally now to kick the tires. So far, I can say: excellent work!

2024-10-25 13:25 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <description>A FedRAMP SSP must contain an implemented requirement for each imported control</description>
Minor but I didn't even think about this for description and I know `message` does not exist for `index-has-key`, but maybe do BCP14 caps anyway.

```suggestion
                <description>A FedRAMP SSP MUST contain an implemented requirement for each imported control.</description>
```

2024-10-25 13:25 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <formal-name>Implemented Controls</formal-name>
Minor: since the ID makes it clear to me what we're doing but the formal name a little less so, can we make a minor improvement there?

```suggestion
                <formal-name>Additional Controls Implemented Not in Baseline</formal-name>
```
```suggestion
            <index-has-key id='additional-implemented-requirements' target="//implemented-requirement" name="index-imported-controls" level="WARNING">
                <formal-name>Additional Controls Implemented Not in Baseline</formal-name>
```

2024-10-25 13:41 UTC, aj-stein-gsa reviewed
I think the work is really good and the approach is definitely the right way because you can do it very efficiently, but I think the `index|index-has-key` messages we cannot customize will be very confusing to downstream customers based on the output.

We should probably discuss this. You did great, but I think it may be time to request `message` for `index|index-has-key` and park this for now. We should discuss during standup maybe?

Some examples for the group because I am not sure how obvious it is if they did not run the CLI outside of tests and look at output or inspect the SARIF.

```sh
% oscal-cli validate '/home/me/Code/fedramp-automation/src/validations/constraints/content/ssp-incomplete-required-controls-implemented-INVALID.xml' -c /home/me/Code/fedramp-automation/src/validations/constraints/fedramp-external-allowed-values.xml -c /home/me/Code/fedramp-automation/src/validations/constraints/fedramp-external-constraints.xml -c /home/me/Code/fedramp-automation/src/validations/constraints/oscal-external-constraints.xml --disable-schema-validation
Loading 'file:/home/me/Code/fedramp-automation/src/validations/constraints/fedramp-external-allowed-values.xml'
Loading 'file:/home/me/Code/fedramp-automation/src/validations/constraints/fedramp-external-constraints.xml'
Loading 'file:/home/me/Code/fedramp-automation/src/validations/constraints/oscal-external-constraints.xml'
Validating 'file:/home/me/Code/fedramp-automation/src/validations/constraints/content/ssp-incomplete-required-controls-implemented-INVALID.xml' as XML.
Validation identified the following issues:
[WARNING] [/catalog/group[1]/control[1]] Key reference [ac-1] not found in index 'index-implemented-requirements' for item at path '/catalog/group[1]/control[1]'
[WARNING] [/catalog/group[2]/control[1]] Key reference [cm-8] not found in index 'index-implemented-requirements' for item at path '/catalog/group[2]/control[1]'
[WARNING] [/catalog/group[3]/control[1]] Key reference [pe-2] not found in index 'index-implemented-requirements' for item at path '/catalog/group[3]/control[1]'
The file 'file:/home/me/Code/fedramp-automation/src/validations/constraints/content/ssp-incomplete-required-controls-implemented-INVALID.xml' is valid.
% oscal-cli validate '/home/me/Code/fedramp-automation/src/validations/constraints/content/ssp-extraneous-implemented-requirements-INVALID.xml' -c /home/me/Code/fedramp-automation/src/validations/constraints/fedramp-external-allowed-values.xml -c /home/me/Code/fedramp-automation/src/validations/constraints/fedramp-external-constraints.xml -c /home/me/Code/fedramp-automation/src/validations/constraints/oscal-external-constraints.xml --disable-schema-validation
Loading 'file:/home/me/Code/fedramp-automation/src/validations/constraints/fedramp-external-allowed-values.xml'
Loading 'file:/home/me/Code/fedramp-automation/src/validations/constraints/fedramp-external-constraints.xml'
Loading 'file:/home/me/Code/fedramp-automation/src/validations/constraints/oscal-external-constraints.xml'
Validating 'file:/home/me/Code/fedramp-automation/src/validations/constraints/content/ssp-extraneous-implemented-requirements-INVALID.xml' as XML.
Validation identified the following issues:
[ERROR] [/system-security-plan/control-implementation[1]/implemented-requirement[1]] Implemented requirement (Control ID: ac-1) must have at least one by-component reference to the source component implementing it. Found (0).
[ERROR] [/system-security-plan/control-implementation[1]/implemented-requirement[1]] The cardinality '0' is below the required minimum '1' for items matching './/by-component'.
[WARNING] [/system-security-plan/control-implementation[1]/implemented-requirement[1]] Key reference [ac-1] not found in index 'index-imported-controls' for item at path '/system-security-plan/control-implementation[1]/implemented-requirement[1]'
The file 'file:/home/me/Code/fedramp-automation/src/validations/constraints/content/ssp-extraneous-implemented-r
```

2024-10-25 14:54 UTC, DimitriZhurkin submitted a review, later dismissed

2024-10-25 14:56 UTC, Rene2mt requested changes
This is great.  A few questions and minor suggestions.

2024-10-25 14:56 UTC, Rene2mt commented on src/validations/constraints/content/ssp-all-VALID.xml
> +      </by-component>
I think we are requiring `by-component` to be inside of `statement` and not directly inside `implementd-requirement`.  @aj-stein-gsa and @brian-ruf is that right?

2024-10-25 14:56 UTC, Rene2mt commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <index-has-key id='incomplete-implemented-requirements' target="$imported-controls-map" name="index-implemented-requirements" level="WARNING">
@aj-stein-gsa and @brian-ruf, non-blocking but I wonder if this should be **ERROR** instead of **WARNING**? Ideally, the `implemented-requirement` should have all of the controls specified in the baseline, and if a control is not implemented, the SSP author indicates that via status rather than omitting the control.

2024-10-25 14:56 UTC, Rene2mt commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <description>A FedRAMP SSP must contain an imported control for each implemented-requirement</description>
Maybe something like 

```suggestion
                <description>This SSP includes extraneous controls that are not part of the FedRAMP baseline.</description>
```

2024-10-25 18:25 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <index-has-key id='incomplete-implemented-requirements' target="$imported-controls-map" name="index-implemented-requirements" level="WARNING">
I actually was wondering but I swore this topic came up and I am not sure why others (maybe me?) recommended to Paul it be WARNING, I have to review earlier the PR history. That said, I would agree this is more significant than a warning.

2024-10-25 18:27 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <description>A FedRAMP SSP must contain an imported control for each implemented-requirement</description>
Well if it is a positive requirement as a warning, should it be about probably not having them?

```suggestion
                <description>A FedRAMP SSP SHOULD NOT contain implemented requirements not in the FedRAMP baseline, but MAY have them under certain circumstances.</description>
```

2024-10-25 18:38 UTC, wandmagic commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <index-has-key id='incomplete-implemented-requirements' target="$imported-controls-map" name="index-implemented-requirements" level="WARNING">
I've made them ERROR, i feel the same way, we should reject SSP's that do not have full coverage

2024-10-25 18:47 UTC, wandmagic commented on src/validations/constraints/content/ssp-all-VALID.xml
> +      </by-component>
ok i've moved it inside the statement

2024-10-28 18:20 UTC, wandmagic commented on src/validations/constraints/fedramp-external-constraints.xml
> +                    </p>
fixed

2024-10-30 12:47 UTC, aj-stein-gsa commented
@wandmagic you want a re-review? What's going on with the profile resolution?

2024-10-30 15:08 UTC, aj-stein-gsa commented
Per standup today, I forgot this issue is blocked for _final_ review until we get metaschema-java adjustments with `message` for `index` and `index-has-key`. Changing status to Blocked.

2024-10-30 15:20 UTC, wandmagic commented
> @wandmagic you want a re-review? What's going on with the profile resolution?

An error occurred while evaluating the expression 'resolve-profile(doc(resolve-uri(import-profile/@href)))//catalog'.

for the invalid profiles, metaschema crashes because it can't process this metapath

2024-10-30 15:33 UTC, aj-stein-gsa commented
> > @wandmagic you want a re-review? What's going on with the profile resolution?
> 
> An error occurred while evaluating the expression 'resolve-profile(doc(resolve-uri(import-profile/@href)))//catalog'.
> 
> for the invalid profiles, metaschema crashes because it can't process this metapath

Thanks for the update. I happen to know this behavior is not desirable, and this work caught a bug-feature-why-not-both fix-hancement in m-j. I am not sure https://github.com/metaschema-framework/metaschema-java/issues/208 fixes it, but we _may_ want to wrap a `doc-available()` before calling the `resolve-profile()`, that's what 208 actually fixes to be less noisy and just say `false()` I hope that makes sense and will leave a placeholder for review when we come back with 2.2.0 of m-j released.

2024-10-30 15:36 UTC, aj-stein-gsa commented on src/validations/constraints/oscal-external-constraints.xml
> +            <let var="all-imports" expression="recurse-depth('resolve-profile(doc(resolve-uri(import-profile/@href)))//catalog')"/>
I will recommend when the dependency on a metaschema-java becomes unblocked we consider wrapping at least the the top-level `import-profile/@href` with a `doc-available()` check, but we need a m-j release with https://github.com/metaschema-framework/metaschema-java/issues/208 merged and released first.

Something like:

```suggestion
            <let var="all-imports" expression="if doc-available(import-profile/@href) then recurse-depth('resolve-profile(doc(resolve-uri(import-profile/@href)))//catalog') else ()"/>
```

2024-10-30 20:36 UTC, wandmagic commented
i'll re open when the issues are resolved

2024-10-30 20:36 UTC, closed without merging

2024-10-31 11:36 UTC, wandmagic commented on src/validations/constraints/oscal-external-constraints.xml
> +            <let var="all-imports" expression="recurse-depth('resolve-profile(doc(resolve-uri(import-profile/@href)))//catalog')"/>
unfortune, but this change does not fix the issue

2024-10-31 12:46 UTC, aj-stein-gsa commented on src/validations/constraints/oscal-external-constraints.xml
> +            <let var="all-imports" expression="recurse-depth('resolve-profile(doc(resolve-uri(import-profile/@href)))//catalog')"/>
How so that it still throws the inner exception or some other way?

2024-10-31 15:43 UTC, DimitriZhurkin commented on src/validations/constraints/oscal-external-constraints.xml
> +            <let var="all-imports" expression="recurse-depth('resolve-profile(doc(resolve-uri(import-profile/@href)))//catalog')"/>
Would removing the `if` statement make it easier? Something like this:
`recurse-depth('resolve-profile(doc(resolve-uri(import-profile/@href)))//catalog') => doc-available(import-profile/@href)`

Just a thought, ya know.

2024-10-31 17:29 UTC, wandmagic commented on src/validations/constraints/oscal-external-constraints.xml
> +            <let var="all-imports" expression="recurse-depth('resolve-profile(doc(resolve-uri(import-profile/@href)))//catalog')"/>
this also does not resolve the issue

2024-10-31 17:31 UTC, wandmagic commented on src/validations/constraints/oscal-external-constraints.xml
> +            <let var="all-imports" expression="recurse-depth('resolve-profile(doc(resolve-uri(import-profile/@href)))//catalog')"/>
> How so that it still throws the inner exception or some other way?

the constraint no longer works with the if statement

2024-10-31 17:33 UTC, wandmagic commented on src/validations/constraints/oscal-external-constraints.xml
> +            <let var="all-imports" expression="recurse-depth('resolve-profile(doc(resolve-uri(import-profile/@href)))//catalog')"/>
> Would removing the `if` statement make it easier? Something like this: `recurse-depth('resolve-profile(doc(resolve-uri(import-profile/@href)))//catalog') => doc-available(import-profile/@href)`
> 
> Just a thought, ya know.


An error occurred while evaluating the expression 'recurse-depth('resolve-profile(doc(resolve-uri(import-profile/@href)))//catalog') => doc-available(import-profile/@href)'.

2024-10-31 17:44 UTC, aj-stein-gsa commented on src/validations/constraints/oscal-external-constraints.xml
> +            <let var="all-imports" expression="recurse-depth('resolve-profile(doc(resolve-uri(import-profile/@href)))//catalog')"/>
Not surprising, can you paste the error in a code block or somewhere in chat when you have a chance? Thanks. If you will do it outside the comments here, feel free to resolve this comment. I know the PR has been closed for a bit.

2024-10-31 18:22 UTC, DimitriZhurkin commented on src/validations/constraints/oscal-external-constraints.xml
> +            <let var="all-imports" expression="recurse-depth('resolve-profile(doc(resolve-uri(import-profile/@href)))//catalog')"/>
Wonder if adding the `mp:` namespace to `resolve-profile` would make any difference, since it's a Metapath function:
```
mp:resolve-profile
```
Again, just a thought.