Add `system-characteristics` `has-cloud-model` constraints
GSA/fedramp-automation pull request #737
Opened 2024-09-27 12:11 UTC by Gabeblis

# Committer Notes
### Description
Added `system-characteristics` `has-cloud-model` constraints and tests for each of the constraints. These should be added as they are part of the effort write all of the constraints from the constraint tracker.

### Changes
- Added constraints has-cloud-service-model, has-cloud-service-model-remarks, has-cloud-deployment-model, has-cloud-deployment-model-remarks, and has-public-cloud-deployment-model to fedramp-external-constraints.xml.
- Added pass and fail yaml tests for all of the above constraints.
- Edited `ssp-all-VALID.xml` to ensure all constraints pass correctly.
- Added `-INVALID.xml` file for each constraint.
### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
~~- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?~~
~~- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?~~

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-09-27 17:15 UTC, aj-stein-gsa reviewed
I want to approve this, but even if simple and straightforward, we seem to have some drift from internal staff guidance made public and the wording in the published docs is not clear about remarks _to me_. Double checking some things internally before approving.

This work is still very good: short, sweet, and to the point. Thanks for your patience and understanding, @Gabeblis!

2024-09-27 17:15 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>A FedRAMP SSP with a cloud service model of "other" must supply remarks.</message>
Minor comment, why remarks? I would like to ask the reviewers to clarify this guidance from the current word docs to align our site and this very good basis, it just doesn't explain what remarks, you know, should actually say.

```suggestion
                <message>A FedRAMP SSP with a cloud service model of "other" must supply remarks to ...</message>
```

2024-09-27 17:15 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="has-cloud-service-model-remarks" target="system-characteristics" test="every $p in prop[@name eq 'cloud-service-model' and @value eq 'other'] satisfies exists($p/remarks)" lev
Blocking: I don't expect you to have easily caught this and it seems the official guidance outside our little code universe has tightened or changed since my previous tenure here, I do not see the official SSP templates (pre-OSCAL, see the public link) mention other at all as an option anymore with the move to Rev 5.

I would like to double check with review staff internally before moving this forward. If we _should_ move this forward, we should make sure other is also explained [in our website docs](https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#deployment-model). We only mention hybrid, not other. More to follow.

2024-09-27 18:55 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="has-cloud-service-model-remarks" target="system-characteristics" test="every $p in prop[@name eq 'cloud-service-model' and @value eq 'other'] satisfies exists($p/remarks)" lev
Sorry re our chat conversation, I think we need more thorough docs about the inventory of relevant info and hierarchy. If ambiguous, I would go in this order. If the highest one doesn't have a clear answer, go down the list:

1. Our automate.fedramp.gov docs. 
1. The [legacy docs for Rev 5 in our repo](https://github.com/GSA/fedramp-automation/tree/fedramp-2.0.0-oscal-1.0.4/documents/rev5).
1. The [legacy docs for Rev 4 in our repo](https://github.com/GSA/fedramp-automation/tree/fedramp-2.0.0-oscal-1.0.4/documents/rev4).
1. [https://www.fedramp.gov/assets/resources/templates/FedRAMP-High-Moderate-Low-LI-SaaS-Baseline-System-Security-Plan-(SSP).docx](https://www.fedramp.gov/assets/resources/templates/FedRAMP-High-Moderate-Low-LI-SaaS-Baseline-System-Security-Plan-%28SSP%29.docx)
1. https://www.fedramp.gov/assets/resources/templates/SSP-Appendix-A-High-FedRAMP-Security-Controls.docx

2024-09-27 18:56 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="has-cloud-service-model-remarks" target="system-characteristics" test="every $p in prop[@name eq 'cloud-service-model' and @value eq 'other'] satisfies exists($p/remarks)" lev
> Sorry re our chat conversation, I think we need more thorough docs about the inventory of relevant info and hierarchy. If ambiguous, I would go in this order. If the highest one doesn't have a clear answer, go down the list:
> 
> 1. Our automate.fedramp.gov docs.
> 2. The [legacy docs for Rev 5 in our repo](https://github.com/GSA/fedramp-automation/tree/fedramp-2.0.0-oscal-1.0.4/documents/rev5).
> 3. The [legacy docs for Rev 4 in our repo](https://github.com/GSA/fedramp-automation/tree/fedramp-2.0.0-oscal-1.0.4/documents/rev4).
> 4. [https://www.fedramp.gov/assets/resources/templates/FedRAMP-High-Moderate-Low-LI-SaaS-Baseline-System-Security-Plan-(SSP).docx](https://www.fedramp.gov/assets/resources/templates/FedRAMP-High-Moderate-Low-LI-SaaS-Baseline-System-Security-Plan-%28SSP%29.docx)
> 5. https://www.fedramp.gov/assets/resources/templates/SSP-Appendix-A-High-FedRAMP-Security-Controls.docx

You're awesome. Thank you sir.

2024-10-30 14:48 UTC, Rene2mt requested changes
PR looks good and the constraints run fine, but I have a few requested changes to the test content.

2024-10-30 14:48 UTC, Rene2mt commented on src/validations/constraints/content/ssp-all-VALID.xml
> +    <prop name='cloud-deployment-model' value='hybrid-cloud' ns="https://fedramp.gov/ns/oscal">
I think in cases where we are applying a constraint to a core OSCAL `prop`, we don't need to add the FedRAMP namespace.

```suggestion
    <prop name='cloud-deployment-model' value='hybrid-cloud'>
```

2024-10-30 14:48 UTC, Rene2mt commented on src/validations/constraints/content/ssp-all-VALID.xml
> +    <prop name='cloud-service-model' value='other' ns="https://fedramp.gov/ns/oscal">
I think in cases where we are applying a constraint to a core OSCAL prop, we don't need to add the FedRAMP namespace.

```suggestion
    <prop name='cloud-service-model' value='other'>
```

2024-10-30 18:01 UTC, Gabeblis commented on src/validations/constraints/content/ssp-all-VALID.xml
> +    <prop name='cloud-deployment-model' value='hybrid-cloud' ns="https://fedramp.gov/ns/oscal">
Thank you for the feedback. Resolved: 
9f0bb37

2024-10-30 18:01 UTC, Gabeblis commented on src/validations/constraints/content/ssp-all-VALID.xml
> +    <prop name='cloud-service-model' value='other' ns="https://fedramp.gov/ns/oscal">
Resolved: 9f0bb37

2024-10-30 18:01 UTC, Gabeblis commented on src/validations/constraints/content/ssp-has-cloud-deployment-model-INVALID.xml
> +    <prop name="cloud-service-model" value="other" ns="https://fedramp.gov/ns/oscal">
Resolved: 9f0bb37

2024-10-30 18:01 UTC, Gabeblis commented on src/validations/constraints/content/ssp-has-cloud-deployment-model-remarks-INVALID.xml
> +    <prop name="cloud-deployment-model" value="hybrid-cloud" ns="https://fedramp.gov/ns/oscal"/>
Resolved: 9f0bb37

2024-10-30 18:01 UTC, Gabeblis commented on src/validations/constraints/content/ssp-has-public-cloud-deployment-model-INVALID.xml
> +    <prop name='cloud-deployment-model' value='government-only-cloud' ns="https://fedramp.gov/ns/oscal">
Resolved: 9f0bb37

2024-10-30 18:26 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="has-cloud-service-model-remarks" target="system-characteristics" test="every $p in prop[@name eq 'cloud-service-model' and @value eq 'other'] satisfies exists($p/remarks)" lev
Thanks for taking the time to reach out for a call. I will follow up with @david-waltermire and crew about the multiple prop approach in the upstream remarks and clarify when I can this afternoon.

I will be in touch!

2024-10-30 18:27 UTC, Gabeblis commented on src/validations/constraints/content/ssp-all-VALID.xml
> +    <prop name='cloud-deployment-model' value='hybrid-cloud' ns="https://fedramp.gov/ns/oscal">
@Rene2mt I had to undo this change. Our allowed values currently grab the props by the namespace. If you want to remove these, we'd have to adjust the `allowed-values` constraint for `deployment-model` as well.
```xml 
<allowed-values id="deployment-model" target="system-characteristics/prop[@name='cloud-deployment-model'][@ns='https://fedramp.gov/ns/oscal']/@value" allow-other="no" level="ERROR">
    <formal-name>Deployment Model</formal-name>
    <description>The cloud deployment model.</description>
    <enum value="public-cloud">Public Cloud</enum>
    <enum value="private-cloud">Private Cloud</enum>
    <enum value="government-only-cloud">U.S. Government Only</enum>
    <enum value="hybrid-cloud">Hybrid</enum>
    <enum value="other">Other</enum>
</allowed-values>
```

2024-10-30 18:32 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>A FedRAMP SSP with a cloud service model of "other" must supply remarks.</message>
Resolved: e83309f

2024-10-30 18:50 UTC, Rene2mt commented on src/validations/constraints/content/ssp-all-VALID.xml
> +    <prop name='cloud-deployment-model' value='hybrid-cloud' ns="https://fedramp.gov/ns/oscal">
Hmmm...my understanding is that FedRAMP namespaces are used where we have a FedRAMP specific `prop` that is not already defined in core OSCAL or where we need to extend an existing core OSCAL `prop` without collision (e.g., we wanted "cloud-deployment-model" to include values that are not part of defined set in core OSCAL).  

In this case, the values FedRAMP allows are a subset of the defined core OSCAL values for the "cloud-deployment-model" `prop`  (see https://github.com/usnistgov/OSCAL/blob/4f02dac6f698efda387cc5f55bc99581eaf494b6/src/metaschema/oscal_ssp_metaschema.xml#L152-L167) so I think the FedRAMP `allowed-values` constraint might need to be updated as well.  Let me get confirmation.

2024-10-30 19:12 UTC, brian-ruf commented on src/validations/constraints/content/ssp-all-VALID.xml
> +    <prop name='cloud-deployment-model' value='hybrid-cloud' ns="https://fedramp.gov/ns/oscal">
I mostly agree with this. One caveat is that if the NIST OSCAL prop's `allowed-values` constraint includes `allow-other="yes"`, we do not need to use our own prop simply to add values.

If the NIST OSCAL prop's `allowed-values` constraint does **not** include `allow-other="yes"` (or it is explicitly set to "no"), we **do** need to use our own prop if we require values that are not defined by NIST. 

In the 2nd instance, we must include **all** acceptable values, including those previously defined by NIST as they are not inherited from the original NIST prop. In fact, all applicable constraints must be re-defined for the FedRAMP extension.

2024-10-30 19:35 UTC, Rene2mt commented on src/validations/constraints/content/ssp-all-VALID.xml
> +    <prop name='cloud-deployment-model' value='hybrid-cloud' ns="https://fedramp.gov/ns/oscal">
Ok,  @Gabeblis  as you noted, I think we need to need to adjust the "cloud-deployment-model" allowed-value constraint, removing the namespace as follows:

```xml
<allowed-values id="deployment-model" target="system-characteristics/prop[@name='cloud-deployment-model']/@value" allow-other="no" level="ERROR">
    <formal-name>Deployment Model</formal-name>
    <description>The cloud deployment model.</description>
    <enum value="public-cloud">Public Cloud</enum>
    <enum value="private-cloud">Private Cloud</enum>
    <enum value="government-only-cloud">U.S. Government Only</enum>
    <enum value="hybrid-cloud">Hybrid</enum>
    <enum value="other">Other</enum>
</allowed-values>
```

Do you want to make that change with this PR or work should we create a separate issue?

2024-10-30 19:45 UTC, Gabeblis commented on src/validations/constraints/content/ssp-all-VALID.xml
> +    <prop name='cloud-deployment-model' value='hybrid-cloud' ns="https://fedramp.gov/ns/oscal">
Ok, I think it is a simple change that can be included and documented within this PR.

2024-10-30 22:17 UTC, aj-stein-gsa requested changes
Sorry, I assure you, last one from me and I will urge the team to quickly review and approve tomorrow.

2024-10-30 22:17 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            </expect>
Blocking: We cannot really enforce that because components and inventory items for a service may have private elements that we in FedRAMP review as part of the authorization process. I truly apologize for missing this earlier if I reviewed too hastily.

```suggestion
```

2024-10-30 22:17 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="has-cloud-service-model-remarks" target="system-characteristics" test="every $p in prop[@name eq 'cloud-service-model' and @value eq 'other'] satisfies exists($p/remarks)" lev
I am going to close this as obsolete in advance of another review.

2024-10-30 22:17 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            </expect>
Blocking: I got some updates from @david-waltermire and @Rene2mt from discussion that we ought to precisely follow OSCAL guidance on this one. NIST and FR, in SP 800-45 and other documents separate of OSCAL do encode the ability of having two or more classifications meaning hybird, not expressly having one called `"hybrid-cloud"`. We can create an upstream issue in usnistgov/OSCAL and ask them to review it entirely, but for now we should go for the following.

- Allow one prop public, private, community-cloud, goverment-only-cloud, or other as acceptable
- Allow two or more props to mean hybird-cloud.
- Do now allow hybrid-cloud to mean hybrid, edit message and remarks to be explicit (without deriving a custom `@ns`-scoped allowed-values enumeration set.

```suggestion
            <expect id="has-cloud-deployment-model-remarks" target="system-characteristics" test="every $p in (prop[@name eq 'cloud-deployment-model' and @value eq 'other'] or count(prop[@name eq 'cloud-deployment-model') > 1)satisfies exists($p/remarks)" level="ERROR">
                <message>A FedRAMP SSP with a cloud deployment model MUST use supply remarks to its deployment model when it is not community-cloud, government-only-cloud, other, public-cloud, or private-cloud.</message>
                <remarks>FedRAMP prefers precise classification over generic classification, so no hybrid...</remarks>
            </expect>
```

2024-10-30 22:17 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            </expect>
I guessed on the `@test` but I can play with it locally and see how it behaves shortly, but this explanation and comment is the full detail of how it ought to work.

2024-11-01 20:44 UTC, aj-stein-gsa commented
@Gabeblis are we at a point we can touch this up and get it back in the review and close out for the week (or Monday latest 🤞)?

2024-11-01 20:46 UTC, Gabeblis commented
> @Gabeblis are we at a point we can touch this up and get it back in the review and close out for the week (or Monday latest 🤞)?

Wow I did not see any of this. I have to step out here in a little, but I'll address all these changes later in the evening 👍

2024-11-04 13:20 UTC, Gabeblis commented on src/validations/constraints/content/ssp-all-VALID.xml
> +    <prop name='cloud-deployment-model' value='hybrid-cloud' ns="https://fedramp.gov/ns/oscal">
Resolved: [2f7bcc0](https://github.com/GSA/fedramp-automation/pull/737/commits/2f7bcc0dc52fcbf4bea73ed05ca65b2f68d2182e) for namespace removal and [7600157](https://github.com/GSA/fedramp-automation/pull/737/commits/760015700ceb0c738e679f712f5ba5533ea61556) for change to "public".

2024-11-04 13:21 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +            </expect>
Thank you for catching that. Resolved: [7600157](https://github.com/GSA/fedramp-automation/pull/737/commits/760015700ceb0c738e679f712f5ba5533ea61556)

2024-11-04 13:27 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +            </expect>
I believe I addressed all feedback. I saw something conflicting here in your suggestion where the test checks if the `@value` is `other` then it has remarks. Then the `message` says it doesn't need remarks if the `value` is `other`. I assumed that we only need remarks if there is more than one deployment model, so that is what I implemented. Please take a look when you get a chance @aj-stein-gsa and let me know if this aligns with what you were suggesting.

2024-11-04 13:40 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            </expect>
> I saw something conflicting here in your suggestion where the test checks if the `@value` is `other` then it has remarks.

Sorry I was unclear, I was just being my normally confusing self. 😆

If you the instance has a `@value` of `"other"`, please require `remarks`.

2024-11-04 14:42 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +            </expect>
No worries. I added that condition here: [520d794](https://github.com/GSA/fedramp-automation/pull/737/commits/520d79454d1392d77e726bc9a96620dde2b6e861)

2024-11-04 19:50 UTC, aj-stein-gsa approved these changes

2024-11-04 22:08 UTC, Rene2mt approved these changes

2024-11-06 19:47 UTC, wandmagic approved these changes

2024-11-07 14:12 UTC, aj-stein-gsa commented
Given approvals, I will rebase and clean up merge conflicts in allowed-values minor tweaks and merge.

2024-11-07 14:15 UTC, merged