hotfix constraint script for windows
GSA/fedramp-automation pull request #740
Opened 2024-09-28 14:11 UTC by wandmagic

# Committer Notes

After switching the run environment of the dev-constraint script we neglected to update our method of finding the constraint directory path for windows.

this adds a github action to assure that the test script runs correctly in windows and linux

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-09-28 14:17 UTC, wandmagic commented
if we don't want the github action let me know, just want to make sure i didn't break linux support as I fixed this on my windows box

2024-09-30 12:19 UTC, aj-stein-gsa requested changes

2024-09-30 12:19 UTC, aj-stein-gsa commented on .github/workflows/test-scripts.yml
> +        uses: actions/setup-java@v3
Blocking: Can you pin the dependency to the full commit hash ID and not tags? Thanks.

```suggestion
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73
```

2024-09-30 12:19 UTC, aj-stein-gsa commented on .github/workflows/test-scripts.yml
> +        uses: actions/checkout@v3
Blocking: can you use commit hash ID and not the tags?

```suggestion
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
```

2024-09-30 12:19 UTC, aj-stein-gsa commented on .github/workflows/test-scripts.yml
> +          distribution: 'adopt'
Blocking: Can you follow the JDK maintainer (`temurin`) and the specific version to align with upstream build requirements?

https://github.com/metaschema-framework/metaschema-java/blob/874ad2d8d561f9c481208bdf389788313bda343a/.github/workflows/build.yml#L31

2024-09-30 12:21 UTC, aj-stein-gsa commented
> if we don't want the github action let me know, just want to make sure i didn't break linux support as I fixed this on my windows box

I am fine with that. Sorry for minor nits, I am fine with the action to test across platforms and everything else looks great.

2024-09-30 13:16 UTC, wandmagic commented on .github/workflows/test-scripts.yml
> +        uses: actions/setup-java@v3
updated

2024-09-30 13:17 UTC, aj-stein-gsa approved these changes

2024-09-30 13:44 UTC, aj-stein-gsa commented on features/fedramp_extensions.feature
> -  | has-authorization-boundary-diagram-FAIL.yaml |
General comment on this file, not just this diff: why are we changing the test inventory in the feature file again? Is it just sorting, because the sorting doesn't seem alphabetical now, was this just to kick the test tires?

2024-09-30 13:52 UTC, wandmagic commented on features/fedramp_extensions.feature
> -  | has-authorization-boundary-diagram-FAIL.yaml |
when you run npm run test this file re-generates with the latest of what is in the directory, there is a chance behaviour here is different sorting between linux and windows

2024-09-30 13:59 UTC, wandmagic commented on features/fedramp_extensions.feature
> -  | has-authorization-boundary-diagram-FAIL.yaml |
we could add a .sort() file in the npm run test command to keep this the same between platforms

2024-09-30 14:05 UTC, aj-stein-gsa approved these changes

2024-09-30 14:17 UTC, merged