has sensitivity-level constraint
GSA/fedramp-automation pull request #742
Opened 2024-10-01 10:53 UTC by wandmagic

# Committer Notes

Introducing a small constraint to assure the SSP has a sensitivity level 

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-10-01 12:44 UTC, aj-stein-gsa requested changes
Things are looking good, but I thought we decided to slim down the negative test fixture data per ADR 6?

2024-10-01 12:44 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-has-security-sensitivity-level-INVALID.xml
> +</system-security-plan>
Blocking feedback: per [ADR 6](https://github.com/GSA/fedramp-automation/blob/73aa345737d03fa49dcb0485481c5778038d4d36/documents/adr/0006-testing-harness-approach.md], can we slim this down now?

```suggestion
<system-security-plan xmlns="http://csrc.nist.gov/ns/oscal/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://csrc.nist.gov/ns/oscal/1.0 https://github.com/usnistgov/OSCAL/releases/download/v1.1.2/oscal_ssp_schema.xsd" uuid="12345678-1234-4321-8765-123456789012">
  <system-characteristics>
    <!-- There is no security-sensitivity-level this will intentionally fail a constraint. -->
    <!-- security-sensitivity-level>does-not-exist</security-sensitivity-level> -->
  <system-characteristics>
</system-security-plan>
```

2024-10-01 13:32 UTC, wandmagic commented
slimmed

2024-10-01 13:47 UTC, aj-stein-gsa approved these changes
This looks good. I need to wrap documentation for the PR connected to https://github.com/GSA/automate.fedramp.gov/issues/55 and close that for this to be ready. If it is not complete at the end of the day.

2024-10-29 15:10 UTC, aj-stein-gsa commented
We need to rebase this PR but the related documentation branch is settling, we should be good to go soon. Let's wrap up review hopefully today or early tomorrow, @wandmagic.

2024-10-30 14:14 UTC, Rene2mt approved these changes

2024-10-30 20:20 UTC, closed without merging