introduce user constraints
GSA/fedramp-automation pull request #743
Opened 2024-10-01 11:34 UTC by wandmagic

# Committer Notes

Introduce constraints on the user object
### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-10-03 17:37 UTC, aj-stein-gsa commented
I wil review this, but you do want me as assignee, but a review (I am in the fedramp-admins groups FYI). I am just always in a state of being perpetually behind! 😆

2024-10-03 23:35 UTC, Rene2mt submitted a review, later dismissed
@wandmagic should these constraints be updated w/ help-text and help-urls per [ADR 9](https://github.com/GSA/fedramp-automation/blob/8301e380c88532ebbb22aca55521701750eb0b83/documents/adr/0009-constraint-based-help-docs.md)?

2024-10-04 13:33 UTC, wandmagic commented
> @wandmagic should these constraints be updated w/ help-text and help-urls per [ADR 9](https://github.com/GSA/fedramp-automation/blob/8301e380c88532ebbb22aca55521701750eb0b83/documents/adr/0009-constraint-based-help-docs.md)?

Added help props and improved messages to include violating UUID

kindly let me know if the URI's i've chosen are appropriate

2024-10-04 13:54 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-markdown" value="# User Type Requirement\n\nEach user must have exactly one type property.\n\nThis is essen
For now, can we just keep the `help-url` and not include others, this is what I had hinted with in the ADR. In the ADR, the only difference is I showed all possible props.

```suggestion
```

2024-10-04 13:55 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-markdown" value="# User Type Requirement\n\nEach user must have exactly one type property.\n\nThis is essen
Wait nevermind, I meant to do a review.

2024-10-04 13:56 UTC, aj-stein-gsa reviewed
Looks good so far, just asking to use the URLs for now. `help-text` and `help-markdown` can come later.

2024-10-04 13:56 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-markdown" value="# Privilege Level Requirement\n\nEach user must have exactly one privilege level property.
For now, can we just keep the `help-url` and not include others, this is what I had hinted with in the ADR. In the ADR, the only difference is I showed all possible props.

```suggestion
```

2024-10-04 15:37 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-markdown" value="# Privilege Level Requirement\n\nEach user must have exactly one privilege level property.
> For now, can we just keep the `help-url` and not include others, this is what I had hinted with in the ADR. In the ADR, the only difference is I showed all possible props.

Just out of curiosity @aj-stein-gsa, what is the reason you don't want `help-text` or `help-markdown` just yet? Is it related to the style guide?

2024-10-04 17:41 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-markdown" value="# Privilege Level Requirement\n\nEach user must have exactly one privilege level property.
Sorry if that wasn't super clear, I think we could add those if we prefer over-time, but I assume inlining all of the documentation _as a default_ will balloon the size of constraint files for processing and I thought that was one of the implications of progressive enhancement from URL to full inline content for airgapped environments per this part of the ADR.

https://github.com/GSA/fedramp-automation/blob/6db699c2aa9b949ba0edfbbd14ad5d50b20ee64d/documents/adr/0009-constraint-based-help-docs.md?plain=1#L67

This is why I explained we use Option 4, not Option 3, as a decision because that would would mandate all of them. I think we should be open to adding them, but not mandating all of them gives that flexibility. Does that make sense?

I perhaps should have been more clear with separate Option 3 and Option 4 examples.

2024-10-04 17:45 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-markdown" value="# Privilege Level Requirement\n\nEach user must have exactly one privilege level property.
That makes perfect sense. Thanks for the clarification 🫡

2024-10-04 18:03 UTC, wandmagic commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-markdown" value="# Privilege Level Requirement\n\nEach user must have exactly one privilege level property.
Right on I've made a PR so that we can enforce help URI as a requirement
https://github.com/GSA/fedramp-automation/pull/759

2024-10-04 18:04 UTC, wandmagic commented
> Looks good so far, just asking to use the URLs for now. `help-text` and `help-markdown` can come later.

ok should be in there now

2024-10-21 17:44 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +<metaschema-meta-constraints xmlns="http://csrc.nist.gov/ns/oscal/metaschema/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://csrc.nist.gov/ns/oscal/metaschema/1.
Paul, I might've missed it, what are these additional `xsi` schemas for?

2024-10-21 18:47 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +<metaschema-meta-constraints xmlns="http://csrc.nist.gov/ns/oscal/metaschema/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://csrc.nist.gov/ns/oscal/metaschema/1.
Not Paul, of course, but: are these not remote URLs to bind schemas to the instance and allow schema-checking to occur for the constraints to occur during developmenet (if you use a supported IDE to add/change/delete constraints)?

2024-10-22 13:51 UTC, wandmagic commented on src/validations/constraints/fedramp-external-constraints.xml
> +<metaschema-meta-constraints xmlns="http://csrc.nist.gov/ns/oscal/metaschema/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://csrc.nist.gov/ns/oscal/metaschema/1.
Yes it's for ide schema checking

2024-10-24 03:57 UTC, aj-stein-gsa requested changes
Apologies for the delayed review.

This is very good work, but we may need to touch a few things up in regards to the documentation URLs generally and also more recent constraint style guide requirements.

2024-10-24 03:57 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>User with uuid {@uuid} must have a single type prop.</message>
Re [FRR111](https://github.com/GSA/fedramp-automation/blob/feature-constraints-style-guide/src/validations/constraints/STYLE.md#frr111) and [FRR113](https://github.com/GSA/fedramp-automation/blob/feature-constraints-style-guide/src/validations/constraints/STYLE.md#frr113), can we adjust this message to use active voice and minimize jargon?

```suggestion
                <message>A FedRAMP document MUST define a user with a type.</message>
```

2024-10-24 03:57 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>User with uuid {@uuid} must have a single privilege prop.</message>
Re [FRR111](https://github.com/GSA/fedramp-automation/blob/feature-constraints-style-guide/src/validations/constraints/STYLE.md#frr111) and [FRR113](https://github.com/GSA/fedramp-automation/blob/feature-constraints-style-guide/src/validations/constraints/STYLE.md#frr113), can we adjust this message to use active voice and minimize jargon?

```suggestion
                <message>A FedRAMP document MUST define a user with a privilege for their use of the system.</message>
```

2024-10-24 03:57 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>User with uuid {@uuid} must have a single sensitivity prop.</message>
Re [FRR111](https://github.com/GSA/fedramp-automation/blob/feature-constraints-style-guide/src/validations/constraints/STYLE.md#frr111) and [FRR113](https://github.com/GSA/fedramp-automation/blob/feature-constraints-style-guide/src/validations/constraints/STYLE.md#frr113), can we adjust this message to use active voice and minimize jargon?

```suggestion
                <message>A FedRAMP document MUST define a user with a sensitivity level of their use of the system.</message>
```

2024-10-24 03:57 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>User with uuid {@uuid} must have at least one role id.</message>
Re [FRR111](https://github.com/GSA/fedramp-automation/blob/feature-constraints-style-guide/src/validations/constraints/STYLE.md#frr111) and [FRR113](https://github.com/GSA/fedramp-automation/blob/feature-constraints-style-guide/src/validations/constraints/STYLE.md#frr113), can we adjust this message to use active voice and minimize jargon?

```suggestion
                <message>A FedRAMP document MUST define a user with at least one role by a role identifier.</message>
```

2024-10-24 03:57 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>User with uuid {@uuid} must have at least one authorized privilege id.</message>
Re [FRR111](https://github.com/GSA/fedramp-automation/blob/feature-constraints-style-guide/src/validations/constraints/STYLE.md#frr111) and [FRR113](https://github.com/GSA/fedramp-automation/blob/feature-constraints-style-guide/src/validations/constraints/STYLE.md#frr113), can we adjust this message to use active voice and minimize jargon?

```suggestion
                <message>A FedRAMP document MUST define a user with at least one authorized privilege by a privilege identifier.</message>
```

2024-10-24 03:57 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#user"/>
Blocking: the anchor in the help-url value does not seem to reference a specific section of the existing part of this page in `develop`. Am I missing something?

2024-10-24 03:57 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#user"/>
Blocking: the anchor in the help-url value does not seem to reference a specific section of the existing part of this page in `develop`. Am I missing something?

2024-10-24 03:57 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#user"/>
Blocking: the anchor in the help-url value does not seem to reference a specific section of the existing part of this page in `develop`. Am I missing something?

2024-10-24 03:57 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#user"/>
Blocking: the anchor in the help-url value does not seem to reference a specific section of the existing part of this page in `develop`. Am I missing something?

2024-10-24 03:57 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#user"/>
Blocking: the anchor in the help-url value does not seem to reference a specific section of the existing part of this page in `develop`. Am I missing something?

2024-10-24 18:03 UTC, wandmagic commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#user"/>
See the PR for adding this into the docs

2024-10-24 18:11 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#user"/>
Sorry need to wrap up the PR on that one too.

2024-10-25 14:05 UTC, kyhu65867 submitted a review, later dismissed
You can also resolve this without changes if you really want to but I think what I said should be considered

2024-10-25 14:09 UTC, wandmagic commented on src/validations/constraints/content/ssp-user-has-authorized-privilege-INVALID.xml
> +    <user uuid="44444444-0000-4000-9000-000000000004">
we originally did have an SSP-all-VALID, It was causing conflicts because different constraints were impossible to both be negative. here i could certainly make them into a single file of ssp-user-INVALID.xml

2024-10-29 13:54 UTC, aj-stein-gsa requested changes
Really solid work as always, can we discuss fixing this up and readying it to go. I am sorry I missed one bit of this potentially in doc review, so we will need to circle back.

2024-10-29 13:54 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +            <allowed-values id="user-privilege-level" target="//user/prop[@name='privilege-level']/@value" allow-other="no" level="ERROR">
I had to double-check but it seems we do diverge from upstream NIST values, the implied default is `allow-other="no"` so we need to fix that up here, the tests, and the docs, but otherwise good.

https://github.com/usnistgov/OSCAL/blob/v1.1.2/src/metaschema/oscal_implementation-common_metaschema.xml#L404-L408

https://pages.nist.gov/metaschema/specification/syntax/constraints/#allowed-values-constraints

```suggestion
            <allowed-values id="user-privilege-level" target="//user/prop[@ns='https://fedramp.gov/ns/oscal' and @name='privilege-level']/@value" allow-other="no" level="ERROR">
```

2024-10-30 12:13 UTC, aj-stein-gsa approved these changes

2024-10-30 15:39 UTC, DimitriZhurkin approved these changes

2024-10-30 19:45 UTC, aj-stein-gsa commented
@wandmagic can you please update the checklist so when a third review comes in, we can approve and merge? Thanks.

2024-10-31 02:06 UTC, merged