Add information-type-800-60-v2r1
GSA/fedramp-automation pull request #764
Opened 2024-10-08 21:03 UTC by DimitriZhurkin

# Committer Notes

In `fedramp-external-allowed-values.xml`, add the `information-type-800-60-v2r1` constraint.

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-10-09 13:41 UTC, aj-stein-gsa requested changes
Nice work. Very, very close, but I would recommend one important change.

2024-10-09 13:41 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +            <allowed-values id="information-type-800-60-v2r1" target="system-characteristics/system-information/information-type/categorization/information-type-id" allow-other="no" level="ERROR">
This is good but I think you can only constraint these with a given system. I am not 100% certain this will work as-is, but it must be something like that.

```suggestion
            <allowed-values id="information-type-800-60-v2r1" target="system-characteristics/system-information/information-type/categorization[@system="https://doi.org/10.6028/NIST.SP.800-60v2r1"]/information-type-id" allow-other="no" level="ERROR">
```

2024-10-09 14:01 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +            <allowed-values id="information-type-800-60-v2r1" target="system-characteristics/system-information/information-type/categorization/information-type-id" allow-other="no" level="ERROR">
Not sure why the push throws the following error:
```
Installed distributions
  Trying to resolve the latest version from remote
  Error: error code: 502
```

It worked fine yesterday.

2024-10-09 14:23 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +            <allowed-values id="information-type-800-60-v2r1" target="system-characteristics/system-information/information-type/categorization/information-type-id" allow-other="no" level="ERROR">
Re-running the job seemed to work fine.

2024-10-09 14:48 UTC, aj-stein-gsa approved these changes

2024-10-09 17:27 UTC, aj-stein-gsa commented
I am going to propose some improvements around positive and negative tests, as discussed in standup, @DimitriZhurkin, one moment.

2024-10-09 18:01 UTC, aj-stein-gsa reviewed
Let's expand some of the tests and discuss changes in my recommendations in the PR (I cannot use suggestions for files out of scope for the PR).

https://github.com/DimitriZhurkin/fedramp-automation/pull/4

I DMed in the team chat to further discuss the implications here. I want more robust tests based on other bugs I have seen reported and want to make sure we fully test the mechanics in positive and negative tests if possible.

2024-10-09 19:51 UTC, DimitriZhurkin commented
I tried your suggestions, and `ssp-all-VALID.xml` was failing. I removed the changes from it.

I'll commit the changes to `ssp-information-type-id-INVALID.xml`.

2024-10-10 15:00 UTC, aj-stein-gsa commented
> I tried your suggestions, and `ssp-all-VALID.xml` was failing. I removed the changes from it.

It took me some time to figure out why but I read through the output and I understand now. I will complete my review on this request.

2024-10-10 15:00 UTC, merged