640 readme cleanup
GSA/fedramp-automation pull request #771
Opened 2024-10-10 21:04 UTC by kyhu65867

# Committer Notes

{Please provide a description of what this PR accomplishes. Be sure to reference any issues addressed. If the PR is a work-in-progress submitted for early review, please submit the PR as a draft PR using the "Draft pull request" dropdown.}

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-10-10 21:16 UTC, aj-stein-gsa commented
@kyhu65867 thanks for the time today and pushing up the work, I will review once you have finished more of the work and mark it as ready for review from us. 😄

2024-10-10 21:17 UTC, kyhu65867 commented
I addressed most of issue 640 and some of issue 739. Still in progress but I think it's a significant improvement from where it was before

2024-10-11 15:33 UTC, kyhu65867 commented
I think the main readme is in a good place. I'm going to close this for review, let me know what you all think!!

2024-10-11 15:53 UTC, aj-stein-gsa requested changes

2024-10-11 15:53 UTC, aj-stein-gsa commented on README.md
> +The FedRAMP Program Management Office (PMO) has drafted FedRAMP specific tooling and guidance to ensure our stakeholders can fully express and review their FedRAMP Security Authorization Packages usi
So it has been so long I didn't realize I have not read this in years, so first off, thank you! Quick just-in-time feedback: can we say OSCAL's syntax and not _just_ SSP syntax? That is inaccurate and misleading.

```suggestion
The FedRAMP Program Management Office (PMO) has drafted FedRAMP specific tooling and guidance to ensure our stakeholders can fully express and review their FedRAMP Security Authorization Packages using NIST’s [OSCAL syntax](https://pages.nist.gov/OSCAL/documentation/).
```

2024-10-11 19:27 UTC, aj-stein-gsa reviewed
And a general question, are we going to move the constraint README for development here and delete those files? Is this PR part of a series of such improvements or this going to be the end of this work?

(Sorry, typed this review question, but had not submitted. It's a few hours old.)

2024-10-11 19:32 UTC, kyhu65867 commented
I didn't know if we wanted to move the constraints readme just because I wanted this readme to be a general overview of everything this repo has and I think in its final form the repo will have more than just the constraints tooling (unless I'm wrong). I also could see this becoming a series of improvements, especially since there are a bunch of dead readme files scattered throughout the repo. But I think that is a part of a bigger project of "decluttering" so that we can have as streamlined and clear of a readme as possible. It's hard to make a streamlined and clear readme with sort of a clunky repo (no offense)

2024-10-15 20:06 UTC, Rene2mt requested changes

2024-10-15 20:06 UTC, Rene2mt commented on README.md
> +As a part of this project, we are continuing to release "constraints," or automated "checks" of FedRAMP's required controls, to expand the coverage of our tooling and further automate the review of s
Use of word "controls" might confuse users in this context as we're not talking about the security "control"  that are in the baselines. Maybe, we could say something like:

```suggestion
Our ongoing work is focused on developing automated validation tooling using the oscal-cli to automatically check that security artifacts in a FedRAMP digital authorization package (such as an system security plan) complies with FedRAMP information and data requirements. 

As a part of this project, we are continuing to release "constraints," or automated "checks" of FedRAMP's digital authorization package requirements, to expand the coverage of our tooling and further automate the review of security artifacts. To learn more about installing and using our validation tooling, go [here](https://github.com/GSA/fedramp-automation/blob/develop/src/validations/constraints/README.md). 
```

2024-10-15 20:06 UTC, Rene2mt commented on README.md
>  - **FedRAMP OSCAL Registry** This registry is the authoritative source for all FedRAMP extensions to the OSCAL syntax, FedRAMP-defined identifiers, and accepted values. The FedRAMP OSCAL Registry is
These are slated for deprecation per ADR #738 .  Should we leave until then or go ahead and remove now since we're updating the page?

2024-10-15 20:06 UTC, Rene2mt commented on README.md
>  - **Implementation Guides:** These documents help tool developers and content authors ensure any generated OSCAL-based FedRAMP deliverabes are fully compliant with FedRAMP’s extensions, defined ident
The automate.fedramp.gov site effectively replaced the guides, so lets update this as follows:

```suggestion
- **Implementation Documentation:** The [FedRAMP Developer Hub documentation site](https://automate.fedramp.gov/documentation/) helps tool developers and content authors ensure any generated OSCAL-based FedRAMP deliverables are fully compliant with FedRAMP’s extensions, defined identifiers, and acceptable values. 
```

2024-10-16 19:16 UTC, brian-ruf commented on README.md
> +In addition to guides and examples assisting in the production of OSCAL artifacts, the FedRAMP PMO is developing software to assist in automating the review of OSCAL (Open Security Controls Assessmen
I thought we weren't supposed to refer to "FedRAMP PMO" anymore. Just "FedRAMP".

2024-10-17 13:42 UTC, aj-stein-gsa requested changes

2024-10-17 13:42 UTC, aj-stein-gsa commented on README.md
>  ### Creating a release
I am of two minds on this, but I am not sure it matters because I doubt our own developers are reading this README. Two approaches, either:

1. Point to the checklist in [the wiki](https://github.com/GSA/fedramp-automation/wiki/Release-Prep)
2. Delete this section entirely and presume the FedRAMP Team who needs to make a release will not read this anyway.

I am all for 2, I actually set this up I believe to be transparent but to offboard to colleagues from the contractor developer team who are no longer here. Parts of this guidance was not followed, so Approach 2 will not change much.

2024-10-17 14:14 UTC, brian-ruf approved these changes
LGTM

2024-10-17 14:24 UTC, brian-ruf commented on README.md
> +| [FedRAMP OSCAL Validation Tooling](./tree/develop/src/validations/constraints) |  The folder that contains the validation tooling and constraints      |
Do we mean to specifically link to the constraints in the develop branch in this link?

2024-10-17 14:24 UTC, aj-stein-gsa requested changes
Some more changes and recommendations. There is a lot. We can talk through it later if you like.

2024-10-17 14:24 UTC, aj-stein-gsa commented on README.md
> +| Component                                                       | Description                                                                        |
Let's be careful with the term [component](https://pages.nist.gov/OSCAL-Reference/models/v1.1.2/component-definition/), since it has a specific meaning in OSCAL.

```suggestion
| Resource                                                       | Description                                                                        |
```

2024-10-17 14:24 UTC, aj-stein-gsa commented on README.md
> +| [FedRAMP Rev 5 Releases](/tree/master/dist/content/rev5)         | The folder that contains guidance and examples related to rev5                     |
I understand the intent here, but we can use relative links without explicating the branch so, once 🤞 the latter merges we do not have to change the code before it lands.

```suggestion
| [FedRAMP OSCAL Validation Tooling](./src/validations/constraints) |  The folder that contains the validation tooling and constraints      |
| [FedRAMP Rev 5 Releases](./dist/content/rev5)         | The folder that contains guidance and examples related to rev5                     |
```

2024-10-17 14:24 UTC, aj-stein-gsa commented on README.md
> +Our ongoing work is focused on developing automated validation tooling using the oscal-cli to automatically check that security artifacts in a FedRAMP digital authorization package (such as an system
Minor wording tweaks and capitalization of SSP is probably for the best.

```suggestion
Our current focus is developing validation constraints to use with the oscal-cli to automatically check that all parts of a FedRAMP digital authorization package (such as System Security Plan) meet FedRAMP's requirements before staff start a formal review. 
```

2024-10-17 14:24 UTC, aj-stein-gsa commented on README.md
>  - **FedRAMP OSCAL Registry** This registry is the authoritative source for all FedRAMP extensions to the OSCAL syntax, FedRAMP-defined identifiers, and accepted values. The FedRAMP OSCAL Registry is
Do we need any of this anymore if we have the table in the earlier section? Much of this can go away or be integrated into that table, yeah?

2024-10-17 14:24 UTC, aj-stein-gsa commented on README.md
> +<details><summary>Resources</summary>
I appreciate we added this section to be helpful, but maybe we should just point NIST documentation and not repeat much of it. In the past, many of the things in the resource section we integrally used for our tooling. At this point, once this content merges to master, that will not be the case anymore.

2024-10-17 14:24 UTC, aj-stein-gsa commented on README.md
> +This section is for prospective contributors to our automation efforts. As an open source project, fedramp-automation welcomes contributions. To see a detailed guide for contributors, go [here](https
I'd also do a relative path here for similar reasons to above so the branch changes are handled for free whatever branch you are on.

```suggestion
This section is for prospective contributors to our automation efforts. As an open source project, fedramp-automation welcomes contributions. To see a detailed guide for contributors, go [here](./CONTRIBUTING.md)
```

2024-10-18 20:22 UTC, kyhu65867 commented on README.md
> +The FedRAMP Program Management Office (PMO), has drafted FedRAMP specific tooling and guidance to ensure our stakeholders can fully express and review their FedRAMP Security Authorization Packages us
I am not going to commit this suggestion but rather use it to inform my own edits.

2024-10-18 20:30 UTC, kyhu65867 commented on README.md
>  - **FedRAMP OSCAL Registry** This registry is the authoritative source for all FedRAMP extensions to the OSCAL syntax, FedRAMP-defined identifiers, and accepted values. The FedRAMP OSCAL Registry is
Counterpoint-- why do we need the table if none of those resources will be contained in this repository anymore?

2024-10-18 20:41 UTC, kyhu65867 commented on README.md
> +In addition to guidance and examples assisting in the production of OSCAL artifacts, the FedRAMP PMO is developing software to assist in automating the review of OSCAL (Open Security Controls Assessm
I like a bit of context but I shortened it down substantially

2024-10-18 20:42 UTC, kyhu65867 commented on README.md
> +| Component                                                       | Description                                                                        |
Question about just deleting the table entirely-- if we only have one project resource that is the validation tooling I don't think it is necessary

2024-10-18 20:45 UTC, kyhu65867 commented on README.md
>  - **FedRAMP OSCAL Registry** This registry is the authoritative source for all FedRAMP extensions to the OSCAL syntax, FedRAMP-defined identifiers, and accepted values. The FedRAMP OSCAL Registry is
Addressed this feedback by removing that whole section and instead pointing to the automate.fedramp.gov site

2024-10-18 20:46 UTC, kyhu65867 commented on README.md
>  ### Creating a release
Deleted :)

2024-10-18 20:47 UTC, kyhu65867 commented on README.md
> +| [FedRAMP OSCAL Validation Tooling](./tree/develop/src/validations/constraints) |  The folder that contains the validation tooling and constraints      |
Thanks for the heads up, I removed the table and tried to make links relative. The only reason I am pointing to the develop branch is that there is no constraints folder in main, the tooling is only accessible via the develop branch

2024-10-18 20:47 UTC, kyhu65867 commented on README.md
> +| [FedRAMP Rev 5 Releases](/tree/master/dist/content/rev5)         | The folder that contains guidance and examples related to rev5                     |
Done

2024-10-18 20:47 UTC, kyhu65867 commented on README.md
> +Our ongoing work is focused on developing automated validation tooling using the oscal-cli to automatically check that security artifacts in a FedRAMP digital authorization package (such as an system
done

2024-10-18 20:48 UTC, kyhu65867 commented on README.md
> +<details><summary>Resources</summary>
I removed this whole section hehe

2024-10-18 20:48 UTC, kyhu65867 commented on README.md
> +This section is for prospective contributors to our automation efforts. As an open source project, fedramp-automation welcomes contributions. To see a detailed guide for contributors, go [here](https
done

2024-10-22 13:02 UTC, aj-stein-gsa requested changes
Some minor touchups before a more thorough review. Also it looks like we need to rebase your branch as a bunch of constraint file changes are in the PR now that are not related to the README edits. That happens.

2024-10-22 13:02 UTC, aj-stein-gsa commented on README.md
> +FedRAMP maintains this repository with data, software, and documentation to review digital authorization packages for FedRAMP authorizations using [OSCAL](https://pages.nist.gov/OSCAL/documentation/)
Minor spacing issue, double spacing after the phrase primary aim:

```suggestion
FedRAMP maintains this repository with data, software, and documentation to review digital authorization packages for FedRAMP authorizations using [OSCAL](https://pages.nist.gov/OSCAL/documentation/). Our primary aim is to reduce manual review efforts and timeframes by validating whether submissions conform to FedRAMP’s requirements. Once complete, our tooling will help ensure that packages such as System Security Plans (SSPs) and Plans of Action and Milestones (POA&Ms) meet FedRAMP's expectations before submission, streamlining the review process.
```

2024-10-25 16:53 UTC, Rene2mt requested changes
Like the leaner README...nice work.  Just a few blocking comments:

1.  Need confirmation on the build requirements
2.  I assume this PR should only have the root README?  If we can rebase, that should clear some of the other unrelated changes

2024-10-25 16:53 UTC, Rene2mt commented on README.md
>  A top-level Makefile is provided to simplify builds.
@aj-stein-gsa and @wandmagic can you confirm the "build requirements"?  I think oscal-cli requires java 11+ and python 3.9 is nearing EOL...not sure we need to list python at all.

2024-10-25 21:01 UTC, aj-stein-gsa commented on README.md
>  A top-level Makefile is provided to simplify builds.
Fair enough, I would argue in hindsight that we should cut Python altogether because I forgot to recall during last review #738 that we will get rid of all relevant parts of the codebase that use Python.

2024-10-28 17:23 UTC, Rene2mt requested changes

2024-10-28 17:23 UTC, Rene2mt commented on README.md
@kyhu65867 the README looks so much better!! In the "Build requirements are" list, can you update "Java 8+" to "Java 11+", and remove the "Python 3.9+" bullet?  I think this PR is ready once that's done.

2024-10-28 20:28 UTC, kyhu65867 commented on README.md
Done in commit b16d915

2024-10-28 20:55 UTC, aj-stein-gsa approved these changes

2024-10-28 23:22 UTC, Rene2mt approved these changes

2024-10-30 02:51 UTC, merged