WIP ADR for system identifier-type and FedRAMP extension namespace
GSA/fedramp-automation pull request #774
Opened 2024-10-11 20:53 UTC by Rene2mt

**[DO NOT MERGE]  Work In Progress (WIP)**

# Committer Notes

This WIP ADR documents proposed options going forward for `identifier-type` and FedRAMP extension `prop` namespaces.  This is part of issue #773 and reported issue #769

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-10-17 14:05 UTC, kyhu65867 submitted a review, later dismissed
I like this. Clear and understandable, I especially like how you explicitly called out the http versus https distinction because that might be hard to spot initially.

2024-10-23 22:02 UTC, aj-stein-gsa reviewed
@Rene2mt, update the checklist and I shall review, thanks in advance!

2024-10-24 13:19 UTC, aj-stein-gsa requested changes
I'll be a contrarian here.

2024-10-24 13:19 UTC, aj-stein-gsa commented on documents/adr/0010-fedramp-identifier-type-and-namespace.md
> +Proceed with option 4 to minimize impact to OSCAL SSP authors.  There is only one instance of the use of `identifier-type` in an OSCAL SSP, the potential impact if SSP authors need to update it is mi
I am going to be the counter-argument here. Since this is going into a future major release, allowing for breaking changes, I would say let's go with Option 2.

```suggestion
Proceed with Option 2.  The inconsistency in documentation and tooling was the source of a bug that initiated an investigation and led to this ADR. This change will have an impact on updating documentation for FedRAMP, but there is little evidence or public feedback to indicate one or more community-maintained tools warrant this concern. Alignment sooner rather than later by FedRAMP, who will operationalize the FedRAMP constraints, is a key factor to prioritize this change the soonest major release, not defer it until later.
```

2024-10-24 13:34 UTC, kyhu65867 commented on documents/adr/0010-fedramp-identifier-type-and-namespace.md
> +Proceed with option 4 to minimize impact to OSCAL SSP authors.  There is only one instance of the use of `identifier-type` in an OSCAL SSP, the potential impact if SSP authors need to update it is mi
When you say "warrent this concern," what do you mean? Who is concerned about what?

2024-10-24 23:39 UTC, Rene2mt commented on documents/adr/0010-fedramp-identifier-type-and-namespace.md
> +Proceed with option 4 to minimize impact to OSCAL SSP authors.  There is only one instance of the use of `identifier-type` in an OSCAL SSP, the potential impact if SSP authors need to update it is mi
Any tools that are referencing FedRAMP extensions such as `<prop ns="https://fedramp.gov/ns/oscal" name="response-point" value=""/>` will need to change to `<prop ns="http://fedramp.gov/ns/oscal" name="response-point" value=""/>` (notice the namespace change from **https** to **http**).  The "response-point" is one of about 90 FedRAMP extensions.

We've mentioned this ADR but haven't received any feedback indicating concern.

On our end, we'd need update the documentation, examples (a.k.a. "templates), the baselines, and constraints.   Its in a lot of places, but very simple / low effort fix on our end.

2024-10-31 02:04 UTC, Gabeblis reviewed
I think this all looks really good! The context and possible solutions are clear. Just some minor suggestions for readability and fixing typos.

2024-10-31 18:46 UTC, Rene2mt commented on documents/adr/0010-fedramp-identifier-type-and-namespace.md
> +While not backwards compatible, option 2 will provide is more understandable and maintainable long-term, which should prevent misunderstandings in the future.
Great suggestion @Gabeblis.  I'm going to commit and resolve 👍🏾

2024-10-31 19:10 UTC, Gabeblis approved these changes
LGTM

2024-11-04 13:45 UTC, kyhu65867 approved these changes
This looks good to me. Ship it!

2024-11-04 16:25 UTC, wandmagic approved these changes

2024-11-04 16:25 UTC, wandmagic commented
lets get it

2024-12-06 18:43 UTC, kyhu65867 approved these changes

2024-12-11 20:29 UTC, merged