fix informational constraint handling and make ssp-all valid correct
GSA/fedramp-automation pull request #775
Opened 2024-10-14 12:43 UTC by wandmagic

# Committer Notes

It has come to my attention that the test runner was mis-labeling information level constraints as failure cases, this corrupted the quality of our three informational constraints. this is now resolved.
This PR also fixes SSP all valid by introducing some missing backmatter resources.

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-10-15 17:00 UTC, Rene2mt commented
The "informational" constraint handling seems correct but changes to fedramp-external-constraints.xml are needed.  This PR might be blocked until we can identify and implement an "informational" constraint.  

The three constraints in this PR should actually be "ERROR" level types.

2024-10-15 17:01 UTC, Rene2mt requested changes

2024-10-16 11:20 UTC, wandmagic commented on src/validations/constraints/fedramp-external-constraints.xml
>              </expect>
Updated these to be ERROR constraints.

Will we have any INFORMATIONAL constraints?

looked through the constraint tracker and other INFO level seems to be existence checks or has index checks that we probably want as error. Let's discus an example INFORMATION level constraint so we can get it in this PR

2024-10-16 12:22 UTC, aj-stein-gsa requested changes
I'd like the constraint change to be handled in #779, we can talk aboiut the other very relevant work separately here as well.

2024-10-16 14:17 UTC, aj-stein-gsa commented on src/scripts/dev-constraint.js
>                  }
Why should we handle informational differently than the others at this point?

2024-10-16 14:24 UTC, wandmagic commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>This FedRAMP SSP must define its NIST SP 800-63 federation assurance level (FAL).</message>
https://github.com/GSA/fedramp-automation/pull/780
made another PR which does not contain this over here

2024-10-16 14:25 UTC, closed without merging