Add security-sensitivity-level-matches-security-impact-level
GSA/fedramp-automation pull request #786
Opened 2024-10-17 14:27 UTC by DimitriZhurkin

# Committer Notes

Add the `security-sensitivity-level-matches-security-impact-level` constraint.

_Note:_ Tested rigorously with various combinations of `security-sensitivity-level` and `security-impact-level` values.

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-10-17 20:50 UTC, wandmagic submitted a review, later dismissed
looks good!
nice if / then usage

2024-10-21 12:56 UTC, Gabeblis approved these changes
Looks good! Just a non-blocking question about where this fits into the style guide.

2024-10-21 12:56 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                else ('fips-199-low')"/>
Non-blocking: @aj-stein-gsa should we add where these fit into the style guide?

2024-10-21 13:01 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                else ('fips-199-low')"/>
It's a good question general but you are asking about variables in the style guide, if else expressions, something else, @Gabeblis?

2024-10-21 13:07 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                else ('fips-199-low')"/>
> It's a good question general but you are asking about variables in the style guide, if else expressions, something else, @Gabeblis?

Apologies for not being more specific. I was referring to the variables themselves. When more are added, where should they go, how should they be organized, etc.

2024-10-21 13:13 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                else ('fips-199-low')"/>
So you want more rules, eh? As you wish! 🍿 (Jokes aside, the placement of variables is a good question, I had a similar question when the feature was generally implemented in Java and added to the specification).

2024-10-21 13:27 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>A FedRAMP SSP security sensitivity level must match the highest level within the security impact levels.</message>
We could add something like, `For more information, see https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#system-sensitivity-level`.

Of course, there's always a danger of siting an absolute URL.

2024-10-21 13:45 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>A FedRAMP SSP security sensitivity level must match the highest level within the security impact levels.</message>
> Of course, there's always a danger of siting an absolute URL.

If you have an alternate solution to citation of absolute URLs that is flexible and does not involve inserting all the documentation into this constraint file, I am all ears. I would propose writing that somewhere outside the comment box on this PR, as that is going to be a long-form conversation.

2024-10-21 13:55 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>A FedRAMP SSP security sensitivity level must match the highest level within the security impact levels.</message>
We could write something generic, something applicable to all messages.

How about referencing the `help-url` prop? Something like, `For more information, see documentation referenced in the help-url property`?

2024-10-21 14:13 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>A FedRAMP SSP security sensitivity level must match the highest level within the security impact levels.</message>
If you don't mind, I'd rather not use all-caps `MUST`.

To elaborate, in tech writing, all caps are frowned at, as are italic and underlined blocks.

2024-10-21 16:19 UTC, aj-stein-gsa approved these changes

2024-10-21 17:51 UTC, Rene2mt requested changes
PR looks great.  One blocking request to make minor update to the message.

2024-10-21 17:51 UTC, Rene2mt commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>A FedRAMP SSP MUST define its FIPS-199 security sensitivity level to match the highest security impact level for the system's confidentiality, integrity, and availability obj
I think this constraint was set to level **WARNING** because there are some _rare_ exceptions (e.g., AO specifies an overrides the expected security sensitivity level for some reason).  For that reason, the error message should probably be changed from _MUST_ to _SHOULD_.

```suggestion
                <message>A FedRAMP SSP SHOULD define its FIPS-199 security sensitivity level to match the highest security impact level for the system's confidentiality, integrity, and availability objectives.</message>
```

2024-10-21 18:17 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>A FedRAMP SSP MUST define its FIPS-199 security sensitivity level to match the highest security impact level for the system's confidentiality, integrity, and availability obj
@Rene2mt, nice catch. Done.

2024-10-21 18:23 UTC, aj-stein-gsa approved these changes
I guess I should learn to review my own notes and remember our previous conversations, happy to approve a second time with a now even more correct version. Thanks to all of you.

2024-10-22 01:54 UTC, Gabeblis reviewed
This looks good, we're just lacking proper documentation on this constraint.

2024-10-22 01:54 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#system-sensitiv
The help-url does link to some documentation on the security sensitivity level, but currently there is no mention of the security impact level or the goal of this constraint.

2024-10-22 14:44 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#system-sensitiv
I am going to mark this as resolved for now as I have opened issue https://github.com/GSA/fedramp-automation/issues/801, and PR https://github.com/GSA/automate.fedramp.gov/pull/91 to add the missing documentation.

2024-10-22 14:44 UTC, Gabeblis approved these changes
Awesome work.

2024-10-23 00:39 UTC, Rene2mt approved these changes

2024-10-24 13:23 UTC, merged