Feature/enforce help props
GSA/fedramp-automation pull request #790
Opened 2024-10-18 12:14 UTC by wandmagic

# Committer Notes

use style guide constraint to enforce style guide 

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-10-18 13:06 UTC, aj-stein-gsa commented
I know this is a draft, but I am excited for this. One short-term ask, the other a consideration in that order.

1. Can we point to Gabe's help URL cleanup branch, @Gabeblis, where is that?
2. Can we consider once this is stable integrating [SARIF into GitHub](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github)? If we could have it comment on the PR so we know (which seems to require a custom [action in addition to upload maybe](https://github.com/sett-and-hive/sarif-to-comment-action), but we ought to consider this.

2024-10-18 13:06 UTC, aj-stein-gsa commented
Also, if I feel like it can I add some more style guide checks into the file when you're ready with a PR to this branch off of your fork, @wandmagic?

2024-10-18 13:11 UTC, Gabeblis commented
> I know this is a draft, but I am excited for this. One short-term ask, the other a consideration in that order.
> 
> 1. Can we point to Gabe's help URL cleanup branch, @Gabeblis, where is that?
> 2. Can we consider once this is stable integrating [SARIF into GitHub](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github)? If we could have it comment on the PR so we know (which seems to require a custom [action in addition to upload maybe](https://github.com/sett-and-hive/sarif-to-comment-action), but we ought to consider this.

https://github.com/Gabeblis/fedramp-automation/tree/constraints/help-url

2024-10-18 13:16 UTC, aj-stein-gsa commented
> https://github.com/Gabeblis/fedramp-automation/tree/constraints/help-url

Thanks, I should stop asking you the same question in two or more places if I will not check my email updates quick enough. @wandmagic, can you adjust the target branch of this PR to [`/feature-constraints-style-guide`](https://github.com/GSA/fedramp-automation/tree/feature-constraints-style-guide)? I will repoint some of my PR there until we end up in develop. Thanks!

2024-10-21 22:16 UTC, wandmagic commented on src/validations/constraints/fedramp-external-allowed-values.xml
> -            </allowed-values>
Ah my bad I must have goofed the rebase I'll re introduce it

2024-10-28 16:51 UTC, Rene2mt requested changes
This is awesome stuff!!! My only feedback is the `src/validations/constraints/content/ssp-*.xml` contents may need to be rebased (see https://github.com/GSA/fedramp-automation/pull/795) to incorporate the fix to the "data-center" props.

2024-10-28 17:23 UTC, kyhu65867 requested changes
Note-- any and all data center props should follow this convention: 
<prop name='type' value='data-center' class='tertiary'/>

2024-10-28 17:23 UTC, kyhu65867 commented on features/steps/fedramp_extensions_steps.ts
> +        '-c',
It would be cool to add some higher level comments before functions/ core operations for documentation purposes

2024-10-28 17:23 UTC, kyhu65867 commented on src/validations/constraints/content/ssp-data-center-US-INVALID.xml
> +      <prop name='data-center' value='dc-zone-1' class='tertiary'/>
This is wrong-- name should be "type", value should be "data-center"

2024-10-28 17:23 UTC, kyhu65867 commented on src/validations/constraints/content/ssp-data-center-alternate-INVALID.xml
> +      <prop name='data-center' value='dc-zone-1' class='tertiary'/>
Same-- name is type, value is data-center

2024-10-28 17:23 UTC, kyhu65867 commented on src/validations/constraints/content/ssp-data-center-count-INVALID.xml
> +      <prop name='data-center' value='dc-zone-1' class='tertiary'/>
Same-- name is type, value is data-center

2024-10-28 17:23 UTC, kyhu65867 commented on src/validations/constraints/content/ssp-data-center-country-code-INVALID.xml
> +      <prop name='data-center' value='dc-zone-1' class='tertiary'/>
Same-- name is type, value is data-center

2024-10-28 17:23 UTC, kyhu65867 commented on src/validations/constraints/content/ssp-data-center-primary-INVALID.xml
> +      <prop name='data-center' value='dc-zone-1' class='tertiary'/>
Same

2024-10-28 17:23 UTC, kyhu65867 commented on src/validations/constraints/content/ssp-role-defined-authorizing-official-poc-INVALID.xml
> +      <prop name='data-center' value='dc-zone-1' class='tertiary'/>
same

2024-10-28 17:23 UTC, kyhu65867 commented on src/validations/constraints/content/ssp-role-defined-information-system-security-officer-INVALID.xml
> +      <prop name='data-center' value='dc-zone-1' class='tertiary'/>
Same

2024-10-28 17:23 UTC, kyhu65867 commented on src/validations/constraints/content/ssp-role-defined-system-owner-INVALID.xml
> +      <prop name='data-center' value='dc-zone-1' class='tertiary'/>
same

2024-10-28 17:23 UTC, kyhu65867 commented on src/validations/styleguides/fedramp_constraint_style.xml
> +    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
Happy about this :)

2024-10-28 17:42 UTC, DimitriZhurkin requested changes

2024-10-28 17:42 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>A FedRAMP SSP must define its NIST SP 800-63 identity assurance level (IAL).</message>
I think `must` should be `MUST`.

2024-10-28 17:42 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>A FedRAMP SSP must define its NIST SP 800-63 authenticator assurance level (AAL).</message>
Ditto.

2024-10-28 17:42 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>A FedRAMP SSP must define its NIST SP 800-63 federation assurance level (FAL).</message>
Ditto.

2024-10-30 20:33 UTC, closed without merging