Fix by-component implemented requirement checks
GSA/fedramp-automation pull request #796
Opened 2024-10-18 21:56 UTC by aj-stein-gsa

# Committer Notes

Fixes #770.

- Add new constraint to report against bad practice FedRAMP will not accept for requirements outside of statement.
- Fix current constraint and correct the test, target, and wording.

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-10-22 13:16 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-all-VALID.xml
>        <prop name="implementation-status" value="partial" ns="https://fedramp.gov/ns/oscal"/>
@Rene2mt, I was working on this later last week and I was surprised this bug fix is a little more confusing than I had once thought. I have a question about how we came to have the `prop[@name="implementation-status"]` and not use [the dedicated `implementation-status` assembly](https://pages.nist.gov/OSCAL-Reference/models/v1.1.2/system-security-plan/xml-reference/#/system-security-plan/control-implementation/implemented-requirement/statement/by-component/implementation-status)? I have been gone a while, but this the prop is [also thoroughly documented on our site](https://automate.fedramp.gov/documentation/ssp/6-security-controls/#implementation-status) and the primary `implementation-status` (not the prop) is not documented at all.

Do you know if there was/is a reason for this? It is not immediately related to the PR but tests kept failing as I moved that around and this led me to scratch my head.

2024-10-22 17:14 UTC, Rene2mt requested changes
I know this is draft.  Just adding suggestions per the discussion earlier.

2024-10-22 17:14 UTC, Rene2mt commented on src/validations/constraints/content/ssp-all-VALID.xml
>        <prop name="control-origination" value="sp-system" ns="https://fedramp.gov/ns/oscal"/>
```suggestion
      <prop name="control-origination" value="sp-system" ns="https://fedramp.gov/ns/oscal"/>
      <prop ns="https://fedramp.gov/ns/oscal" name="implementation-status" value="partial"/>
```

2024-10-22 17:14 UTC, Rene2mt commented on src/validations/constraints/content/ssp-all-VALID.xml
> +          <prop ns="https://fedramp.gov/ns/oscal" name="implementation-status" value="implemented"/>
Use the `implementations-status` assembly inside the `by-component`, however, it is optional.
```suggestion
```

2024-10-22 17:14 UTC, Rene2mt commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="missing-response-components" target="implemented-requirement/statement" test="count(./by-component) gt 0">
```suggestion
            <expect id="by-component-requirement-not-inside-statement" target="implemented-requirement" test="not(exists(by-component))" level="ERROR">
                <message>A FedRAMP SSP MUST document only a component-based implemented requirement within a specific statement, not at the control level.</message>
            </expect>
            <expect id="missing-response-components" target="implemented-requirement/statement" test="count(./by-component) gt 0" level="ERROR">
```

2024-10-22 17:14 UTC, Rene2mt commented on src/validations/constraints/content/ssp-by-component-requirement-not-inside-statement-INVALID.xml
> +        <prop ns="https://fedramp.gov/ns/oscal" name="implementation-status" value="implemented"/>
```suggestion
```

2024-10-22 17:14 UTC, Rene2mt commented on src/validations/constraints/content/ssp-by-component-requirement-not-inside-statement-INVALID.xml
> +        <prop ns="https://fedramp.gov/ns/oscal" name="implementation-status" value="partial"/>
```suggestion
```

2024-10-24 16:09 UTC, aj-stein-gsa commented
I am working on integrating Rene's feedback and reviewing the documentation to fix the test. His feedback was very helpful, but we found an unrelated bug when looking into errors with `ssp-all-VALID.xml` that were not making a lot of sense.

2024-10-30 21:58 UTC, closed without merging