Add allowed-values metadata fedramp-version
GSA/fedramp-automation pull request #800
Opened 2024-10-21 16:52 UTC by DimitriZhurkin

# Committer Notes

1. In `fedramp-external-allowed-values.xml`, add the metadata `fedramp-version` prop value.
2. In `ssp-all-VALID.xml`, add the metadata `fedramp-version` prop.

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-10-21 16:56 UTC, brian-ruf commented
@DimitriZhurkin what issue(s) do/does this address?

2024-10-21 17:12 UTC, DimitriZhurkin commented
Sorry, forgot to mention the issue: #789.

2024-10-21 18:16 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>A FedRAMP document metadata MUST contain a FedRAMP version.</message>
I like it: short, clean, and to the point. I would tweak the wording a little bit. We may want to add an explanation for the less GitHub-fluent where a CSP or 3PAO or similar stakeholder can identify a valid version number.

```suggestion
                <message>A FedRAMP document's metadata MUST define a valid FedRAMP version.</message>
                <remarks>
                    <p>All documents in a digital authorization package for FedRAMP must identify the  version that identifies which FedRAMP policies, guidance, and technical specifications its authors used during the creation and maintenance of the package.</p>
                    <p>FedRAMP maintains an official list of the versions on the <a href="https://github.com/GSA/fedramp-automation/releases">the fedramp-automation releases page</a>. Unless noted otherwise, a valid version is <a href="https://github.com/GSA/fedramp-automation/tags">a published tag name</a>.</p>
                </remarks>
```

2024-10-21 18:46 UTC, Rene2mt requested changes
Nice work.  I have a few requested changes.

2024-10-21 18:46 UTC, Rene2mt commented on src/validations/constraints/content/ssp-all-VALID.xml
> +    <prop name="fedramp-version" value="fedramp-3.0.0rc1-oscal-1.1.2"/>
All FedRAMP specific `prop` must have the FedRAMP namespace. Props without namespaces are assumed to be core OSCAL (e.g., "http://csrc.nist.gov/ns/oscal") but "fedramp-version" in not a core OSCAL `prop` so validation will result in errors.

```suggestions
    <prop name="fedramp-version" ns="https://fedramp.gov/ns/oscal" value="fedramp-3.0.rc1-oscal-1.1.2"/>
```

2024-10-21 18:46 UTC, Rene2mt commented on src/validations/constraints/content/ssp-all-VALID.xml
>      <oscal-version>1.0.0</oscal-version>
Recommed change below for consistency...otherwise, this will confuse users.

```suggestion
    <oscal-version>1.1.2</oscal-version>
```

2024-10-21 18:46 UTC, Rene2mt commented on src/validations/constraints/content/ssp-fedramp-version-INVALID.xml
> +		<oscal-version>1.0.0</oscal-version>
for consistency

```suggestion
    <oscal-version>1.1.2</oscal-version>
```

2024-10-21 18:46 UTC, Rene2mt commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +                <description>The current FedRAMP version.</description>
Minor wording suggestion

```suggestion
                <description>Identifies the FedRAMP version of the document.</description>
```

2024-10-21 18:50 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-all-VALID.xml
> +    <prop name="fedramp-version" value="fedramp-3.0.0rc1-oscal-1.1.2"/>
I get where are you going with that feedback, but that is only required if there are conflicting constraints. In this particular location in the model, there is permissive use of the `prop` assembly and for all matter of name, with the exclusion of `@name="marking"`. That said, I do find it a little confusing, but it is not strictly required.

As for the ergonomics of this, I did have two minds on this one. @david-waltermire and I discussed it a few days ago when I was formulating the AC in the issue (and this is why I left it out), but I suppose we should discuss more thoroughly before final review.

2024-10-21 18:50 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-all-VALID.xml
>      <oscal-version>1.0.0</oscal-version>
Nice catch agreed!

2024-10-21 18:51 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-fedramp-version-INVALID.xml
> +		<oscal-version>1.0.0</oscal-version>
Agreed

2024-10-21 18:57 UTC, david-waltermire commented on src/validations/constraints/content/ssp-all-VALID.xml
> +    <prop name="fedramp-version" value="fedramp-3.0.0rc1-oscal-1.1.2"/>
This is a FedRAMP prop, so it should 100% be in the FedRAMP namespace.

2024-10-21 19:00 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-all-VALID.xml
> +    <prop name="fedramp-version" value="fedramp-3.0.0rc1-oscal-1.1.2"/>
Then I clearly screwed up defining the requirements, this one is on me, @DimitriZhurkin, apologies.

2024-10-21 20:08 UTC, DimitriZhurkin commented
OK, I think I've implemented all comments.

The added `help-url` prop is a placeholder. I'll work on documentation separately.

2024-10-21 20:45 UTC, aj-stein-gsa reviewed
Are we going to add the remarks from the unresolved comment or we do not think it is necessary?

2024-10-21 21:24 UTC, DimitriZhurkin commented
Somehow, I had totally missed remarks. Added them.

2024-10-21 21:25 UTC, aj-stein-gsa submitted a review, later dismissed

2024-10-23 00:35 UTC, Rene2mt approved these changes

2024-10-23 13:34 UTC, DimitriZhurkin commented
Folks,

I'm working on the documentation for the `fedramp-version` prop. This means that I will update the `help-url` value later. This means that I'll have another commit of `fedramp-external-constraints.xml`.

In short, maybe it makes sense not to merge this PR until `help-url` is finalized in `fedramp-external-constraints.xml`.

2024-10-23 17:17 UTC, DimitriZhurkin commented
Created **FedRAMP Version** documentation (PR [#94](https://github.com/GSA/automate.fedramp.gov/pull/94)).

2024-10-23 21:13 UTC, Rene2mt approved these changes
Approved.  Associated documentation in PR https://github.com/GSA/automate.fedramp.gov/pull/94 also approved

2024-10-23 21:43 UTC, aj-stein-gsa commented
> Approved. Associated documentation in PR [GSA/automate.fedramp.gov#94](https://github.com/GSA/automate.fedramp.gov/pull/94) also approved

@DimitriZhurkin if you update the checklist accordingly to update the goal and AC list in #780 and the above in this PR, I will approve. But as I said today in standup, I expect these to be updated.

So you can use the GUI to check off the buttons on their lists. Or you can edit them in bulk to take an entry like this example.

```
- [ ] Example item 1
- [ ] Example item 2
```

And check it off by putting a lowercase `x` in the middle of the brackets.

```
- [x] Example item 1
- [x] Example item 2
```

You cannot do the following in the GUI, to cross out not applicable or out of scope parts of the issue, specific to that issue and not just as a habit 😉 , edit the list and put an explanation.


```
- [x] Example item 1
- ~Example item 2~ Does not require documentation because it is an update to GitHub CI config
```

Once you do something like that, I will approve.

2024-10-23 22:10 UTC, aj-stein-gsa approved these changes

2024-10-24 03:50 UTC, Gabeblis approved these changes

2024-10-24 05:13 UTC, merged

2024-10-24 13:31 UTC, kyhu65867 reviewed
LGTM