818 fix data center
GSA/fedramp-automation pull request #819
Opened 2024-10-24 16:36 UTC by kyhu65867

# Committer Notes

This PR addresses issue 818, thereby fixing data-center constraints and unit test files. The constraints needed to check for name=type and value=data-center, instead of name=data-center. Additionally, there were many unit tests that were not designed to test one issue at a time, (for example in the primary data center test document the country was also wrong) so I switched the documents to only one error per unit test. **NOTE** @Gabeblis agreed to update documentation for this PR

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-10-24 16:52 UTC, wandmagic submitted a review, later dismissed
looks good, nice bugfix

2024-10-24 17:38 UTC, DimitriZhurkin approved these changes
Looks good. Nice XML fixes.

2024-10-24 17:41 UTC, aj-stein-gsa requested changes
Great work done so quickly, mainly minor formatting things and a new style guide requirement I did not remind you of earlier on a call.

2024-10-24 17:41 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="data-center-count" target="." test="count(/location/prop[@name eq 'type'][@value eq 'data-center']) &gt; 1">
Can we add the prop for docs here now that will come into effect with GSA/automate.fedramp.gov#96?

```suggestion
            <expect id="data-center-count" target="." test="count(/location/prop[@name eq 'type'][@value eq 'data-center']) &gt; 1">
               <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0"  name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#data-centers" />
```

2024-10-24 17:41 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="data-center-primary" target="." test="count(/location/prop[@name eq 'type'][@value eq 'data-center'][@class eq 'primary']) = 1">
Can we add the prop for docs here now that will come into effect with GSA/automate.fedramp.gov#96?

```suggestion
            <expect id="data-center-primary" target="." test="count(/location/prop[@name eq 'type'][@value eq 'data-center'][@class eq 'primary']) = 1">
               <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0"  name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#data-centers" />
```

2024-10-24 17:41 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="data-center-alternate" target="." test="count(/location/prop[@name eq 'type'][@value eq 'data-center'][@class eq 'alternate']) &gt; 0">
Can we add the prop for docs here now that will come into effect with GSA/automate.fedramp.gov#96?

```suggestion
            <expect id="data-center-alternate" target="." test="count(/location/prop[@name eq 'type'][@value eq 'data-center'][@class eq 'alternate']) &gt; 0">
               <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0"  name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#data-centers" />
```

2024-10-24 19:15 UTC, Gabeblis requested changes
This all looks good. I know you didn't make any changes to the data-center constraints on lines 37-42 in this PR, but it would be nice to add the help-url props to those as well since the documentation for those constraints is in the same exact area.

2024-10-24 21:30 UTC, aj-stein-gsa approved these changes

2024-10-24 22:41 UTC, wandmagic approved these changes
looks good

2024-10-24 23:00 UTC, Rene2mt approved these changes
Looks good to me.

2024-10-25 00:22 UTC, aj-stein-gsa commented
If others who reviewed this PR are ok with the related documentation work in https://github.com/GSA/automate.fedramp.gov/pull/96 and approve that, this can merge very soon. For now, I mark DONOTMERGE.

/cc @Rene2mt @wandmagic @Gabeblis @DimitriZhurkin

2024-10-25 13:37 UTC, aj-stein-gsa commented
#96 is reviewed, so this is good to go. Remvoed the DONOTMERGE tag and merging in now. This is ready to ship.

2024-10-25 13:38 UTC, merged