issue template updates
GSA/fedramp-automation pull request #824
Opened 2024-10-25 19:32 UTC by brian-ruf

# Committer Notes

This PR adds one new issue template and modifies an existing issue template.
The new issue template is specifically for constraint work. 
The action-item template was modified to remove obsolete choices and to direct the submitter to the automate.fedramp.gov repo for issues related to documentation. 

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-10-25 20:39 UTC, aj-stein-gsa reviewed
This looks good so far, minor feedback and some questions about how we want to approach some of the implied consequences. Otherwise, very good stuff and I hope to merge soon.

2024-10-25 20:39 UTC, aj-stein-gsa commented on .github/ISSUE_TEMPLATE/3-action-item.yaml
>        - label: the **FedRAMP OSCAL Validations**
Very minor feedback, open question: should we add an Other?

```suggestion
      - label: the **FedRAMP SSP OSCAL Example** 
      - label: the **FedRAMP SAP OSCAL Example** 
      - label: the **FedRAMP SAR OSCAL Example**
      - label: the **FedRAMP POA&M OSCAL Example**
      - label: the **FedRAMP OSCAL Validations**
      - label: the **Not sure** 
```

2024-10-25 20:39 UTC, aj-stein-gsa commented on .github/ISSUE_TEMPLATE/4-constraint-work.yaml
> +name: Create or Revise a Constraint
Minor, non-blocking: we may want to even take some away, yes?

```suggestion
name: Add, Change, or Remove a Constraint
```

2024-10-25 20:39 UTC, aj-stein-gsa commented on .github/ISSUE_TEMPLATE/4-constraint-work.yaml
> +      render: xslt
Non-block, wow TIL that it is even possible. I am going to have to read the documentation!

2024-10-25 20:39 UTC, aj-stein-gsa commented on .github/ISSUE_TEMPLATE/4-constraint-work.yaml
> +      description: Describe how the OSCAL content is used by FedRAMP Reviewers.
In the presentation we mentioned prioritizing the CSP stakeholder group IIRC, and reviewers were among them. Is this the only group we care about insead of asking what group you think you are part of and what you think the purpose is? (I am flexible here, I am not it is not required.)

2024-10-25 20:39 UTC, aj-stein-gsa commented on .github/ISSUE_TEMPLATE/4-constraint-work.yaml
> +          - [ ] metapath is present and accurate
Minor: maybe we can make this more actionable?

```suggestion
          - [ ] [Metapath](https://pages.nist.gov/metaschema/specification/syntax/metapath/) is present,  accurate, and does not throw a syntax exception using `oscal-cli metaschema metapath eval -e "expression"`. 
```

2024-10-25 20:39 UTC, aj-stein-gsa commented on .github/ISSUE_TEMPLATE/4-constraint-work.yaml
> +      - There are only NIST-defined allowd values.
Minor: typo.

```suggestion
      - There are only NIST-defined allowed values.
```

2024-10-25 20:39 UTC, aj-stein-gsa commented on .github/ISSUE_TEMPLATE/4-constraint-work.yaml
> +      - NIST-allowed values must be extended with FedRAMP allowed values.
Do we think on initial submission for more junior staff and/or community contributors there should not be a "not sure"?

```suggestion
      - NIST-allowed values must be extended with FedRAMP allowed values.
      - Not sure, can maintainers help me choose?
```

2024-10-25 20:39 UTC, aj-stein-gsa commented on .github/ISSUE_TEMPLATE/4-constraint-work.yaml
> +      - This is a FedRAMP extension.
Since we are not really doing extension the same way we did in the past, can we avoid this wording?

```suggestion
      - This is a FedRAMP constraint in the FedRAMP-specific namespace.
```

2024-10-25 20:39 UTC, aj-stein-gsa commented on .github/ISSUE_TEMPLATE/4-constraint-work.yaml
> +      - This is optional core OSCAL syntax.
I think I know you are going with this, but different constraints have different ways of suggesting optional versus required depending on what's involved. Did we intend to be explict with syntax in a relevant wiki page? In the snippet inline to the selections? Something different?

2024-10-25 20:39 UTC, aj-stein-gsa commented on .github/ISSUE_TEMPLATE/4-constraint-work.yaml
> +      - This is a mix of required, optional, and/or extended syntax.
Can we add a not sure for more junior staff/community members who may not know given it is required?

```suggestion
      - This is a mix of required, optional, and/or extended syntax.
      - Not sure, can maintainers help me choose?
```

2024-10-25 20:39 UTC, aj-stein-gsa commented on .github/ISSUE_TEMPLATE/4-constraint-work.yaml
> +description: Define work to be performed specifically related to the creation, refinement, or decommissioning of constraints.
Minor: can we use plainer language?

```suggestion
description: Define work to be performed specifically related to the adding, changing, or removing constraints.
```

2024-10-25 20:40 UTC, aj-stein-gsa commented
Sorry for the delayed review, @brian-ruf. Also that feature branch isn't necessary and I wasn't fast enough to get rid of it. We can just target master for this given the other issues I need to report. I will take care of that bug report soonish. 😄

2024-10-25 22:52 UTC, brian-ruf commented on .github/ISSUE_TEMPLATE/4-constraint-work.yaml
> +      render: xslt
Found that in an r example. The`render` tag is the trick, but it has to specify a code format GH recognizes. Unfortunately, xpath wasn't on the list. So while XSLT doesn't actually seem to help with code formatting, it's at least a safe choice and closest match. 

Note that because the PR view file mode is read only, this can only be tested upon first use. It's one of the first quality checks I'll do post-merge. If it doesn't work, I'll strip out that statement and the tag; and let people manually add the back ticks.

2024-10-25 22:56 UTC, brian-ruf commented on .github/ISSUE_TEMPLATE/4-constraint-work.yaml
> +      description: Describe how the OSCAL content is used by FedRAMP Reviewers.
Good point. Tricky topic. I'll adjust wording.

2024-10-25 23:02 UTC, brian-ruf commented on .github/ISSUE_TEMPLATE/4-constraint-work.yaml
> +      - This is optional core OSCAL syntax.
I was thinking more along the lines of putting action lists into buckets:
- if the data is a required field in core OSCAL, we just need to address sample data and documentation. 
- if the data is an optional field in core OSCAL, we need to address all of the above, plus creat a constraint, test data, and define the test. 
- if the field is a FedRAMP extension, we need to do all of the above, plus document/track the existence of the extension.

That said, you raise a good point. Let me think a little on this and revisit it with your comment in mind.

2024-10-28 12:55 UTC, aj-stein-gsa commented on .github/ISSUE_TEMPLATE/4-constraint-work.yaml
> +      description: Describe how the OSCAL content is used by FedRAMP Reviewers.
I understand, no worries.

2024-10-28 14:50 UTC, Rene2mt requested changes
This looks great @brian-ruf.  I'll add my approval once the comments @aj-stein-gsa sent are resolved

2024-10-28 14:50 UTC, Rene2mt commented on .github/ISSUE_TEMPLATE/4-constraint-work.yaml
> +      description: Describe how the OSCAL content is used by FedRAMP Reviewers.
Agreed.  There are many potential stakeholders here:
- FedRAMP Reviewers 
- CSPs
- Agencies
- Independent Assessors - not part of the pilot currently but I can see scenarios in the future when dealing with SAP and SAR where this stakeholder group could be involved

2024-10-28 19:05 UTC, brian-ruf commented on .github/ISSUE_TEMPLATE/4-constraint-work.yaml
> +      description: Describe how the OSCAL content is used by FedRAMP Reviewers.
@Rene2mt | @aj-stein-gsa  
The reason I phrased it this way is that all of the required content (whether in Word or OSCAL) is only required because government officials (AOs and former JAB) have deemed the information necessary in order to adjudicate an authorization decision. 

Our work is about automating the review process, thus the content is used _by_ reviewers _for_ stakeholders.

With that clarification, if you still feel strongly about changing the wording from "by reviewers" to "by stakeholders", I'm happy to make the change.

2024-10-28 21:28 UTC, Rene2mt commented on .github/ISSUE_TEMPLATE/4-constraint-work.yaml
> +      description: Describe how the OSCAL content is used by FedRAMP Reviewers.
@brian-ruf The reason I was suggesting "stakeholder" is that the local validation approach we are implementing takes the review burden off of the traditional reviewer (for items that can be automated) and empowers anyone (CSP, etc.) to run the validations and know if their content will meet those specific FedRAMP requirements.  So whether the CSP runs the validation or FedRAMP (reviewers) run them post-submission by CSP, I view the purpose as confirmation that a FedRAMP requirement is being met or not.

Having said that, I don't see this as a blocking change 😃.  I cool with moving forward and if we see a need to update later, we can address then 👍🏾

2024-10-28 21:31 UTC, aj-stein-gsa approved these changes
Sorry I held this up for longer in the day I had planned, I like it from Friday and you addressed all the feedback I was concerned with. The other feedback items are not critical.

(Thanks to @Rene2mt to remind me how tardy I am this late in the afternoon.)

2024-10-28 21:31 UTC, merged