Add ADR-12
GSA/fedramp-automation pull request #830
Opened 2024-10-28 21:43 UTC by brian-ruf

# Committer Notes

Adding ADR -12 as discussed in issue #626 to document prioritization approach and priciples.

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-10-29 12:11 UTC, Gabeblis requested changes
This is a great start! I noticed a few minor grammatical issues and have some suggestions to enhance the ADR.

2024-10-29 13:26 UTC, kyhu65867 submitted a review, later dismissed
I like this a lot, just a few changes to make it stronger :)

2024-10-29 13:26 UTC, kyhu65867 commented on documents/adr/0012-constraint-strategy.md
> +- **Integrity Checks**: Focus on data correlation and consistency checks within the OSCAL content, similar to database referential integrity checks. Some of this can be performed with Metaschema cons
It could be good to include examples for each category here

2024-10-29 13:26 UTC, kyhu65867 commented on documents/adr/0012-constraint-strategy.md
> +## Consequences
I second this. Makes the most sense, but isn't necessarily all good.

2024-10-29 16:41 UTC, aj-stein-gsa commented on documents/adr/0012-constraint-strategy.md
> +The FedRAMP Automation Team requires a consistent mechanism for prioritizing and performing work on FedRAMP constraints. While a larger strategy document was created internally, this ADR documents th
Blocking: I assume people already see this in GitHub, but I do not really want us to emphasize we have internal communications separate from them. I will also state here that, over time, we will want to move away from internal tracking documents, so I would like us to limit 🤞 hopefully historical references to clean up in the future. Otherwise, good stuff.


```suggestion
The FedRAMP Automation Team requires a consistent strategy and methodology for prioritizing and performing work on FedRAMP constraints. This ADR documents the key decisions in how FedRAMP will develop and maintain constraints, in order to provide transparency to stakeholders and guide contributors to this work.  
```

2024-10-29 16:41 UTC, aj-stein-gsa commented on documents/adr/0012-constraint-strategy.md
> +- **Integrity Checks**: Focus on data correlation and consistency checks within the OSCAL content, similar to database referential integrity checks. Some of this can be performed with Metaschema cons
I would like that but it not necessarily urgent, I am fine either way on this one. We definitely should document that elsewhere.

2024-10-29 16:41 UTC, aj-stein-gsa commented on documents/adr/0012-constraint-strategy.md
> +  1. requires human judgement, thus is more suited to a workflow.
Agree to this, also we should capitalize Metaschema.

```suggestion
    1. is fully automatable via Metaschema constraints or other means; or
    1. requires human judgement, thus is more suited to a workflow.
```

2024-11-01 23:07 UTC, brian-ruf commented on documents/adr/0012-constraint-strategy.md
> +## Consequences
Great point! Added a paragraph to address negative consequences.

2024-11-01 23:13 UTC, brian-ruf commented on documents/adr/0012-constraint-strategy.md
> +- **Integrity Checks**: Focus on data correlation and consistency checks within the OSCAL content, similar to database referential integrity checks. Some of this can be performed with Metaschema cons
I added a sentence to each type with examples.

2024-11-01 23:17 UTC, brian-ruf commented on documents/adr/0012-constraint-strategy.md
> +This ADR focuses on Metaschema constraints related to **Completeness Checks** and **Integrity Checks**.
I wanted to define the three tiers first and then make a statement that two of those three tiers are the focus here.

2024-11-01 23:25 UTC, brian-ruf commented
All review comments are addressed and edits have been accepted. There are two comments that were associated with edits, that I can't see how to mark resolved. They are showing as outstanding, even though the actual edits were already accepted.

2024-11-04 13:43 UTC, kyhu65867 approved these changes
This looks great! Thanks!

2024-11-04 15:52 UTC, aj-stein-gsa approved these changes
My final review changes are for cleanup to approve and merge on my end, I am happy with it and can quickly re-review as required because of newer commits.

Nice work.

2024-11-04 15:52 UTC, aj-stein-gsa commented on documents/adr/0012-constraint-strategy.md
> +
I missed this before, can we remove this?

```suggestion
```

2024-11-04 15:52 UTC, aj-stein-gsa commented on documents/adr/0012-constraint-strategy.md
> +Proposed
If we approve this, we are at the moment where we change the date and status. 😄 

```suggestion
# 12. Constraint Prioritization Strategy ADR 
Date: 2024-10-04

## Status

Accepted
```

2024-11-04 16:24 UTC, wandmagic submitted a review, later dismissed

2024-11-04 16:28 UTC, Gabeblis submitted a review, later dismissed
LGTM

2024-11-04 18:17 UTC, merged