Feature constraints style guide
GSA/fedramp-automation pull request #858
Opened 2024-11-01 19:55 UTC by wandmagic

# Committer Notes

Interested in getting this into develop before we take on more constraints

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-11-01 21:08 UTC, aj-stein-gsa reviewed
We need a rebase but this PR looks like a good start.

2024-11-04 12:32 UTC, aj-stein-gsa submitted a review, later dismissed
Sometime today, can you rebase this PR and update the checklist accordingly please? Thanks.

2024-11-04 13:33 UTC, wandmagic commented
> Sometime today, can you rebase this PR and update the checklist accordingly please? Thanks.

rebased ✅

2024-11-04 18:31 UTC, aj-stein-gsa requested changes

2024-11-04 19:24 UTC, Gabeblis commented on features/steps/fedramp_extensions_steps.ts
> +      ]);
We definitely can make 2 and 3 happen. As for 1, I'm not sure if this is pre-existing behavior, but the metaschema `validate` command is not producing any viable sarif. Also, something in the the new release is causing unwanted behavior when running the `validate` command. It isn't catching any errors and I verified that the same exact code works with 2.2, but not 2.3. Were there any significant changes that I'm missing? If not, then we're dealing with another bug.

2024-11-04 19:29 UTC, aj-stein-gsa commented on features/steps/fedramp_extensions_steps.ts
> +      ]);
I will take a look then.

2024-11-04 22:34 UTC, wandmagic commented
ok added make lint, also added use 2.2.0 so we can use the older version until we sort out bugs in 2.3.0

2024-11-05 01:59 UTC, aj-stein-gsa commented on features/steps/fedramp_extensions_steps.ts
> +      ]);
Yeah something is not right here. It seems 2.2.0 works but 2.3.0 is not working I will work that bug report but we should figure that out over time. 

I see @wandmagic worked around that in https://github.com/GSA/fedramp-automation/pull/858/commits/3819f9c50b8e8e12abdf3b0d0eb82243fa6affd5 for now.

2024-11-05 02:12 UTC, aj-stein-gsa requested changes

2024-11-05 02:12 UTC, aj-stein-gsa commented on features/steps/fedramp_extensions_steps.ts
> +      ]);
Now that we have rolled back to 2.2.0, can we please add something like this before final approval? Thanks!

```suggestion
  for (const file_name of constraint_files) {
    const filePath = join(constraintDir, file_name.trim());
    const styleGuideReportPath = join(styleGuideReportsDir, `${parse(filePath).name}.sarif`);
    console.log(filePath);
    try {
      console.log(filePath);
      const [result, error] = await executeOscalCliCommand('metaschema', [
        'validate',
        filePath,
        '-c',
        styleGuidePath,
        '-o',
        styleGuideReportPath,
        '--disable-schema-validation',
      ]);
```

2024-11-05 15:57 UTC, Gabeblis commented on features/steps/fedramp_extensions_steps.ts
> +    console.log(filePath);
I may have left some debug logs in there 🙄 
```suggestion
```

2024-11-05 16:27 UTC, Gabeblis commented on features/steps/fedramp_extensions_steps.ts
> +import {formatSarifOutput} from 'oscal'
After testing locally, the sarif output is not formatted correctly. The text appears as one large block.

2024-11-05 18:13 UTC, wandmagic commented on features/steps/fedramp_extensions_steps.ts
> +import {formatSarifOutput} from 'oscal'
fixed

2024-11-05 18:19 UTC, aj-stein-gsa approved these changes

2024-11-05 22:01 UTC, wandmagic commented
This is ready for review again

2024-11-05 22:10 UTC, aj-stein-gsa approved these changes

2024-11-05 22:15 UTC, aj-stein-gsa commented
Anything I need to know with the help wanted tag?

2024-11-05 22:32 UTC, wandmagic commented
> Anything I need to know with the help wanted tag?

Just help reviewing

2024-11-05 23:42 UTC, Gabeblis approved these changes
Things are about to get REAL

2024-11-06 01:22 UTC, aj-stein-gsa commented
> Things are about to get REAL

This made my evening, thanks to you and the whole crew who made it happen so quickly!

2024-11-06 15:37 UTC, Rene2mt approved these changes
Looks good!!!

2024-11-06 15:38 UTC, merged