Add Diagram Link Validation Constraints
GSA/fedramp-automation pull request #865
Opened 2024-11-05 15:39 UTC by Gabeblis

# Committer Notes
## Purpose
This PR introduces the implementation of three new  `system-characteristics` constraints leveraging the functionality provided by OSCAL-CLI version 2.3. These constraints ensure that all necessary diagram links are properly validated, ensuring all diagrams have valid and accessible `resource` targets in the `back-matter`.

## Changes

Constraint: has-authorization-boundary-diagram-link-href-target
- Ensures that a valid href target is specified for the authorization boundary diagram link.
- Validates the presence and correctness of the link target.

Constraint: has-network-architecture-diagram-link-href-target
- Ensures that a valid href target is specified for the network architecture diagram link.
- Validates the presence and correctness of the link target.

Constraint: has-data-flow-diagram-link-href-target
- Ensures that a valid href target is specified for the data flow diagram link.
- Validates the presence and correctness of the link target.

Tests: 
- Invalid case test files were created for each constraint.
- Pass/fail case yaml files were created for each constraint.

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
~- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?~ Documentation already exists.
- [x] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-11-05 16:17 UTC, aj-stein-gsa commented
Oh I now realize this is an issue, not a PR. I will backport an issue.

2024-11-05 16:20 UTC, Gabeblis commented
> Oh I now realize this is a PR, not an issue. I will backport an issue.

I opened an issue [here](https://github.com/GSA/fedramp-automation/issues/864)

2024-11-05 16:25 UTC, aj-stein-gsa commented
> > Oh I now realize this is a PR, not an issue. I will backport an issue.
> 
> I opened an issue [here](https://github.com/GSA/fedramp-automation/issues/864)

I just realized I was maybe tagging and adding something incorrectly to the board.

2024-11-05 17:15 UTC, aj-stein-gsa requested changes

2024-11-05 17:15 UTC, aj-stein-gsa commented on oscal-cli-sarif-log-78c0b601-f154-4134-851c-cd2ce3857d3a.json
> +{
Blocking can we delete this file?

2024-11-05 17:21 UTC, Gabeblis commented on oscal-cli-sarif-log-78c0b601-f154-4134-851c-cd2ce3857d3a.json
> +{
how did that get there.... 🙄 thanks

2024-11-06 14:05 UTC, aj-stein-gsa requested changes

2024-11-06 14:05 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            </expect>
Blocking: I know we do not (and probably cannot) mandate the resource back matter approach as it as appropriate, but somebody may link to a local file or remote URL (that would be weird, but possible I think depending on authenticated URLs). Can we account for either eventuality?

Point being, it may not always be a back-matter resource, even if that is preferred, you _could link to `<link href="./diagram.png"/>` and the test and fixture data doesn't account for that.

I know this is something that should be better described, we can discuss more if you have questions or concerns.

2024-11-07 14:53 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +            </expect>
Ok, in [87de26c](https://github.com/GSA/fedramp-automation/pull/865/commits/87de26c0769df8a3dc9a784f4e3d5e4a5e067baa) I added a check that allows this test to pass if the `@href` doesn't start with `#`. So it can pass if it links directly in the `@href` or if it starts with `#`, it can pass if there exists a valid resource with the matching `uuid`. Please let me know if this addresses your concerns @aj-stein-gsa

2024-11-07 14:56 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +            </expect>
Also, I couldn't find any documentation that mentions this (`<link href="./diagram.png"/>`) is valid. I'll have to update the automate.fedramp docs to include this

2024-11-07 15:10 UTC, aj-stein-gsa submitted a review, later dismissed
Great work, I like the dev process, tests, and their inline docs. I have minor tweaks and I will reapprove either way. Thanks for taking the time on these.

2024-11-07 15:10 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>A FedRAMP SSP MUST reference a data flow diagram document.</message>
Ditto

```suggestion
                <message>A FedRAMP SSP MUST reference a data flow diagram.</message>
```

2024-11-07 15:10 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>A FedRAMP SSP MUST reference a network architecture diagram document.</message>
Ditto

```suggestion
                <message>A FedRAMP SSP MUST include a network architecture diagram.</message>
```

2024-11-07 15:21 UTC, aj-stein-gsa commented
@Gabeblis can you also go the referenced page in the `help-url` and add an example of the inline link approach (not just a href URI reference to UUID)?

2024-11-07 15:32 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>A FedRAMP SSP MUST reference an authorization boundary diagram document.</message>
That's fair. Thank you for the feedback & suggestion.

2024-11-07 15:42 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            </expect>
Thanks, please do (where did my comment go where I thought I said this? haha). In short I know it is possible because of the underlying Metaschema type and how it gets downconverted into JSON Schema and XML Schema.

2024-11-07 15:43 UTC, aj-stein-gsa submitted a review, later dismissed

2024-11-08 22:28 UTC, wandmagic approved these changes

2024-11-08 22:30 UTC, wandmagic commented
looks good but we really need a function that auto-resolves the hashes, because having so many if thens about the # character is a bit of cognitave overload, can we create functions in metapath and re-use that concept?

also would we want a more general, every resource should have a doc-available?

2024-11-08 23:05 UTC, Gabeblis commented
> looks good but we really need a function that auto-resolves the hashes, because having so many if thens about the # character is a bit of cognitave overload, can we create functions in metapath and re-use that concept?
> 
> also would we want a more general, every resource should have a doc-available?

This is just to check that a valid resource is referenced. It is not checking the actual content. As far as the cognitive overload goes, I'm always down to make things easier, but I'm not too bothered by how it is currently.

2024-11-09 02:18 UTC, david-waltermire commented
> looks good but we really need a function that auto-resolves the hashes, because having so many if thens about the # character is a bit of cognitave overload, can we create functions in metapath and re-use that concept?

The issue https://github.com/metaschema-framework/metaschema-java/issues/242 is about this. This is on my short list of capabilities to add.

2024-11-13 14:29 UTC, aj-stein-gsa approved these changes

2024-11-13 20:42 UTC, Rene2mt approved these changes

2024-11-14 17:53 UTC, wandmagic approved these changes

2024-11-14 17:53 UTC, merged