Add ADR to formally deprecate Spock versioning, formalize Semantic Versioning Use
GSA/fedramp-automation pull request #866
Opened 2024-11-05 20:12 UTC by aj-stein-gsa

# Committer Notes

This is a PR to backport a previously made decision in previous implementer meetings in the Automation Team. We need to complete this as part of #847, along with website documentation, to properly inform the requirements in https://github.com/GSA/fedramp-automation/pull/834.

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-11-06 13:32 UTC, Rene2mt requested changes
@aj-stein-gsa looks good overall.  Just a couple of minor suggestions.

2024-11-06 13:32 UTC, Rene2mt commented on documents/adr/0010-semantic-versions-only.md
> +In the past, the FedRAMP Automation Team [the versioning methodology of the Spock Framework](https://spockframework.org/spock/docs/2.0/known_issues.html#_groovy_version_compatibility). Staff document
Minor edit
```suggestion
In the past, the FedRAMP Automation Team implemented [the versioning methodology of the Spock Framework](https://spockframework.org/spock/docs/2.0/known_issues.html#_groovy_version_compatibility). Staff documented this versioning methodology in [ADR #2](https://github.com/GSA/fedramp-automation/blob/247f99a0e3a2cfa6b9e78dd7c18836cf008115b2/documents/adr/0002-git-release-version-strategy.md). In 2024, the FedRAMP Automation Team received significant positive feedback from the community to transition from this methodology to [Semantic Versioning](https://semver.org/) as part of its release strategy and updated [the automate.fedramp.gov website](https://automate.fedramp.gov/about/release/) accordingly. They also socialized with the community that the update page on the website, not the previous ADR and outdated developer documentation, is the canonical source for the release strategy and other documents.
```

2024-11-06 13:32 UTC, Rene2mt commented on documents/adr/0010-semantic-versions-only.md
> +What becomes easier or more difficult to do because of this change?
```suggestion
What becomes easier or more difficult to do because of this change?
It will be easier for developers to automate handling version updates based on SemVer rules.
```

2024-11-13 02:25 UTC, Rene2mt approved these changes

2024-11-13 14:07 UTC, Gabeblis approved these changes

2024-11-14 03:17 UTC, merged