Remove missed `make` targets and GitHub Action pipelines for Schematron develop
GSA/fedramp-automation pull request #867
Opened 2024-11-06 01:21 UTC by aj-stein-gsa

# Committer Notes

I missed this code and build support tooling. This is a small step towards completing #738.

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?
- ~If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated?~ N/A for this issue, it for team-focused development tooling.

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-11-06 12:41 UTC, Gabeblis submitted a review, later dismissed

2024-11-06 21:27 UTC, wandmagic commented
We still use make test, and i think we should use make build for the content stuff, we just need to remove the build-web part

2024-11-06 21:30 UTC, wandmagic requested changes

2024-11-06 21:30 UTC, wandmagic commented on Makefile
build and test should look like this:

test: build-validations ## Test all

build: init-content test-content build-content  ## Build all artifacts and copy into dist directory

2024-11-06 23:58 UTC, aj-stein-gsa commented on Makefile
Sorry serves me write I was too aggressive yesterday with quick edits.

2024-11-07 02:45 UTC, aj-stein-gsa commented on Makefile
Fixed commit on rebase and pushed, thanks for catching, you know, the one target I could not change. 😆

2024-11-07 02:53 UTC, wandmagic commented on Makefile
```suggestion
build: init-content test-content build-content  ## Build all artifacts and copy into dist directory
```

2024-11-07 03:09 UTC, aj-stein-gsa commented on Makefile
Sigh I am embarassed I waste this much time on this. I actually run these all separately and didn't know we use `build`, all those sub-targets are defined in the other module and I have never seen someone mention using these in chat, but you did now saw it three times, so there's that!

2024-11-07 12:48 UTC, wandmagic approved these changes

2024-11-07 12:56 UTC, Gabeblis approved these changes

2024-11-12 22:27 UTC, merged