Add `Prepared For` Constraints
GSA/fedramp-automation pull request #869
Opened 2024-11-06 05:14 UTC by Gabeblis

# Committer Notes
## Purpose
This PR introduces three constraints aimed at ensuring FedRAMP compliance for the digital authorization package by verifying the `prepared-for` roles/parties. These constraints ensure that all required elements are present and that necessary information is accurately documented.

## Changes
Constraint: `role-defined-prepared-for`
- Validates that there is a defined role with the ID "prepared-for".

Constraint: `responsible-party-prepared-for`
- Ensures that a responsible party is assigned to the prepared-for role.
 
Constraint: `responsible-party-prepared-for-location-valid`
- Validates that the party assigned to the prepared-for role includes a location-uuid with the required address details.

Tests
- Added invalid test data files for all three constraints.
- Added pass/fail YAML files for the three constraints to verify their functionality.
- Updated ssp-all-VALID.xml to contain the required information so that the constraints fire and pass as expected.

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [x] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-11-06 15:29 UTC, aj-stein-gsa requested changes
Can you address the updated AC requirements in the issue? Sorry again.

2024-11-06 17:03 UTC, Gabeblis commented
> Can you address the updated AC requirements in the issue? Sorry again.

Resolved here: [045e70e](https://github.com/GSA/fedramp-automation/pull/869/commits/045e70ef3055c9c1b1620d783b73690a05747714). I added the check for an embedded address assembly in the party and I added another `-VALID.xml` test file in order to validate both scenarios.

2024-11-06 19:46 UTC, wandmagic submitted a review, later dismissed

2024-11-07 03:03 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/general-concepts/4-expressing-common-fedramp-templat
Blocking: I am kind of intrigued. How can this work if the booleans `and`s connect all the expressions and not an `or` if you can have a location UUID, an address inside the party, but not both?

2024-11-07 04:18 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/general-concepts/4-expressing-common-fedramp-templat
I'm a little confused by what you're asking. How the expression works is it checks if either a full address is embedded in the party or if it references a location assembly, then check if that has a full address. If both don't exist, or are incomplete, it will return false. If either one exists and is complete, it returns true. This is verified by the invalid test data files and the valid ones. I could make an invalid test file for each scenario, but that would require like 10 extra invalid test files. I manually checked each missing field, and if one missing field causes the expression to return false, then we can assume that more missing fields would also return false. Currently, it allows for both to exist. I could be more specific and say if one exists, then don't allow the other and vice versa.

2024-11-07 04:28 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/general-concepts/4-expressing-common-fedramp-templat
Sorry I address above, but you understood perfectly!

2024-11-07 04:29 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="responsible-party-prepared-for-location-valid" target="." test="$prepared-for-party/address[@type='work'] and $prepared-for-party/address/addr-line and $prepared-for-party/add
OK you understood perfectly, I just assumed the precedent of `and`/`or` needs some parens. If it doesn't, it seems kind of unreadable to me.

```suggestion
            <expect id="responsible-party-prepared-for-location-valid" target="." test="($prepared-for-party/address[@type='work'] and $prepared-for-party/address/addr-line and $prepared-for-party/address/city and $prepared-for-party/address/state and $prepared-for-party/address/postal-code) or ($prepared-for-location/address[@type='work'] and $prepared-for-location/address/addr-line and $prepared-for-location/address/city and $prepared-for-location/address/state and $prepared-for-location/address/postal-code)" level="WARNING">
```

2024-11-07 04:29 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/general-concepts/4-expressing-common-fedramp-templat
Resolving this one to put the suggestion where I meant it.

2024-11-07 04:50 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="responsible-party-prepared-for-location-valid" target="." test="$prepared-for-party/address[@type='work'] and $prepared-for-party/address/addr-line and $prepared-for-party/add
I mean your good, I don't the PEMDAS properties of XPath 3.1 or Metapath that well, so I wanted to look into this.

2024-11-07 04:52 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="responsible-party-prepared-for-location-valid" target="." test="$prepared-for-party/address[@type='work'] and $prepared-for-party/address/addr-line and $prepared-for-party/add
`and` takes a higher precedence over `or` so both expressions work the same. Definitely easier to read with parenthesis though

2024-11-07 05:04 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="responsible-party-prepared-for-location-valid" target="." test="$prepared-for-party/address[@type='work'] and $prepared-for-party/address/addr-line and $prepared-for-party/add
Resolved: [eceab1a](https://github.com/GSA/fedramp-automation/pull/869/commits/eceab1af055db024d11796008301b1c1d84605c0)

2024-11-12 14:39 UTC, wandmagic submitted a review, later dismissed

2024-11-12 19:47 UTC, kyhu65867 submitted a review, later dismissed
tweaks to message clarity

2024-11-12 19:47 UTC, kyhu65867 commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>A FedRAMP SSP MUST have a responsible party for who the document was prepared for, and that party MUST define an address.</message>
Since this is a separate constraint, I don't think I would repeat the responsible party prepared for option, and instead have the message just say "A FedRAMP SSP MUST define the address of the responsible party for whom the document was prepared. "

2024-11-12 19:47 UTC, kyhu65867 commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>A FedRAMP SSP MUST have a responsible party that defines the party that the document was prepared for.</message>
Change message slightly to "A FedRAMP SSP MUST have a responsible party that defines the party for whom the document was prepared." (better grammar)

2024-11-12 22:25 UTC, aj-stein-gsa submitted a review, later dismissed

2024-11-12 22:27 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>A FedRAMP SSP MUST have a responsible party that defines the party that the document was prepared for.</message>
I do not disagree, I just felt the more formal, rigid grammatical style feels a little off from the more approachable, plain language style. I agree it is more casual and repetitive with the redundant "thats," but I defer to team opinion here, not just AJ.

2024-11-13 13:55 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>A FedRAMP SSP MUST have a responsible party for who the document was prepared for, and that party MUST define an address.</message>
Resolved: [c67e133](https://github.com/GSA/fedramp-automation/pull/869/commits/c67e1333ab12b1110fe723425468175258eb0ac2)

2024-11-13 13:56 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>A FedRAMP SSP MUST have a responsible party that defines the party that the document was prepared for.</message>
I don't mind the change. Resolved: Resolved: [c67e133](https://github.com/GSA/fedramp-automation/pull/869/commits/c67e1333ab12b1110fe723425468175258eb0ac2)

2024-11-13 14:17 UTC, aj-stein-gsa submitted a review, later dismissed

2024-11-13 14:17 UTC, aj-stein-gsa commented
@Gabeblis sorry to be that person, but can you rebase?

2024-11-13 16:00 UTC, wandmagic approved these changes

2024-11-14 03:16 UTC, aj-stein-gsa approved these changes

2024-11-14 15:00 UTC, Rene2mt approved these changes

2024-11-14 17:51 UTC, merged