Add has-marking
GSA/fedramp-automation pull request #875
Opened 2024-11-06 15:50 UTC by DimitriZhurkin

# Committer Notes

1. Add the `has-marking` constraint to check the existence of the `<prop name="marking" value="cui"/>` metadata prop.
2. Add the allowed value for the `marking` metadata prop.
3. Add the `marking` metadata prop to `ssp-all-VALID.xml` file.
4. Add pass and fail unit test.

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-11-06 15:51 UTC, DimitriZhurkin commented
Issue https://github.com/GSA/fedramp-automation/issues/836.

2024-11-06 19:09 UTC, aj-stein-gsa commented
@DimitriZhurkin why did you close this PR?

2024-11-06 19:49 UTC, wandmagic submitted a review, later dismissed
looks good to me, just rebase before merging

2024-11-06 19:52 UTC, DimitriZhurkin commented
I did rebase my local repo. I also did hard reset, just in case.

2024-11-06 20:45 UTC, DimitriZhurkin commented
Paul,

How do I remove the erroneously generated `marking` constraint from `fedramp_extensions.feature`? That entry crashes the workflows for this PR.

I tried removing `marking` from `fedramp_extensions.feature` manually, but VS Code threw the following error:
```Can't push refs to remote. Try running "Pull" first to integrate your changes.```

When I push, I'm getting the following message:
```Already up to date.```

2024-11-06 20:49 UTC, aj-stein-gsa requested changes

2024-11-06 20:49 UTC, aj-stein-gsa commented on features/fedramp_extensions.feature
> +  | marking |
@DimitriZhurkin re your question, just commit this suggestion button below please and the tests will re-run.

```suggestion
```

2024-11-06 21:06 UTC, DimitriZhurkin commented
Still the same workflow run error:
```
Ensuring full test coverage for "marking": OSCAL Document Constraints
Constraint marking has no tests
AssertionError: Constraint marking has no tests
```

2024-11-06 21:13 UTC, aj-stein-gsa requested changes

2024-11-06 21:13 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +        	<allowed-values id="marking" target="metadata/prop[@name='marking']/@value" allow-other="yes" level="ERROR">
Woops I missed this, the test coverage is failing because the ID is not covered because it is not being tested. I am sorry I missed this.

You need a separate test configuration for YAML files I completely missed this. So OK, I am sorry:

- Add back `| marking |` to fedramp_extensions.feature, sorry about that.
- Add a `unit-test/marking-FAIL.yaml` to cover the allowed value control.
- Add a `unit-test/marking-FAIL.yaml` to cover the allowed value control.

That is why it failed, they are similar but on the expect constraint is checked, not allowed-values. I too got confused on it myself, so I did a double take. Apologies.

2024-11-06 22:04 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +        	<allowed-values id="marking" target="metadata/prop[@name='marking']/@value" allow-other="yes" level="ERROR">
Added `marking-FAIL.yaml` and `marking-PASS.yaml` unit tests.

When I try pushing them to my fork, VS Code throws the same error:
```
Can't push refs to remote. Try running "Pull" first to integrate your changes.
```

2024-11-07 03:16 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +        	<allowed-values id="marking" target="metadata/prop[@name='marking']/@value" allow-other="yes" level="ERROR">
You have to do `git pull -r origin add-has-marking` to make sure recommendations applied in GitHub get back to your local client. I can help here.

2024-11-07 03:38 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +        	<allowed-values id="marking" target="metadata/prop[@name='marking']/@value" allow-other="yes" level="ERROR">
OK actually, disregard this advice, let's talking in the morning I made a series of mistakes in the criteria for this issue as well.

2024-11-07 03:40 UTC, aj-stein-gsa requested changes

2024-11-07 03:40 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +        	</allowed-values>
Blocking: please delete this and only test the `has-marking` constraint. I am updating the criteria because I did not realize that reusing an upstream `allowed-values/@enum` with `allow-other="yes"` means I gave you a contradictory, not implementable requirement, apologies for that.

2024-11-07 04:21 UTC, aj-stein-gsa requested changes
I have a minor wording nit, but I am happy this. I would

2024-11-07 04:21 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/general-concepts/4-expressing-common-fedramp-templat
Can you please create a PR and link it back to #836 in the GSA/automate.fedramp.gov and do the following:

1. Update the sections in [this page](https://automate.fedramp.gov/documentation/general-concepts/4-expressing-common-fedramp-template-elements-in-oscal/) to replace `<prop name="marking" value="Controlled Unclassified Information"/>` to `<prop name="marking" value="cui"/>` per this PR?
2. Add to [this page, in a new section called Metadata, above System Information](https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#system-information), an update that specifically says the SSP requires the prop? The content and change in 1 is generic.

2024-11-07 14:17 UTC, Rene2mt requested changes
PR looks good, but waiting for suggestions to be merged and the documentation PR to be updated, then I'll approve

2024-11-07 14:21 UTC, aj-stein-gsa commented
Oh and @DimitriZhurkin when you find this PR I clean up things because I misled led you. Locally on your computer if you want to make changes a

```
# I am not sure you are still on this branch right now, but just to make sure
git checkout add-has-marking
git fetch origin
git stash
git reset --hard origin/add-has-marking
```

2024-11-08 17:22 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/general-concepts/4-expressing-common-fedramp-templat
@aj-stein-gsa,

Since the `marking` prop is universal across all documents, not just SSP, I feel that we only need item 1.

What do you think?

2024-11-08 17:53 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/general-concepts/4-expressing-common-fedramp-templat
Created documentation PR https://github.com/GSA/automate.fedramp.gov/pull/110.

2024-11-08 18:51 UTC, kyhu65867 approved these changes
This looks good to me. Nice work!

2024-11-09 22:28 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/general-concepts/4-expressing-common-fedramp-templat
(Sigh I saw I never sent this on Friday after all, it was left in the buffer in a browser tab over the evening.)

I understand, @DimitriZhurkin , but I would like a clear example of it in the SSP near the top so people we are requiring it re 2. There will be others we need to add there as well coming up.

2024-11-12 14:36 UTC, DimitriZhurkin commented
> PR looks good, but waiting for suggestions to be merged and the documentation PR to be updated, then I'll approve

Documentation created (https://github.com/GSA/automate.fedramp.gov/pull/110).

2024-11-12 14:38 UTC, DimitriZhurkin commented
> I have a minor wording nit, but I am happy this. I would

Wording changes implemented.

2024-11-12 23:01 UTC, aj-stein-gsa approved these changes

2024-11-13 02:16 UTC, Rene2mt approved these changes

2024-11-13 03:53 UTC, merged