Feature/party name
GSA/fedramp-automation pull request #878
Opened 2024-11-07 15:48 UTC by wandmagic

# Committer Notes

add party has name constraint 

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-11-07 15:48 UTC, wandmagic commented
[#874](https://github.com/orgs/GSA/projects/25/views/11?pane=issue&itemId=86212404&issue=GSA%7Cfedramp-automation%7C874)

2024-11-07 19:12 UTC, Rene2mt submitted a review, later dismissed

2024-11-07 21:43 UTC, aj-stein-gsa approved these changes

2024-11-08 02:08 UTC, Gabeblis requested changes
The constraint looks good. Just some changes for consistency.

2024-11-08 02:08 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <formal-name>all Parties of MUST have a name.</formal-name>
Just a suggestion here.  I think it'd be better if the formal name was more like a title, and not formatted like a message. 
```suggestion
                <formal-name>All Parties Have a Name</formal-name>
```

2024-11-08 02:08 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Each Party assembly MUST have a name</message>
Minor change for consistency. 
```suggestion
                <message>Each Party assembly MUST have a name.</message>
```

2024-11-08 02:08 UTC, Gabeblis commented on src/validations/styleguides/fedramp-constraint-style.xml
> +            </expect>
Are we able to leave this commented out until it is actually implemented? I think it would be better to either have it commented out or fully implemented. Right now this test does nothing.

2024-11-08 14:46 UTC, Gabeblis requested changes
Whichever way we go with the constraint id, it should be consistent throughout all the file names so that it is future-proof and easier to maintain. After this is addressed, I'm ready to approve this PR 😄

2024-11-08 14:46 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="party-name" target="." test="exists(name)" level="ERROR">
I'd rather this `id` be `party-has-name` both for consistency with the other file names related to this constraint, and because it matches the way we've been naming existence check constraints like this thus far. If we keep it as `party-name`, then I'd recommend changing the unit test and content file names to match the id so that we avoid any potential issues in the future.
```suggestion
            <expect id="party-has-name" target="." test="exists(name)" level="ERROR">
```

2024-11-08 14:46 UTC, Gabeblis commented on src/validations/constraints/content/ssp-party-has-name-INVALID.xml
> +    <address type="work"  />
minor indentation needed
```suggestion
    <party uuid="22222222-0000-4000-9000-000000000002" type="person">
      <email-address>jane.doe@example.com</email-address>
      <address type="work"  />
```

2024-11-08 14:46 UTC, Gabeblis commented on src/validations/constraints/unit-tests/party-has-name-FAIL.yaml
> +    - constraint-id: party-name
In case you go the route of changing the constraint id
```suggestion
    - constraint-id: party-has-name
```

2024-11-08 14:46 UTC, Gabeblis commented on src/validations/constraints/unit-tests/party-has-name-PASS.yaml
> +    - constraint-id: party-name
In case you go the route of changing the constraint id
```suggestion
    - constraint-id: party-has-name
```

2024-11-08 15:12 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="party-name" target="." test="exists(name)" level="ERROR">
I too am cool with this.

2024-11-08 15:29 UTC, Rene2mt reviewed
@wandmagic constraint runs as expected.  Nice work. Once you rename it I'll approve.

2024-11-08 16:14 UTC, Gabeblis approved these changes
LGTM

2024-11-12 18:43 UTC, Rene2mt submitted a review, later dismissed
Look good 👍🏾

2024-11-12 18:45 UTC, aj-stein-gsa requested changes

2024-11-12 18:51 UTC, aj-stein-gsa approved these changes

2024-11-12 19:05 UTC, DimitriZhurkin approved these changes

2024-11-12 19:07 UTC, merged