Feature/implemented requirements
GSA/fedramp-automation pull request #883
Opened 2024-11-07 20:31 UTC by wandmagic

# Committer Notes

Introduce implemented requirement constraints, also refactor profile constraints to handle edge cases more cleanly

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [x] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-11-08 20:26 UTC, kyhu65867 requested changes

2024-11-08 20:26 UTC, kyhu65867 commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <description>This SSP includes extraneous controls that are not part of the FedRAMP baseline.</description>
If this is an error, it should say what should/ must be done in the format "A FedRAMP SSP MUST NOT include extraneous controls outside of the FedRAMP baseline" (although the questioner in me wonders why we care if people go above and beyond but that is a question for another day)

2024-11-12 14:25 UTC, wandmagic commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <description>This SSP includes extraneous controls that are not part of the FedRAMP baseline.</description>
fixed

2024-11-14 18:00 UTC, closed without merging

2024-11-14 18:01 UTC, wandmagic commented
closing because this is getting stale, so just assign this back to me if we actually want to get these constraints across the board.