833 oscal version constraint
GSA/fedramp-automation pull request #884
Opened 2024-11-07 22:10 UTC by kyhu65867

# Committer Notes

{Please provide a description of what this PR accomplishes. Be sure to reference any issues addressed. If the PR is a work-in-progress submitted for early review, please submit the PR as a draft PR using the "Draft pull request" dropdown.}

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-11-08 23:59 UTC, aj-stein-gsa commented
@kyhu65867 I beefed it up and think it works before I mark it anymore complicated. Let me know what you think, especially the tests. I may have to abstain from review, but hope our colleagues roast me and show you that no one is sacred during review. 😄

2024-11-09 00:00 UTC, aj-stein-gsa commented
I add myself not just because I contributed but I want honest feedback and review from others since I did my fair share on this one, I should have to defend it with Kylie.

2024-11-18 19:47 UTC, Gabeblis requested changes
I think this is a good start. My biggest issue with this is the FedRAMP versions. Right now we have only 1 version with its minimum required OSCAL version hardcoded. Are there different versions? If not, we could simplify this constraint a lot. Simply changing the FedRAMP version at all breaks this constraint.

2024-11-18 19:47 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                test="$major-version-valid and $minor-version-valid and $patch-version-valid">
Cleanup `expect` constraint attributes order
```suggestion
            <expect id="oscal-version-matches-fedramp-version" target="oscal-version" test="$major-version-valid and $minor-version-valid and $patch-version-valid" level="ERROR">
```

2024-11-18 19:47 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://docs.oasis-open.org/sarif/sarif/v2.1.0"/>
Add help-url with related documentation 
```suggestion
                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/general-concepts/oscal-file-concepts/#oscal-syntax-version"/>                
```

2024-11-18 19:47 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                    then map:get($fedramp-minimum-oscal-versions, $preferred-version)
We already have a constraint that checks and requires the existence of the `fedramp-version` prop. I am not sure adding a default value in the case of the missing prop is what we want to do here.

2024-11-18 19:47 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <let var="fedramp-minimum-oscal-versions" expression="map{'3.0.0-rc1': '1.1.2'}"/>
This map approach would be good in the case of multiple FedRAMP versions that use different versions of OSCAL. The only thing is that this logic isn't dynamic. We would have to come back and add new versions to the map. However, if this is the only possible FedRAMP version (3.0.0) and it corresponds to OSCAL version (1.1.2), then we don't even need this. I think I need some more explanation of what the goal is here.

2024-11-18 20:01 UTC, aj-stein-gsa commented on src/validations/constraints/unit-tests/oscal-version-matches-fedramp-version-FAIL.yaml
> +    This test case validates the behavior of constraint import-profile-has-available-document.
I am sorry that I made this oversight, I shall fix.

2024-11-18 20:18 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://docs.oasis-open.org/sarif/sarif/v2.1.0"/>
Embarrassing, yes, I will fix!

2024-11-18 20:18 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                    then map:get($fedramp-minimum-oscal-versions, $preferred-version)
If not you will get null point exceptions when you dereference other elements, so I was curious how others would consider appropriate for the balancing act. I appreciate the feedback.

2024-11-18 20:21 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                test="$major-version-valid and $minor-version-valid and $patch-version-valid">
We are also missing the formal name for this constraint

2024-11-18 20:22 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <let var="fedramp-minimum-oscal-versions" expression="map{'3.0.0-rc1': '1.1.2'}"/>
The goal would be, as we have different versions published with the new constraint architecture, we would add to the map list. I have no expectation it would be useful with a single entry in the map. That said, without the embedded OSCAL version per the ADR 10 deprecating ADR 2, I am not really sure we have a better way and there is quite likely going to be in the next few months at least one, if not two or more, minimally required version bumps as we move versions in release candidates and final versions. We will not retroactively "go back" and patch up RCs and old versions we do not plan on people using. That would be counterproductive.

So, @Gabeblis:

1. Does this explanation help justify the design, even if suboptimal?
2. Do I need to add a better explanation in the the remarks of the constraint, perhaps, to explain this approach?


To be clear, in #847 I plan for us to update this constraint right, as specified in the SOP in the wiki for releases, before we tag new RCs and final versions to warn others how they slide up the version of FedRAMP requirements and underlying OSCAL requirements will go hand in hand.

2024-11-18 20:24 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                test="$major-version-valid and $minor-version-valid and $patch-version-valid">
Yeah, sadly working on ths constraint led to #905 and why I confirmed with @wandmagic something is wonky with oscal-cli 2.3.1 and the constraint of constraint behavior with the `oscal-cli metaschema validate-content -m -c ...` command.

2024-11-18 20:37 UTC, wandmagic commented on src/validations/constraints/fedramp-external-constraints.xml
> +                test="$major-version-valid and $minor-version-valid and $patch-version-valid">
i think it has something to do with the changes intoduced in metaschema 2.0.0

2024-11-18 20:42 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                    then map:get($fedramp-minimum-oscal-versions, $preferred-version)
The first thing that comes to mind is creating a let expression that checks for the existence of the prop. If it doesn't exist, assign some null value. Add that check as part of the other let expressions: if (true) then do something... else null value. Then in the constraint test just check that the value isn't null and all the other conditions are still truthy

2024-11-18 21:34 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                    then map:get($fedramp-minimum-oscal-versions, $preferred-version)
OK, I can keep that in mind.

2024-11-18 22:09 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <let var="fedramp-minimum-oscal-versions" expression="map{'3.0.0-rc1': '1.1.2'}"/>
Yes, this explanation helped. No, I don't think it needs a remark. I think the message does a good job of explaining what is required.

2024-11-19 06:38 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                test="$major-version-valid and $minor-version-valid and $patch-version-valid">
> We are also missing the formal name for this constraint

Rebasing was a doosie for me with this one, but fixed in https://github.com/GSA/fedramp-automation/pull/884/commits/92f9ad3f6f9c9ddc05e4e1e132c8e0a5876b3fe9.

2024-11-19 12:17 UTC, wandmagic approved these changes

2024-11-19 13:39 UTC, Gabeblis requested changes

2024-11-19 13:39 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>A FedRAMP document SHOULD have an OSCAL version that matches the minimally required version for FedRAMP packages ({$fedramp-required-minimum-version} not {.}).</message>
If this constraint is an error and the minimum compatible version is required, I think it would be better to use the word `MUST`.
```suggestion
                <message>A FedRAMP document MUST have an OSCAL version that matches the minimally required version for FedRAMP packages ({$fedramp-required-minimum-version} not {.}).</message>
```

2024-11-19 13:39 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                    then map:get($fedramp-minimum-oscal-versions, $preferred-version)
One more thing about the current implementation is that in the case that no FedRAMP version is included, it incorrectly results in a pass because of the way it defaults to a certain value.

2024-11-19 14:11 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                    then map:get($fedramp-minimum-oscal-versions, $preferred-version)
Apologies. It just hit me that I forgot to mention that yesterday is all 🤕

2025-03-20 13:30 UTC, closed without merging

2025-03-20 13:31 UTC, aj-stein-gsa commented
Ironically, so late in the game, I am going to work on this issue, but start over the PR.