Is unique inventory assets
GSA/fedramp-automation pull request #887
Opened 2024-11-12 14:21 UTC by wandmagic

# Committer Notes

add is unique check for inventory assets

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-11-12 17:35 UTC, aj-stein-gsa reviewed
So this constraint and its tests are passing because we filter out the relevant upstream constraint (see https://github.com/usnistgov/OSCAL/blob/4f02dac6f698efda387cc5f55bc99581eaf494b6/src/metaschema/oscal_implementation-common_metaschema.xml#L530) referenced by ~usnistgov/OSCAL#2043 and removed in usnistgov/OSCAL#2044~ usnistgov/OSCAL#2064 is filtered out of test result analysis logic, correct @wandmagic?

2024-11-12 17:37 UTC, wandmagic commented
Where is #2044 ?

2024-11-12 17:57 UTC, aj-stein-gsa commented
> Where is #2044 ?

Updated, usnistgov/OSCAL#2044. See above, apologies. I edited after the first submission.

2024-11-13 04:27 UTC, Rene2mt requested changes
The constraint is good, just need to update the help-url and associated documentation.

2024-11-13 04:27 UTC, Rene2mt commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#asset-id"/>
Recommend using this link instead, and in a separate documentation PR, adding asset-id documentation on that page.

```suggestion
                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/5-attachments/#system-inventory-approach"/>
```

2024-11-14 18:03 UTC, Gabeblis requested changes
Looks good! Willing to approve after my suggestion is resolved.

2024-11-14 18:03 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                    <p>Asset IDs must be unique across all inventory items to ensure proper identification and tracking of system components.</p>
Small change to comply with the style guide (frr112)
```suggestion
                    <p>Asset IDs MUST be unique across all inventory items to ensure proper identification and tracking of system components.</p>
```

2024-11-14 18:03 UTC, Gabeblis commented on src/validations/constraints/unit-tests/unique-inventory-item-asset-id-FAIL.yaml
> +        type: "exact"
Non-blocking: This is cool. I noticed without this we get mixed results and it doesn't fail properly.

2024-11-14 18:37 UTC, Gabeblis submitted a review, later dismissed

2024-11-15 02:07 UTC, aj-stein-gsa submitted a review, later dismissed

2024-11-15 02:07 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                    <p>Asset IDs MUST be unique across all inventory items to ensure proper identification and tracking of system components.</p>
```suggestion
                    <p>A FedRAMP SSP's inventory item MUST Have an Asset ID across that is unique across all inventory items in the system and its components.</p>
```

2024-11-15 02:07 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-unique-inventory-item-asset-id-INVALID.xml
> +        <prop name="asset-id" value="DB-001" ns="http://csrc.nist.gov/ns/oscal"/>
Do we need the explicit `@ns` for the default value? I have not ever seen us include this in tests.

```suggestion
        <prop name="asset-id" value="DB-001"/>
```

2024-11-15 02:07 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-unique-inventory-item-asset-id-INVALID.xml
> +      <prop name="asset-id" value="DB-001" ns="http://csrc.nist.gov/ns/oscal"/>
Ditto

```suggestion
      <prop name="asset-id" value="DB-001" />
```

2024-11-15 02:07 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-unique-inventory-item-asset-id-INVALID.xml
> +        <prop name="asset-id" value="DB-001" ns="http://csrc.nist.gov/ns/oscal"/>
Ditto
```suggestion
        <prop name="asset-id" value="DB-001" />
```

2024-11-15 02:07 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-unique-inventory-item-asset-id-INVALID.xml
> +    </component>
I appreciate the detail of this test, but does this not include far more data than required just to successfully test a constraint violation and error message?

```suggestion
```

2024-11-18 17:09 UTC, Gabeblis approved these changes

2024-11-18 17:34 UTC, aj-stein-gsa approved these changes

2024-11-18 17:34 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                    <p>A FedRAMP SSP's inventory item MUST Have an Asset ID across that is unique across all inventory items in the system and its components.</p>
I am sorry to do this, but I have a sneaking suspicion the wording here is based on a previous suggestion from me that is a little odd, so I will approve and it can be fixed so I reapprove. I sense busy AJ style will always have grammar issues.

```suggestion
                    <p>A FedRAMP SSP's inventory item MUST Have an Asset ID unique across all inventory items in the system and its components.</p>
```

2024-11-18 17:46 UTC, aj-stein-gsa approved these changes

2024-11-18 17:46 UTC, Gabeblis approved these changes

2024-11-18 21:05 UTC, Rene2mt approved these changes

2024-11-18 21:24 UTC, merged