Feature/all valid test
GSA/fedramp-automation pull request #896
Opened 2024-11-13 15:23 UTC by wandmagic

# Committer Notes

Provides an extra test for all valid documents which we can add to. IE fedramp tamples awesome cloud etc...

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-11-14 03:14 UTC, aj-stein-gsa requested changes

2024-11-14 03:14 UTC, aj-stein-gsa commented on features/fedramp_extensions.feature
> +@style-guide
Blocking: this tag does not seem to be appropriate for a test collection that is more akin to integration testing, no?

```suggestion
@integration
```

2024-11-14 03:14 UTC, aj-stein-gsa commented on package.json
> +    "oscal": "2.0.6",
Non-blocking: OK for now, but in the future, please allow for dependabot or separate out version bumps.

2024-11-14 03:14 UTC, aj-stein-gsa commented on src/validations/module.mk
> +OSCAL_CLI = npx oscal@next
Blocking: I accidentally took care of this in #901 per https://github.com/GSA/fedramp-automation/pull/901#issuecomment-2474788805. That was unintentional and I will have to lock myself down to prevent such mistakes as well, but I want this pinned. We will need to determine a matrix strategy in CI/CD to try the current pinned release and `oscal@next` in parallel to do some early warning testing as you are aiming for here.

```suggestion
OSCAL_CLI = npx oscal@2.0.6
```

2024-11-14 14:17 UTC, aj-stein-gsa submitted a review, later dismissed

2024-11-14 14:17 UTC, aj-stein-gsa commented on package.json
>      "inquirer": "^10.1.8",
Non-blocking: this is a general comment because I cannot comment on file-level stuff, thanks GitHub reviews. Do we want to add a specific `npm run` target for integration tests here and in build for local debugging to get quickly through "valid content tests" when debugging? I say non-blocking because I may be the only person in the group that uses that so often.

2024-11-14 15:01 UTC, aj-stein-gsa approved these changes

2024-11-14 20:47 UTC, Gabeblis requested changes

2024-11-14 20:47 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Every FedRAMP document must define a party with a name.</message>
Was this change intended? It goes against the style guide.
```suggestion
                <message>Every FedRAMP document MUST define a party with a name.</message>
```

2024-11-14 20:47 UTC, Gabeblis commented on src/validations/constraints/content/ssp-all-VALID.xml
> +      </address>
What was the reason behind these changes? Specifically removing the `party` and `location` that were added for the `prepared-by` constraints. The constraint still works, but it isn't being fully tested as intended.

2024-11-14 21:56 UTC, wandmagic commented on src/validations/constraints/content/ssp-all-VALID.xml
> +      </address>
before your latest stuff was merged in, i had to fix some things in ssp-all valid for this test to pass.
now that i've rebased i only had to add one role, so we are good now

2024-11-15 01:56 UTC, aj-stein-gsa requested changes
Can you please rebase and not merge commits? They will block changes on feature branches.

2024-11-15 15:29 UTC, aj-stein-gsa approved these changes

2024-11-18 16:03 UTC, Gabeblis commented on features/steps/fedramp_extensions_steps.ts
> +let quiet= false
I am having some difficulty understanding why quiet is being used. It isn't updated anywhere, so I'm not sure if there is any benefit to adding `!quiet &&` to all the logging. I just want to understand how this works so I can provide some actual meaningful feedback.

2024-11-18 16:58 UTC, wandmagic commented on features/steps/fedramp_extensions_steps.ts
> +let quiet= false
added env variable to toggle quiet param

2024-11-18 17:05 UTC, Gabeblis commented on features/steps/fedramp_extensions_steps.ts
> +let quiet= false
That makes sense. Thanks for the explanation.

2024-11-18 17:05 UTC, Gabeblis submitted a review, later dismissed

2024-11-18 21:35 UTC, aj-stein-gsa approved these changes

2024-11-18 21:35 UTC, aj-stein-gsa commented
I am sorry to do this to you, but if you want we can hold for the third approval and then we can rebase and merge after that, @wandmagic.

2024-11-19 16:40 UTC, Rene2mt submitted a review, later dismissed

2024-11-19 17:24 UTC, wandmagic commented
> I am sorry to do this to you, but if you want we can hold for the third approval and then we can rebase and merge after that, @wandmagic.

looks like rebasing dismissed the reviews

2024-11-19 18:23 UTC, Gabeblis approved these changes

2024-11-19 22:07 UTC, aj-stein-gsa approved these changes

2024-11-20 15:15 UTC, merged