Add has-inventory-items
GSA/fedramp-automation pull request #899
Opened 2024-11-13 16:53 UTC by DimitriZhurkin

# Committer Notes

1. Add the `has-inventory-items` constraint, which checks that a FedRAMP SSP contains two or more inventory items.
2. In the `ssp-all-VALID.xml` file, add the second `<inventory-item>` node to make the SSP valid.

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-11-13 17:36 UTC, DimitriZhurkin commented
Related issue #881.

2024-11-14 17:54 UTC, wandmagic approved these changes

2024-11-14 18:33 UTC, Gabeblis requested changes
This is good work, just requires some small tweaks to meet the requirements per issue #881 and fixing the `.feature` file.

2024-11-14 18:33 UTC, Gabeblis commented on features/fedramp_extensions.feature
> -  | has-published-date |
Not sure why these constraints (`has-published-date`, `responsible-party-prepared-by`, `responsible-party-prepared-by-location-valid`, `role-defined-prepared-by`) were deleted from the feature file. Are you able to run `make test` and commit the changes to the feature file so that these get added back.

2024-11-14 18:33 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +			<expect id="has-inventory-items" target="." test="count(inventory-item) >= 2" level="ERROR">
Issue #881 proposed that this constraint should check if there is at least 1 inventory item. Is there a reason that we are checking for at least 2?

2024-11-14 18:33 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +			<expect id="has-inventory-items" target="." test="count(inventory-item) >= 2" level="ERROR">
Correction to check for at least 1 inventory item.
```suggestion
			<expect id="has-inventory-items" target="." test="count(inventory-item) >= 1" level="ERROR">
```

2024-11-14 18:33 UTC, Gabeblis commented on src/validations/constraints/unit-tests/has-inventory-items-FAIL.yaml
> +  description: Test that the FedRAMP SSP contains only one inventory item.
Change to align with the suggested test of `>=1`.
```suggestion
  description: Test that the FedRAMP SSP does not contain at least one inventory item.
```

2024-11-14 18:33 UTC, Gabeblis commented on src/validations/constraints/unit-tests/has-inventory-items-PASS.yaml
> +  description: Test that the FedRAMP SSP contains the two or more inventory items.
Change to align with the suggested test of `>=1`.
```suggestion
  description: Test that the FedRAMP SSP contains at least one inventory item.
```

2024-11-14 21:53 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +			<expect id="has-inventory-items" target="." test="count(inventory-item) >= 2" level="ERROR">
According to Brian, "FedRAMP requires at least two instances of a system":
https://github.com/GSA/fedramp-automation/issues/881#issuecomment-2468770799

2024-11-14 21:54 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +			<expect id="has-inventory-items" target="." test="count(inventory-item) >= 2" level="ERROR">
Ditto.

2024-11-14 21:54 UTC, DimitriZhurkin commented on src/validations/constraints/unit-tests/has-inventory-items-FAIL.yaml
> +  description: Test that the FedRAMP SSP contains only one inventory item.
Ditto.

2024-11-14 21:54 UTC, DimitriZhurkin commented on src/validations/constraints/unit-tests/has-inventory-items-PASS.yaml
> +  description: Test that the FedRAMP SSP contains the two or more inventory items.
Ditto.

2024-11-14 21:58 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +			<expect id="has-inventory-items" target="." test="count(inventory-item) >= 2" level="ERROR">
That's fair. Ignore my previous comments then. The constraint message will need to be adjusted to align with what the constraint is testing

2024-11-15 01:52 UTC, aj-stein-gsa commented on features/fedramp_extensions.feature
> -  | has-published-date |
I helped him rebase and it seems I did a so-so job.

2024-11-18 15:45 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +			<expect id="has-inventory-items" target="." test="count(inventory-item) >= 2" level="ERROR">
Ah, yes, I missed that, thanks. Fixed now.

2024-11-18 16:43 UTC, aj-stein-gsa approved these changes
I had to rebase and rewrite your two commits to clean it up. Given the feedback from others resolved and these touch-ups, it looks good now.

2024-11-18 17:08 UTC, Gabeblis approved these changes
LGTM

2024-11-18 17:17 UTC, merged