Create run-lint.yml
GSA/fedramp-automation pull request #905
Opened 2024-11-14 22:24 UTC by wandmagic

# Committer Notes

metaschema validate command doesn't accept external modules correctly since version 2.3.0
so we run it seperately and run in its own context

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-11-14 22:35 UTC, aj-stein-gsa commented on .github/workflows/run-lint.yml
> +          npx oscal use 2.2.0
Should we consider caching the installs for now?

2024-11-14 22:48 UTC, wandmagic commented on .github/workflows/run-lint.yml
> +          npx oscal use 2.2.0
i think we could probably improve action runtime if we leveraged caching

2024-11-14 22:49 UTC, wandmagic commented on .github/workflows/run-lint.yml
> +          npx oscal use 2.2.0
for now i skipped the installation of server and latest cli for this action

2024-11-14 22:59 UTC, aj-stein-gsa approved these changes
I understand the need for this to workaround some stability issues with the linting process, thanks for putting this PR together quickly. Can you let the team know why I asked you to create it and review quickly? Thanks.

2024-11-18 15:15 UTC, Gabeblis requested changes
Looks good, just some minor things that caught my attention.

2024-11-18 15:15 UTC, Gabeblis commented on .github/workflows/run-lint.yml
> +          node-version: ${{ steps.nvmrc.outputs.NODE_VERSION }}
The set-output command was [deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/). It looks like they postponed removing the command, but still recommend updating. Just a thought 
```suggestion
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Install required node.js version
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
        with:
          node-version: ${{ env.NODE_VERSION }}
```

2024-11-18 15:27 UTC, Gabeblis approved these changes

2024-11-18 15:41 UTC, aj-stein-gsa approved these changes

2024-11-18 20:50 UTC, kyhu65867 approved these changes
LGTM

2024-11-18 20:51 UTC, merged