PR for leveraged authorization constraints (issue #898)
GSA/fedramp-automation pull request #911
Opened 2024-11-18 20:37 UTC by Rene2mt

# Committer Notes

This PR adds the constraints in issue #898.  These include
- `leveraged-authorization-has-authorized-users` - Ensure every "system" component linked to a leveraged authorization has at least one authorized user.  **NOTE** - Current implementation only checks that the component (that represents the leveraged authorization service) has at least one `responsible-party` with a `role-id`.  Issue #898 called for checking the `party-uuid`, and this can be added, however, it seems the rev 5 SSP template table 6.1 may actually be looking for role rather the the respective `party`.  
- `leveraged-authorization-has-component` - Ensure every leveraged authorization entry is associated with exactly one component of type "system"
- `leveraged-authorization-has-implementation-point` - Ensure every "system" component linked to a leveraged authorization has exactly one implementation point property, and that it is set to "external"
- `leveraged-authorization-has-information-type` - Ensure every "system" component linked to a leveraged authorization has at least one information-type FedRAMP extension property
- `leveraged-authorization-has-nature-of-agreement` - Ensure every "system" component linked to a leveraged authorization has exactly one `nature-of-agreement` FedRAMP extension property

FedRAMP Developer Hub documentation changes are being prepared in a separate PR

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.? IN PROGRESS
- [x] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-11-19 19:32 UTC, wandmagic approved these changes
i like the messages you chose for this one, great job!

2024-11-20 12:54 UTC, Gabeblis requested changes
This is a good start! Just a few things that I noticed.

2024-11-20 12:58 UTC, wandmagic commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Each leveraged authorization MUST have exactly one system component.  The leveraged authorization with uuid '{ $leveraged-authorization-uuid }' has { count(../component[@type
i think the counts provide useful feedback in the message, where/when do remarks get rendered? if they are visible upon validation i'm fine with using remarks, otherwise i would prefer the information in the message where it can be received by the validating user.

2024-11-20 21:02 UTC, aj-stein-gsa requested changes

2024-11-20 21:02 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Each leveraged authorization MUST have exactly one system component.  The leveraged authorization with uuid '{ $leveraged-authorization-uuid }' has { count(../component[@type
So ... this one is going to be problematic. I did not realize during backlog definition and grooming that this shadows a pre-existing index, but with a default error message that is confusing. Hat tip to @DimitriZhurkin who brought this to my attention with a question about separate constraint development where this error occurred.

We should probably revisit this as an `index` and `index-has-key` and how it will shadow the core OSCAL even if we mimic it with a different message.

https://github.com/usnistgov/OSCAL/blob/4f02dac6f698efda387cc5f55bc99581eaf494b6/src/metaschema/oscal_ssp_metaschema.xml#L602-L607

Can we adjust the constraint _and comment it_ to make it clear it shadows an upstream constraint. The complexity around this, believe it or not, pertains to implications from https://github.com/usnistgov/OSCAL/issues/2050 that we cannot defer forever, so we will have to plan a way ahead, but we should more closely mimic that.

However, I do not think this is a FR-specific requirement, but a generic one for NIST that should be externalized to `oscal-external-constraints.xml`. I know that is a lot feel free to follow up and ask questions.

2024-11-20 21:07 UTC, wandmagic commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Each leveraged authorization MUST have exactly one system component.  The leveraged authorization with uuid '{ $leveraged-authorization-uuid }' has { count(../component[@type
if the index exists in upsteam oscal, is there any need to shadow it? can't we just use the index-has key?
and if its different, shouldn't we simply use a different name?

2024-11-22 22:48 UTC, Rene2mt commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Each leveraged authorization MUST have exactly one system component.  The leveraged authorization with uuid '{ $leveraged-authorization-uuid }' has { count(../component[@type
I think the upstream oscal leveraged-authorization index is okay to use but we need to define our own local added a `index-has-key` constraint to ensure we are checking only against `component` of type "system".  This is resolved in commit d61b3f27d8e6f6acef85038d14c6b5651ef5b8ff

2024-11-22 22:49 UTC, Rene2mt commented on src/validations/constraints/fedramp-external-constraints.xml
> +            </expect>
fixed in commit d61b3f27d8e6f6acef85038d14c6b5651ef5b8ff

2024-11-22 22:53 UTC, Rene2mt commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Each leveraged authorization system component MUST have exactly one nature of agreemeent property.  The leveraged authorization with uuid '{ $leveraged-authorization-uuid }'
Commit d61b3f27d8e6f6acef85038d14c6b5651ef5b8ff add a `index-has-key` constraint that ensures each leveraged authorization has exactly one `component` of type "system".  This constraint just checks that the component has one "nature-of-agreement" FedRAMP extension `prop` so I kept as an `expect` constraint

2024-11-22 22:54 UTC, Rene2mt commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Each leveraged authorization system component MUST have at least one information type property.  The leveraged authorization with uuid '{ $leveraged-authorization-uuid }' has
Commit d61b3f27d8e6f6acef85038d14c6b5651ef5b8ff add a `index-has-key` constraint that ensures each leveraged authorization has exactly one `component` of type "system".  This constraint just checks that the component has one "information-type" FedRAMP extension `prop` so I kept as an `expect` constraint

2024-11-22 22:55 UTC, Rene2mt commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Each leveraged authorization system component MUST have exactly one implementation point property.  The leveraged authorization with uuid '{ $leveraged-authorization-uuid }'
Commit d61b3f27d8e6f6acef85038d14c6b5651ef5b8ff add a `index-has-key` constraint that ensures each leveraged authorization has exactly one `component` of type "system".  This constraint just checks that the component has one "implementation-point" FedRAMP extension `prop` so I kept as an `expect` constraint

2024-11-22 22:56 UTC, Rene2mt commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Each leveraged authorization system component SHOULD have at least one role for authorized users.  The leveraged authorization with uuid '{ $leveraged-authorization-uuid }' h
Commit d61b3f27d8e6f6acef85038d14c6b5651ef5b8ff add a `index-has-key` constraint that ensures each leveraged authorization has exactly one `component` of type "system".  This constraint requires that there be one or more authorized users so as an `expect` constraint needed

2024-11-25 15:05 UTC, wandmagic submitted a review, later dismissed

2024-11-27 14:32 UTC, DimitriZhurkin submitted a review, later dismissed

2024-11-27 14:44 UTC, Gabeblis requested changes
Thank you for addressing my previous feedback. This looks really good! Just one small typo that I noticed.

2024-11-27 14:44 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Each leveraged authorization system component MUST have at least one information type property.  The leveraged authorization with uuid '{ $leveraged-authorization-uuid }' has
typo
```suggestion
                <message>Each leveraged authorization system component MUST have at least one information type property.  The leveraged authorization with uuid '{ $leveraged-authorization-uuid }' has a "system" component with { count($leveraged-authorization-component/prop[@name='information-type' and @ns='https://fedramp.gov/ns/oscal']) } defined "information-type" props.</message>
```

2024-11-27 15:03 UTC, Rene2mt commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Each leveraged authorization system component MUST have at least one information type property.  The leveraged authorization with uuid '{ $leveraged-authorization-uuid }' has
good catch

2024-11-27 15:06 UTC, Gabeblis approved these changes

2024-11-27 15:32 UTC, DimitriZhurkin approved these changes

2024-11-27 15:35 UTC, wandmagic submitted a review, later dismissed

2024-12-02 13:13 UTC, aj-stein-gsa requested changes

2024-12-02 18:26 UTC, aj-stein-gsa approved these changes

2024-12-02 19:33 UTC, wandmagic submitted a review, later dismissed

2024-12-10 15:53 UTC, Gabeblis approved these changes

2024-12-13 19:15 UTC, aj-stein-gsa commented
Hey @Rene2mt I just wanted to check up on this and see if we want to move this forward before or after #828 and namespace shift.

2025-02-13 01:47 UTC, Rene2mt commented
Could I get another review pls 🙏🏾 ? This was previously approved but I didn't merge so it needed a large rebase.

2025-02-13 04:50 UTC, aj-stein-gsa approved these changes

2025-02-13 15:03 UTC, Gabeblis approved these changes
LGTM

2025-02-13 19:57 UTC, merged