Add `leveraged-authorization-matches-impact-level` constraint
GSA/fedramp-automation pull request #913
Opened 2024-11-19 13:05 UTC by Gabeblis

# Committer Notes
## Purpose
This PR adds a constraint to ensure that a digital authorization package maintains appropriate FIPS-199 impact levels for leveraged authorizations within an SSP. This update helps avoid pass-back errors by aligning with the system's security sensitivity level (e.g., low, moderate, or high).

## Changes
- Added a new `expect` constraint to check that all leveraged authorizations define the appropriate FIPS-199 impact level (low, moderate, or high).
- Edited `ssp-all-VALID.xml` to have proper data to trigger the constraint and pass.
- Added an invalid test data file to trigger the constraint and demonstrate a successful fail
- Added pass and fail YAML files for the constraint.

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
~- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?~ Documentation already exists
- [x] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-11-19 13:49 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-all-VALID.xml
> +         <link href="//path/to/leveraged_system_responsibility_and_inheritance.xml"/>
Some of these links, which I do know need to be touched up in website and the older templates, are no longer relevant anymore. Do constraints actually check for these?

```suggestion
```

2024-11-19 13:49 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                else ('low')"/>
This will always select the highest level as the watermark. I thought some parts of a system can be leveraged with different impact levels, so does this logic work?

2024-11-19 13:52 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                else ('low')"/>
I thought that was the goal. Should we only be checking for one of the allowed values then?

2024-11-19 13:59 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                else ('low')"/>
Unclear let's discuss in chat. If you leverage more than one service some part might not have sensitive data (like if you use NewRelic for monitoring and controls around monitoring and alerting for incident response; the high risk data is not in there redacted logs and monitoring data are).

2024-11-19 15:05 UTC, Gabeblis commented on src/validations/constraints/content/ssp-all-VALID.xml
> +         <link href="//path/to/leveraged_system_responsibility_and_inheritance.xml"/>
Resolved: [c206c0c](https://github.com/GSA/fedramp-automation/pull/913/commits/c206c0ca02bab399adfc9e4eed77986f1f5ad3d8)

2024-11-20 15:42 UTC, brian-ruf commented on src/validations/constraints/fedramp-external-constraints.xml
> +                else ('low')"/>
This should be comparing the property `//component[@type='system' and ./prop[@name='leveraged-authorization-uuid']]/prop[@name='impact-level' and @ns='http://fedramp.gov/ns/oscal'] /@value` with ``//system-characteristics/security-sensitivity-level`

Both of which should be using `fips-199-high`, `fips-199-moderate`, `fips-199-low` allowed values.

2024-11-20 16:53 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                else ('low')"/>
@brian-ruf So we are comparing a `prop[@name='impact-level']` within a component,  with `security-sensitivity-level`? That's pretty different than what #888 is asking. I also looked through your ssp branch and the templates, and I don't see such a component. I only see the `impact-level` prop being used within the leveraged authorization.

2024-11-20 17:16 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                else ('low')"/>
@Gabeblis for context, this is what I alluded to in standup earlier today because Brian and I noticed the disparity. The FedRAMP pre-OSCAL documents use this phrase "impact level" casually to mean a bunch of things. This is Table 6.1 from the current template as of a few days ago.

![image](https://github.com/user-attachments/assets/e942e7ff-3fd6-444d-948a-49c0bf2028b6)

This connects to Table 3.1 where you take the other impact levels and they form an overall sensitivity level is called "the FIPS PUB 199 Level" and that is `sensitivity-level` and relates to the high watermark of the three values for the related `impact-levels` as we define their names in OSCAL.

![image](https://github.com/user-attachments/assets/430c9642-e43c-4d95-b475-3ad3738c62aa)

Re my concern with the high watermark, your logic was right, I was wrong; I will skip a very long explanation but picking the highest level is right), but we are looking in the wrong spot. Brian noticed that the issue was unclear; everyone interchanges these words inside and outside of OSCAL, that was on me.

I will update review feedback momentarily.

2024-11-20 17:43 UTC, aj-stein-gsa requested changes

2024-11-20 17:43 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            </expect>
OK, so now I have to come back to the point I made before and I had not finished with in my previous review until talking to @brian-ruf and @Rene2mt. Apologies. Important context I added in https://github.com/GSA/fedramp-automation/pull/913#discussion_r1850710632 is in the review comments. You acted upon immediately but I wanted to review the issue's goals I wrote. I gave some deeper context here, I didn't circle back fast enough like Brian to land the plane so to speak.

So, re your previous logic, it was good. What was the issue was looking at the impact level _not_ the security-sensitivity-level. You fixed that. That gets you the same answer separate of the FIPS-199 inputs that decide what is the "correct" value for the sensitivity-level. But by removing this logic, we have come back to the thing I verified. I presumed, the high watermark approach is correct, my assumption was wrong.

Let's say you have a system that has a security-sensitivity-level of `fips-199-low`, the leveraged authorization level MAY be any of the sensitivity levels.

- `fips-199-low`
- `fips-199-moderate`
- `fips-199-high`

Let's say you have a system that has a security-sensitivity-level of `fips-199-moderate`, the leveraged authorization level MAY be any of the sensitivity levels.

- `fips-199-moderate`
- `fips-199-high`

Let's say you have a system that has a security-sensitivity-level of `fips-199-moderate`, the leveraged authorization level MAY be any of the sensitivity levels.

- `fips-199-high`

To make a cute diagram (incoming, writing it up now if I can) as to the names and the confusion, impact levels of the system document in a SSP feed into security-sensitivity-level for that system, and given that computed sensitivity-level based upon those impact levels, the leveraged authorization impact types have to match "the floor value" of what that sensitivity level allows. The FIPS-199 document goes into this "math" with more detail than you would like (just not talking about the leveraged auth piece).

2024-11-20 18:42 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +            </expect>
Thank you for the explanation. I implemented the requirement here: [45f01c4](https://github.com/GSA/fedramp-automation/pull/913/commits/45f01c4684e62fc4abc53a645e9ee80ab94079f8). Please let me know if this is satisfactory 👍

2024-11-20 18:43 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                else ('low')"/>
This helps. Thanks!

2024-11-20 20:39 UTC, wandmagic approved these changes
looks good nice work

2024-11-20 23:05 UTC, aj-stein-gsa requested changes
Looks very solid but would like the documentation change to match.

2024-11-20 23:05 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#leveraged-fedra
Can you please add the necessary prop to the example in the referenced documentation at that URL and anchor and call out in a sentence with a sub-heading that it is required?

After that I can approve this.

2024-11-22 14:46 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#leveraged-fedra
Opened a [PR](https://github.com/GSA/automate.fedramp.gov/pull/124) for this on automate.fedramp.

2024-11-22 17:36 UTC, aj-stein-gsa submitted a review, later dismissed
Very good work, I particularly enjoy how you document the scenarios in your passing and failing test cases over the last few weeks. Keep it up!

2024-11-25 15:21 UTC, wandmagic approved these changes

2024-11-25 19:26 UTC, Rene2mt submitted a review, later dismissed
Looks good to me.

2024-11-27 16:59 UTC, DimitriZhurkin approved these changes

2024-11-29 17:01 UTC, aj-stein-gsa approved these changes

2024-12-02 12:39 UTC, wandmagic approved these changes

2024-12-02 14:53 UTC, DimitriZhurkin requested changes

2024-12-02 14:53 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="leveraged-authorization-has-valid-impact-level" target="//leveraged-authorization/prop[@name='impact-level'][@ns='https://fedramp.gov/ns/oscal']/@value" test=". = $sensitivity
Add the `@level` attribute:
```suggestion
            <expect id="leveraged-authorization-has-valid-impact-level" target="//leveraged-authorization/prop[@name='impact-level'][@ns='https://fedramp.gov/ns/oscal']/@value" test=". = $sensitivity-level-floor" level="ERROR">
```

2024-12-02 16:30 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="leveraged-authorization-has-valid-impact-level" target="//leveraged-authorization/prop[@name='impact-level'][@ns='https://fedramp.gov/ns/oscal']/@value" test=". = $sensitivity
Nice catch! Resolved: [0945578](https://github.com/GSA/fedramp-automation/pull/913/commits/09455781ebaaafbe11ca034d8d507d950ac44efa)

2024-12-02 17:52 UTC, wandmagic approved these changes

2024-12-02 18:16 UTC, kyhu65867 approved these changes

2024-12-02 19:06 UTC, aj-stein-gsa approved these changes
Review acceptance criteria and related documentation updates to the website in https://github.com/GSA/automate.fedramp.gov/pull/124, looks good to go. 🚢

2024-12-02 19:07 UTC, merged