Update fedramp-external-allowed-values.xml
GSA/fedramp-automation pull request #917
Opened 2024-11-19 19:41 UTC by wandmagic

# Committer Notes

improve information-types constraint

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-11-19 19:41 UTC, wandmagic commented
addresses https://github.com/orgs/GSA/projects/25/views/11?pane=issue&itemId=86941737&issue=GSA%7Cfedramp-automation%7C890

2024-11-19 20:20 UTC, DimitriZhurkin requested changes
@wandmagic,

For the sake of consistency, in `@value` attributes, do you want to replace single quotes with double quotes?

2024-11-19 20:27 UTC, wandmagic commented
> @wandmagic,
> 
> For the sake of consistency, in `@value` attributes, do you want to replace single quotes with double quotes?

fixed

2024-11-19 20:30 UTC, DimitriZhurkin submitted a review, later dismissed
Super job!

2024-11-19 21:48 UTC, aj-stein-gsa requested changes

2024-11-19 21:48 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +                <enum value="C.2.1.1">Controls and Oversight &#x2F; Corrective Action Information Type as defined by <a href='https://doi.org/10.6028/NIST.SP.800-60v2r1'>NIST.SP.800-60v2r1</a></enum>
I am sorry to be that person, but since it is a category can we go for `Category: information type`? I will just guess that hex encoding of special characters is a bridge too far if embedded hrefs are not to important information about the data.


```suggestion
                <enum value="C.2.1.1">Controls and Oversight: Corrective Action Information Type as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.1.2">Controls and Oversight: Program Evaluation as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.1.3">Controls and Oversight: Program Monitoring as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.2.1">Regulatory Development: Policy and Guidance Development as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.2.2">Regulatory Development: Public Comment Tracking as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.2.3">Regulatory Development: Regulatory Creation as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.2.4">Regulatory Development: Rule Publication as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.3.1">Planning and Budgeting: Budget Formulation as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.3.2">Planning and Budget: Capital Planning as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.3.3">Planning and Budget: Enterprise Architecture as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.3.4">Planning and Budget: Strategic Planning as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.3.5">Planning and Budget: Budget Execution as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.3.6">Planning and Budget: Workforce Planning as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.3.7">Planning and Budget: Management Improvement as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.3.8">Planning and Budget: Budget and Performance Integration as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.3.9">Planning and Budget: Tax and Fiscal Policy as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.4.1">Internal Risk Management and Mitigation: Contingency Planning as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.4.2">Internal Risk Management and Mitigation: Continuity of Operations as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.4.3">Internal Risk Management and Mitigation: Service Recovery as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.5.1">Revenue Collection: Debt Collection as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.5.2">Revenue Collection: User Fee Collection as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.5.3">Revenue Collection: Federal Asset Sales as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.6.1">Public Affairs: Customer Services as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.6.2">Public Affairs: Official Information Dissemination as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.6.3">Public Affairs: Product Outreach as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.6.4">Public Affairs: Public Relations as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.7.1">Legislative Relations: Legislation Tracking as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.7.2">Legislative Relations: Legislative Testimony as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.7.3">Legislative Relations: Proposal Development as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.7.4">Legislative Relations: Congressional Liaison Operations as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.8.1">General Government: Central Fiscal Operations as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.8.2">General Government: Legislative Functions as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.8.3">General Government: Executive Functions as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.8.4">General Government: Central Property Management as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.8.5">General Government: Central Personnel Management as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.8.6">General Government: Taxation Management as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.8.7">General Government: Central Records and Statistics Management as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.8.8">General Government: Income Information as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.8.9">General Government: Personal Identity and Authentication Information as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.8.10">General Government: Entitlement Event Information as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.8.11">General Government: Representative Payee Information as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.8.12">General Government: General Information as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.3.1.1">Administrative Management: Facilities, Fleet, and Equipment Management as defined by < [...]

2024-11-19 21:52 UTC, aj-stein-gsa submitted a review, later dismissed
Sorry messed up scope of last review suggestion.

2024-11-19 21:52 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +                <enum value="D.26.2">Direct Services for Citizens &#x2F; Civilian Operations as defined by <a href='https://doi.org/10.6028/NIST.SP.800-60v2r1'>NIST.SP.800-60v2r1</a></enum>
I am sorry to be that person, but since it is a category can we go for `Category: information type`? I will just guess that hex encoding of special characters is a bridge too far if embedded hrefs are not to important information about the data.

Also it would be appreciate to fix the quotes for symmetry on the link hrefs.


```suggestion
                <enum value="C.2.1.1">Controls and Oversight: Corrective Action Information Type as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.1.2">Controls and Oversight: Program Evaluation as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.1.3">Controls and Oversight: Program Monitoring as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.2.1">Regulatory Development: Policy and Guidance Development as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.2.2">Regulatory Development: Public Comment Tracking as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.2.3">Regulatory Development: Regulatory Creation as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.2.4">Regulatory Development: Rule Publication as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.3.1">Planning and Budgeting: Budget Formulation as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.3.2">Planning and Budget: Capital Planning as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.3.3">Planning and Budget: Enterprise Architecture as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.3.4">Planning and Budget: Strategic Planning as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.3.5">Planning and Budget: Budget Execution as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.3.6">Planning and Budget: Workforce Planning as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.3.7">Planning and Budget: Management Improvement as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.3.8">Planning and Budget: Budget and Performance Integration as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.3.9">Planning and Budget: Tax and Fiscal Policy as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.4.1">Internal Risk Management and Mitigation: Contingency Planning as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.4.2">Internal Risk Management and Mitigation: Continuity of Operations as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.4.3">Internal Risk Management and Mitigation: Service Recovery as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.5.1">Revenue Collection: Debt Collection as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.5.2">Revenue Collection: User Fee Collection as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.5.3">Revenue Collection: Federal Asset Sales as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.6.1">Public Affairs: Customer Services as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.6.2">Public Affairs: Official Information Dissemination as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.6.3">Public Affairs: Product Outreach as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.6.4">Public Affairs: Public Relations as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.7.1">Legislative Relations: Legislation Tracking as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.7.2">Legislative Relations: Legislative Testimony as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.7.3">Legislative Relations: Proposal Development as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.7.4">Legislative Relations: Congressional Liaison Operations as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.8.1">General Government: Central Fiscal Operations as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.8.2">General Government: Legislative Functions as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.8.3">General Government: Executive Functions as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.8.4">General Government: Central Property Management as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.8.5">General Government: Central Personnel Management as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.8.6">General Government: Taxation Management as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.8.7">General Government: Central Records and Statistics Management as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.8.8">General Government: Income Information as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.8.9">General Government: Personal Identity and Authentication Information as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.8.10">General Government: Entitlement Event Information as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.8.11">General Government: Representative Payee Information as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.2.8.12">General Government: General Information as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="C.3.1.1">Adminis [...]

2024-11-19 22:07 UTC, aj-stein-gsa approved these changes

2024-11-19 22:07 UTC, DimitriZhurkin submitted a review, later dismissed

2024-11-19 22:17 UTC, Gabeblis reviewed
@aj-stein-gsa were we looking to remove all instances of `&#x2F` here? Just something that I caught. If not, go ahead and ignore this feedback.

2024-11-19 22:17 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +                <enum value="C.3.2.7">Financial Management: Cost Accounting&#x2F; Performance Measurement as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></en
```suggestion
                <enum value="C.3.2.7">Financial Management: Cost Accounting; Performance Measurement as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
```

2024-11-19 22:17 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +                <enum value="D.25.4">Transfers to Local&#x2F;State Governments: State Loans as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
```suggestion
                <enum value="D.25.1">Transfers to Local;State Government: Formula Grants as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="D.25.2">Transfers to Local;State Government: Project/Competitive Grants as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="D.25.3">Transfers to Local;State Governments: Earmarked Grants as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
                <enum value="D.25.4">Transfers to Local;State Governments: State Loans as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></enum>
```

2024-11-19 22:29 UTC, Gabeblis approved these changes

2024-11-19 22:54 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +                <enum value="C.3.2.7">Financial Management: Cost Accounting&#x2F; Performance Measurement as defined by <a href="https://doi.org/10.6028/NIST.SP.800-60v2r1">NIST.SP.800-60v2r1</a></en
Yeah I did a Ctrl-F and grep one-off, so maybe I missed something somehow?

2024-11-20 13:39 UTC, DimitriZhurkin approved these changes

2024-11-20 14:58 UTC, kyhu65867 approved these changes
Nice job!

2024-11-20 14:59 UTC, merged