Add `saas-has-leveraged-authorization` constraint
GSA/fedramp-automation pull request #919
Opened 2024-11-20 17:54 UTC by Gabeblis

# Committer Notes
## Purpose
This PR aims to ensure that SaaS cloud service offerings include at least one leveraged-authorization. 

## Changes
Added Constraint:
- `saas-has-leveraged-authorization`: Validates that if a SaaS service model is declared, the SSP must include at least one leveraged-authorization.

Added Test Data:
- `1 Invalid Test File`: Demonstrates a failure case where a SaaS service model is declared, but no leveraged-authorization elements are provided.

- `2 Valid Test Files`: Demonstrate the two ways in which the constraint can pass: A  SaaS service model is declared with one or more leveraged-authorization(s) OR `ssp-all-INVALID.xml` demonstrates no SaaS service model is declared. 

Added YAML Files:
- `2 YAML files`: Included pass and fail YAML files.
### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [x] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-11-20 20:38 UTC, wandmagic commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="saas-has-leveraged-authorization" target="." test="if (exists(prop[@name='cloud-service-model' and @value='saas'])) then (count(..//leveraged-authorization) >= 1) else (true()
NON Blocking, I would like isSaas variable, in case we have other constraints on SAAS cloud services in the future. we can save that as an improvement if / when a second constraint comes along

2024-11-20 20:38 UTC, wandmagic approved these changes

2024-11-20 21:16 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="saas-has-leveraged-authorization" target="." test="if (exists(prop[@name='cloud-service-model' and @value='saas'])) then (count(..//leveraged-authorization) >= 1) else (true()
I could agree with that myself.

2024-11-20 21:16 UTC, aj-stein-gsa submitted a review, later dismissed

2024-11-20 21:46 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="saas-has-leveraged-authorization" target="." test="if (exists(prop[@name='cloud-service-model' and @value='saas'])) then (count(..//leveraged-authorization) >= 1) else (true()
That's valid. I actually had that before, but then I changed the implementation. I will add that back.

2024-11-20 21:50 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="saas-has-leveraged-authorization" target="." test="if (exists(prop[@name='cloud-service-model' and @value='saas'])) then (count(..//leveraged-authorization) >= 1) else (true()
done: [490cb0a](https://github.com/GSA/fedramp-automation/pull/919/commits/490cb0abb9251b1b92d0724ec2980dc973d63d3d)

2024-11-20 22:31 UTC, wandmagic submitted a review, later dismissed

2024-11-20 23:02 UTC, aj-stein-gsa requested changes

2024-11-20 23:02 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#service-model"/
Blocking: I know I started us down this road, so I apologize. It would seem that the documentation for leveraged authorization counts for a system of type saas belongs here. The at least one requirement is implied, but not explicit can you update that section and update this prop URL target accordingly?

```suggestion
                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#leveraged-fedramp-authorized-services"/>
```

2024-11-21 12:03 UTC, wandmagic approved these changes

2024-11-22 16:11 UTC, wandmagic approved these changes

2024-11-25 15:22 UTC, wandmagic approved these changes

2024-11-25 19:50 UTC, Rene2mt approved these changes
This is good to go

2024-11-25 20:10 UTC, merged