Add leveraged-authorization-nature-of-agreement
GSA/fedramp-automation pull request #920
Opened 2024-11-20 19:23 UTC by DimitriZhurkin

# Committer Notes

Add allowed values for SSP `nature-of-agreement` props for leveraged systems.

Related issue: #889

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-11-20 20:35 UTC, wandmagic submitted a review, later dismissed

2024-11-20 21:05 UTC, wandmagic approved these changes

2024-11-21 18:07 UTC, wandmagic approved these changes

2024-11-21 18:36 UTC, Gabeblis requested changes
Solid work. Just a couple things that I noticed.

2024-11-21 18:36 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +        	</allowed-values>
A few things here: 
1) Do you mind adjusting the indentation here so that it is consistent with the rest of the file. It's a 4 space indentation. 
2) Also if you could do the same for the allowed-value block itself, so that it lines up with the rest of them.
3) This constraint is not sorted alphabetically per [the style guide](https://github.com/GSA/fedramp-automation/blob/develop/src/validations/styleguides/STYLE.md#frr103). You'll just have to copy/paste it between `inventory-item-virtual` and `privilege-level`

2024-11-21 18:36 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +        		<prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping//#fedramp-allowed-valu
I would change this deep link to be the main header for this content. The current deep link wouldn't be suitable if there are multiple `Fedramp Allowed Values` sections. Even if we appended the index (-1/-2/etc.), it could change when new documentation is added. 
```suggestion
        		<prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#leveraged-fedramp-authorized-services"/>
```

2024-11-21 19:41 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +        	</allowed-values>
Done.

2024-11-21 19:41 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-allowed-values.xml
> +        		<prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping//#fedramp-allowed-valu
Fixed.

2024-11-22 13:45 UTC, Gabeblis approved these changes

2024-11-22 15:39 UTC, merged