Example SSP Reflecting Latest FedRAMP OSCAL Modeling
GSA/fedramp-automation pull request #925
Opened 2024-11-21 17:09 UTC by brian-ruf

# Committer Notes

This PR contains an OSCAL SSP Example File that reflects revisions to the way required FedRAMP content is modeled in OSCAL.

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-11-21 18:11 UTC, wandmagic commented
in fedramp_extensions.feature file line 13
Add your in progress SSP into the test runner so the github actions can capture validity of this SSP
src/content/rev5/examples/ssp/xml/FedRAMP-SSP-Example.OSCAL.xml

2024-12-04 22:10 UTC, aj-stein-gsa requested changes

2024-12-04 22:10 UTC, aj-stein-gsa commented on src/content/rev5/examples/UUIDs_for_Examples_Legend.md
To start acting on this, are you OK with me converting this into a page on the developer wiki?

2024-12-05 15:21 UTC, kyhu65867 commented on src/content/rev5/examples/ssp/xml/fedramp-ssp-example.oscal.xml
> +      <oscal-version>1.1.2</oscal-version>
Worth updating to 1.1.3?

2024-12-05 15:21 UTC, kyhu65867 commented on src/content/rev5/examples/UUIDs_for_Examples_Legend.md
> +# UUIDs for Examples
If this is important for all of our stakeholders to know (aka we are going to reject their package if they don't name their UUIDs correctly), it may be worth making a diagram to add to this file. (It could be worth it anyways just for the sake of clarity and so that different visual learners can understand this because I'm having trouble parsing it out)

2025-01-06 14:45 UTC, brian-ruf commented on src/content/rev5/examples/UUIDs_for_Examples_Legend.md
> +# UUIDs for Examples
@kyhu65867 this is only for creating examples with easier-to-read UUIDs. Our stakeholders should **not** be using this for real packages.

The idea was to have consistency in how these example UUIDs appear from one example to the next. It was in response to feedback we had received about the difficulty of following examples with truly random UUIDs (as is their nature) and balancing that against other feedback that all our examples should be valid. (Thus preventing us from using things like `component-uuid="[uuid-of-component]"` which is easier to understand, but invalid.

2025-01-06 14:46 UTC, brian-ruf commented on src/content/rev5/examples/UUIDs_for_Examples_Legend.md
> +# UUIDs for Examples
That said, I agree a diagram is helpful and I'll work on something when I'm done the analysis work.

2025-01-06 14:48 UTC, brian-ruf commented on src/content/rev5/examples/ssp/xml/fedramp-ssp-example.oscal.xml
> +      <oscal-version>1.1.2</oscal-version>
Agreed. Done.

2025-01-06 14:52 UTC, brian-ruf commented on src/content/rev5/examples/UUIDs_for_Examples_Legend.md
@aj-stein-gsa, while I am OK with it, please be aware this is ONLY for the creation of examples and is in response to feedback that the truly random UUIDs made the examples difficult to follow, while also receiving feedback that all examples should be fully valid OSCAL, preventing us from using things like, `component-uuid="[uuid-of-database-component]"`. 

We probably need to be more clear about that and/or place it in a part of the wiki that helps clarify this is guidance for creating examples and should **not** be used for submitted packages.

2025-02-19 19:16 UTC, closed without merging