implementation point constraint
GSA/fedramp-automation pull request #936
Opened 2024-11-25 16:54 UTC by wandmagic

# Committer Notes

add implementation point constraint

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-11-25 19:35 UTC, kyhu65867 reviewed
Let me know what you think of this feedback-- mostly to do with the failing unit test. I'm going to comment for now because I'm not sure if it is blocking

2024-11-25 19:35 UTC, kyhu65867 commented on src/validations/constraints/content/ssp-network-component-has-implementation-point-INVALID.xml
> +    <component uuid="66666666-0000-4000-9000-000000000006" type="service">
It might be worth testing if one component has an implementation point, and a different one doesn't, would the constraint still fail? That way you check to be sure it only passes if every component has an implementation point. Not mandatory, but I think it would be good. 

Additionally, if there are multiple components and only the last one doesn't include an implementation point, would  this constraint point to that specific component, or no?

2024-11-25 19:55 UTC, wandmagic commented on src/validations/constraints/content/ssp-network-component-has-implementation-point-INVALID.xml
> +    <component uuid="66666666-0000-4000-9000-000000000006" type="service">
My first attempt at this constraint looked like something like this:
```
    <context>
        <metapath target="//system-implementation/component[@type='service' or (@type='software' and ./prop[@name='asset-type' and @value='cli'])]"/>
        <constraints>
            <expect id="network-component-has-implementation-point" target="." test="count(prop[@name='implementation-point']) = 1" level="ERROR">
                <formal-name>Component Has Implementation Point</formal-name>
                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/5-attachments/#system-inventory-approach"/>
                <message>Service components and CLI software components MUST have exactly one implementation-point property.</message>
            </expect>
        </constraints>
    </context>

```
I like this better because the rule executes exactly on the items it needs to instead of the parent.

however, when I execute this every unit test fails and I get this undecipherable error message
`rror: OSCAL CLI process exited with code 6:
Unexpected error occured: null
java.lang.NullPointerException: null
        at java.base/java.util.Objects.requireNonNull(Objects.java:220) ~[?:?]
        at java.base/java.util.ImmutableCollections.listFromTrustedArray(ImmutableCollections.java:215) ~[?:?]
        at java.base/java.util.ImmutableCollections$Access$1.listFromTrustedArray(ImmutableCollections.java:124) ~[?:?]
        at java.base/java.util.stream.Collectors.lambda$toUnmodifiableList$6(Collectors.java:266) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:731) ~[?:?]
        at gov.nist.secauto.metaschema.core.metapath.impl.StreamSequence.getValue(StreamSequence.java:63) ~[dev.metaschema.java.metaschema-core-2.0.1.jar:?]
        at gov.nist.secauto.metaschema.core.metapath.function.ComparisonFunctions.generalCompairison(ComparisonFunctions.java:100) ~[dev.metaschema.java.metaschema-core-2.0.1.jar:?]
        at gov.nist.secauto.metaschema.core.metapath.cst.comparison.GeneralComparison.accept(GeneralComparison.java:48) ~[dev.metaschema.java.metaschema-core-2.0.1.jar:?]
        at gov.nist.secauto.metaschema.core.metapath.cst.Or.accept(Or.java:70) ~[dev.metaschema.java.metaschema-core-2.0.1.jar:?]`

2024-11-25 19:56 UTC, wandmagic commented on src/validations/constraints/content/ssp-network-component-has-implementation-point-INVALID.xml
> +    <component uuid="66666666-0000-4000-9000-000000000006" type="service">
the workaround does indeed have the issue you describe, it will point to the parent and say there is something wrong here, we can include the information on the offending items in the error message to work around this

2024-11-25 20:17 UTC, wandmagic commented on src/validations/constraints/content/ssp-network-component-has-implementation-point-INVALID.xml
> +    <component uuid="66666666-0000-4000-9000-000000000006" type="service">
I've update the constraint and unit test to address this feedback

2024-11-25 22:25 UTC, kyhu65867 submitted a review, later dismissed

2024-11-25 22:25 UTC, kyhu65867 commented on src/validations/constraints/content/ssp-network-component-has-implementation-point-INVALID.xml
> +      <prop name="asset-type" value="cli"/>
add implementation point property in one component and not the other to test if your constraint sees everything it needs to

2024-11-26 13:23 UTC, wandmagic commented on src/validations/constraints/content/ssp-network-component-has-implementation-point-INVALID.xml
> +      <prop name="asset-type" value="cli"/>
added

2024-11-26 14:48 UTC, Gabeblis submitted a review, later dismissed

2024-11-26 17:58 UTC, DimitriZhurkin requested changes

2024-11-26 17:58 UTC, DimitriZhurkin commented on src/validations/constraints/content/ssp-all-VALID.xml
> +      <prop name="implementation-point" value="external"></prop>
I'd make it an empty element:
```suggestion
      <prop name="implementation-point" value="external"/>
```

2024-11-26 18:01 UTC, DimitriZhurkin approved these changes

2024-11-26 18:13 UTC, Gabeblis approved these changes

2024-11-27 16:40 UTC, Rene2mt requested changes

2024-11-27 16:40 UTC, Rene2mt commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/5-attachments/#system-inventory-approach"/>
For now, `implementation-point` is discussed here:  

```suggestion
                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/ssp/4-ssp-template-to-oscal-mapping/#leveraged-fedramp-authorized-services"/>
```

Longer term, [issue # 126](https://github.com/GSA/automate.fedramp.gov/issues/126) will updated leveraged authorization and non-authorized external systems documentation and we will likely need to update the `help-url` to point to the updated documentation.

2024-11-27 16:58 UTC, DimitriZhurkin approved these changes

2024-12-02 20:21 UTC, aj-stein-gsa reviewed
Can you please rebase this PR? Sorry and thanks in advance.

2024-12-03 13:56 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +    </context>
Are you able to use the existing system-implementation context on line 507 instead of creating this new context block, and also sort the constraints alphabetically?

2024-12-03 14:03 UTC, aj-stein-gsa requested changes
Solid work, I see some post-rebase issues, can we double check that unrelated addition I see in the diff is not something a re-rebase or update to current `develop` would fix? 

Back on topic: the constraint target and test are straightforward and you did solid work as always, I have some recommendations on the message text, but we may want some team discussion on that.

2024-12-03 14:03 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Service components and CLI software components MUST have exactly one implementation-point property.</message>
[FRR111](https://github.com/GSA/fedramp-automation/blob/develop/src/validations/styleguides/STYLE.md#frr111) and [FRR113](https://github.com/GSA/fedramp-automation/blob/develop/src/validations/styleguides/STYLE.md#frr113) feedback:

```suggestion
                <message>A FedRAMP SSP with service components and CLI software components performing cross-boundary network communication MUST indicate exactly one time if the point of implementation is internal or external to the system.</message>
```

That said, I am not sure my suggestion is good enough to take as-is, maybe workshop with the team. I added some wordiness to explain the concept as refined with communication with the team yesterday in [Google Chat](https://chat.google.com/room/AAAAn3vuHpo/UZmw209Gi0o/okN9GILbMwQ?cls=10). It may seem like a different topic, but conceptually very related. (We are talking about cross-boundary communication, so those not in the category of "Most technical components are 'networked,' but only for communication within the authorization boundary." category.)

2024-12-03 16:30 UTC, wandmagic commented on src/validations/constraints/fedramp-external-constraints.xml
> +            </is-unique>
i am sneaking in a second constraint to reduce amount of WIPS

2024-12-03 16:31 UTC, wandmagic commented on src/validations/constraints/fedramp-external-constraints.xml
> +            </is-unique>
i can take it out if we need but it works

2024-12-03 17:52 UTC, Gabeblis approved these changes

2024-12-03 18:08 UTC, merged