Add constraint 'component-responsible-role-references-party'
GSA/fedramp-automation pull request #945
Opened 2024-11-27 15:21 UTC by Gabeblis

# Committer Notes
## Purpose
This PR introduces a constraint `component-responsible-role-references-party`, which ensures that each component dealing with leveraged systems, interconnections, or authorized services has a "provider" responsible-role that references exactly one valid party.

## Changes

Added Constraint:
- `component-responsible-role-references-party`: Validates that each component dealing with leveraged systems, interconnections, or authorized services has a "provider" responsible-role that references exactly one valid party.

Test Data:
- **Invalid Test Data File**: Demonstrates the case where there the party count is not equal to 1.
- **Valid Test Data File**: Demonstrates the case where the party count is equal to 1.

Added YAML Files
- **2 YAML Files**: Included pass and fail YAML files to validate the constraint:

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [x] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-11-27 15:36 UTC, DimitriZhurkin submitted a review, later dismissed

2024-11-27 16:05 UTC, wandmagic submitted a review, later dismissed

2024-11-27 18:22 UTC, Rene2mt requested changes
[Blocking]: The PR looks good, just suggestion to make sure we test against scenario where we get an SSP that has a leveraged authorization or external system with multiple parties associated.

2024-11-27 18:22 UTC, Rene2mt commented on src/validations/constraints/content/ssp-component-responsible-role-references-party-INVALID.xml
> +        <party-uuid>11111111-0000-4000-9000-000000000001</party-uuid>
The intent of this constraint is to make sure that for a given (leveraged authorization or external system) `component`, there is only one `party` associated (via `party-uuid`), so one main fail scenario would be something like this...

```suggestion
        <party-uuid>11111111-0000-4000-9000-000000000001</party-uuid>
        <party-uuid>11111111-0000-4000-9000-000000000002</party-uuid>
```
Core OSCAL allows this one-to-many association, but for FedRAMP leveraged authorization or external system components, we are only expecting one provider.

2024-11-27 18:24 UTC, Gabeblis commented
apologies @wandmagic @DimitriZhurkin, if you could please re-review. I had to add a small change on top of the rebase (adding remarks to the authentication method). Just future proofing for another constraint.

2024-11-27 19:02 UTC, Gabeblis commented on src/validations/constraints/content/ssp-component-responsible-role-references-party-INVALID.xml
> +        <party-uuid>11111111-0000-4000-9000-000000000001</party-uuid>
According to #937 and the following test: `count(//party[@uuid=./responsible-role[@role-id='provider']/party-uuid]) = 1` it looks like we're checking that only one party exists per responsible role with a `role-id` of "provider". Are you saying we should change this constraint to enforce that there is only 1 party listed under the responsible roles? or should we add a separate constraint for this?

2024-11-27 19:44 UTC, Rene2mt commented on src/validations/constraints/content/ssp-component-responsible-role-references-party-INVALID.xml
> +    </party>
The scenario where two parties have shouldn't have the same UUID is is covered by this index in core OSCAL - https://github.com/usnistgov/OSCAL/blob/b123c11bd12c8b8f1bcc8bf85763e5775c0423e9/src/metaschema/oscal_metadata_metaschema.xml#L386-L389

2024-11-27 19:57 UTC, Gabeblis commented on src/validations/constraints/content/ssp-component-responsible-role-references-party-INVALID.xml
> +    </party>
Ok, thank you for the clarification. Then in this case, I'll just check that there is 1 party within the "provider" responsible role, instead of the current implementation. 👍

2024-11-27 20:11 UTC, Gabeblis commented on src/validations/constraints/content/ssp-component-responsible-role-references-party-INVALID.xml
> +    </party>
@Rene2mt I just pushed commit: [2c19c60](https://github.com/GSA/fedramp-automation/pull/945/commits/2c19c60abe585150641722d15dd3f41f0e4ecb1d). Can you let me know if this is what we're looking for with this constraint. Thanks!

2024-11-27 20:27 UTC, Rene2mt approved these changes

2024-11-27 20:29 UTC, wandmagic approved these changes

2024-11-27 21:03 UTC, DimitriZhurkin requested changes

2024-11-27 21:03 UTC, DimitriZhurkin commented on src/validations/constraints/content/ssp-all-VALID.xml
>        <prop name="direction" value="in/out" ns="https://fedramp.gov/ns/oscal"/>
Shouldn't `direction` value be either `incoming` or `outgoing`?

2024-11-27 21:13 UTC, Gabeblis commented on src/validations/constraints/content/ssp-all-VALID.xml
>        <prop name="direction" value="in/out" ns="https://fedramp.gov/ns/oscal"/>
This isn't part of this PR. This specifically was added in #929, but doesn't relate to the scope of this PR. If these values should be changed, we should open an issue for this and change them all in one sweep.

2024-11-27 21:20 UTC, DimitriZhurkin submitted a review, later dismissed

2024-11-27 21:21 UTC, DimitriZhurkin commented on src/validations/constraints/content/ssp-all-VALID.xml
>        <prop name="direction" value="in/out" ns="https://fedramp.gov/ns/oscal"/>
Very valid point.

2024-11-29 17:08 UTC, Gabeblis commented
@brian-ruf before this gets merged, I'd like to confirm with you that the change in 62e9de688865d44ebdc3901760945242b3aeec8d is what we're looking to test with this constraint. The constraint now checks that there is just one `party-uuid` referenced in "provider" responsible role (`count(responsible-role[@role-id='provider']/party-uuid) = 1`).

2024-11-29 19:36 UTC, brian-ruf commented
Correct. This can't be ambiguous as to who the provider is. There should be exactly one party associated with the "provider" role for each component where a provider must be identified.

2024-11-29 19:56 UTC, Gabeblis commented
> Correct. This can't be ambiguous as to who the provider is. There should be exactly one party associated with the "provider" role for each component where a provider must be identified.

Great. Thanks for confirming.

2024-11-29 20:41 UTC, aj-stein-gsa approved these changes
I know we were discussing possible doc changes but the constraint looks solid, nice work.

2024-12-02 12:41 UTC, wandmagic submitted a review, later dismissed

2024-12-02 20:10 UTC, aj-stein-gsa submitted a review, later dismissed

2024-12-02 20:10 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Each component dealing with leveraged systems, interconnections, or authorized services MUST have a "provider" responsible-role that references exactly one valid party.</mess
Minor: can we follow [FRR111](https://github.com/GSA/fedramp-automation/blob/develop/src/validations/styleguides/STYLE.md#frr111) and make the passive voice with the subject as the document?

```suggestion
                <message>A FedRAMP SSP MUST have each component describing leveraged systems, interconnections, or authorized services identify a "provider" role that references one responsible party.</message>
```

2024-12-02 20:13 UTC, aj-stein-gsa approved these changes

2024-12-03 13:16 UTC, wandmagic approved these changes

2024-12-03 13:55 UTC, Rene2mt approved these changes
looks good!

2024-12-03 13:57 UTC, merged