Add Example SSP
GSA/fedramp-automation pull request #953
Opened 2024-12-03 17:25 UTC by Gabeblis

# Committer Notes
## Purpose
This PR aims to add a new example SSP.

## Changes
- `fedramp-example-ssp.xml` was added to the content folder.
- feature file was edited to comment out `ssp-all-VALID.xml` under integration testing for now because future constraints will no longer be valid against this file as we shift towards using `fedramp-example-ssp.xml`.
- Test scaffolding function was edited in the `dev-constraint.js` file. A conditional statement was added that if the model is SSP, then point to the new `fedramp-example-ssp.xml` file. This preserves it's intended functionality for when we start writing constraints against other models, while also pointing to our new SSP example file when writing constraints against an SSP in the meantime. 

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
~- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?~ Not applicable. 
~- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?~ Not applicable. 

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-12-03 18:55 UTC, aj-stein-gsa requested changes

2024-12-03 18:55 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="missing-response-components" target="//statement" test="count(by-component) gt 0" level="ERROR">
Blocking: FYI, this is incoming in #952. I am pairing with people on the call with this change right now.

2024-12-03 18:56 UTC, aj-stein-gsa requested changes

2024-12-03 18:56 UTC, aj-stein-gsa commented on src/validations/constraints/content/fedramp-ssp-example.oscal.xml
Blocking: which one will we keep for now?

2024-12-03 18:56 UTC, aj-stein-gsa commented on src/validations/constraints/content/fedramp-ssp-example.xml
Blocking: which one will we keep for now?

2024-12-03 19:18 UTC, Gabeblis commented on src/validations/constraints/content/fedramp-ssp-example.xml
Resolved: [b88f36b](https://github.com/GSA/fedramp-automation/pull/953/commits/b88f36bfe9eac1316eac6877478eb335fc2da269)

2024-12-03 19:18 UTC, Gabeblis commented on src/validations/constraints/content/fedramp-ssp-example.oscal.xml
Resolved: [b88f36b](https://github.com/GSA/fedramp-automation/pull/953/commits/b88f36bfe9eac1316eac6877478eb335fc2da269)

2024-12-03 19:30 UTC, wandmagic approved these changes

2024-12-03 19:31 UTC, wandmagic commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="missing-response-components" target="//statement" test="count(by-component) gt 0" level="ERROR">
ok if it needs adjustment from an upcoming PR we can adjust but i think we should keep it in for now so that we keep the green checks green

2024-12-03 20:51 UTC, aj-stein-gsa commented
Per discussion while pairing earlier today, @wandmagic asked me to integrate the changes in #952 here, so I will work towards a PR to wrap in here.

2024-12-03 22:48 UTC, aj-stein-gsa reviewed
Nice work, strong start. I have a general approach question/comment, but I can be happily overruled on that.

2024-12-03 22:48 UTC, aj-stein-gsa commented on src/validations/constraints/content/fedramp-ssp-example.oscal.xml
I think I will get overruled, but can we leave the example files in the example folder like #925 and run integration tests against that? Later, I think we will have a few full files and narrative around them and cross-reference segemnts of said files in some way in embedded rendered views on the automate.fedramp.gov website, so we may want to have this folder of worked examples.

That said, I think I will be the minority opinoin here, I will comment on this, I am not immediately asking for a change.

2024-12-03 23:41 UTC, Gabeblis commented on src/validations/constraints/content/fedramp-ssp-example.oscal.xml
I'm ok with that. Resolved: [fa46b2f](https://github.com/GSA/fedramp-automation/pull/953/commits/fa46b2fd4c84af8cc407b59859d2ffcce1df7c11)

2024-12-04 13:36 UTC, aj-stein-gsa approved these changes

2024-12-04 14:36 UTC, wandmagic approved these changes

2024-12-04 14:36 UTC, merged