Hotfix/deprecate all valid
GSA/fedramp-automation pull request #960
Opened 2024-12-04 17:49 UTC by wandmagic

# Committer Notes

deprecate all valid

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-12-04 18:18 UTC, wandmagic commented
fixes https://github.com/GSA/fedramp-automation/issues/958

2024-12-04 18:34 UTC, aj-stein-gsa requested changes
Looks good, some initial feedback.

2024-12-04 18:34 UTC, aj-stein-gsa commented on src/content/rev5/examples/ssp/xml/attachments/diagrams/boundary.png
Interesting, was this a dangling `@href` before? I didn't see the same folder structure in the other directory where the example SSP was previously located.

2024-12-04 18:34 UTC, aj-stein-gsa commented on src/validations/constraints/CONTRIBUTING.md
> +2. Add the necessary, correct data to [`../../../content/rev5/examples/ssp/xml/fedramp-ssp-example.oscal.xml`](../../../content/rev5/examples/ssp/xml/fedramp-ssp-example.oscal.xml) for a positive tes
Non-blocking: thanks for taking care of this, I possibly would have forgotten it had I not seen your PR today, thanks!

2024-12-04 18:34 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-has-data-flow-diagram-link-href-target-VALID-1.xml
> +        <link href="./fedramp-tailoring-profile.xml" rel="diagram" />
Blocking: Ummm, what kind of diagrams have you been using these days that look like OSCAL profiles?

2024-12-04 18:34 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>A FedRAMP SSP MUST include an authorization boundary diagram. found {$authorization-boundary-href}</message>
Blocking: How are changes to constraints coming into this PR?

2024-12-04 20:49 UTC, aj-stein-gsa requested changes
Sorry I found some other touch ups during review.

2024-12-04 20:49 UTC, aj-stein-gsa commented on src/content/rev5/examples/ssp/xml/fedramp-ssp-example.oscal.xml
> +         <prop name="connection-security" value="vpn" ns="https://fedramp.gov/ns/oscal"/>
Given chatter in the team chat, it would seem we should change this ahead of allowed-values updates.

```suggestion
         <prop name="connection-security" value="tls-1.3" ns="https://fedramp.gov/ns/oscal"/>
```

2024-12-04 20:49 UTC, aj-stein-gsa commented on src/content/rev5/examples/ssp/xml/fedramp-ssp-example.oscal.xml
> +         <prop name="connection-security" value="vpn" ns="https://fedramp.gov/ns/oscal"/>
Ditto here


```suggestion
         <prop name="connection-security" value="tls-1.3" ns="https://fedramp.gov/ns/oscal"/>
```

2024-12-04 20:49 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-has-authorization-boundary-diagram-link-href-target-VALID-1.xml
> +            <link href="https://www.fedramp.gov/assets/resources/documents/Agency-Authorization-Auth-Boundary-Diagram-Job-Aid.pdf" rel="diagram"/>
I was unclear before it seems, let's at least link to a picture that represents a diagram?

```suggestion
            <link href="https://github.com/GSA/fedramp-automation/blob/9a8e155668d4f7a26ffc372b73d568b074854aac/src/content/awesome-cloud/artifacts/AwesomeCloudHLA1.png" rel="diagram"/>
```

2024-12-04 20:49 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-has-data-flow-diagram-link-href-target-VALID-1.xml
> +        <link href="https://www.fedramp.gov/assets/resources/documents/Agency-Authorization-Auth-Boundary-Diagram-Job-Aid.pdf" rel="diagram" />
Ditto

```suggestion
            <link href="https://github.com/GSA/fedramp-automation/blob/9a8e155668d4f7a26ffc372b73d568b074854aac/src/content/awesome-cloud/artifacts/AwesomeCloudHLA1.png" rel="diagram"/>
```

2024-12-04 20:49 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-has-network-architecture-diagram-link-href-target-VALID-1.xml
> +        <link href="https://www.fedramp.gov/assets/resources/documents/Agency-Authorization-Auth-Boundary-Diagram-Job-Aid.pdf" rel="diagram"/>
Ditto

```suggestion
            <link href="https://github.com/GSA/fedramp-automation/blob/9a8e155668d4f7a26ffc372b73d568b074854aac/src/content/awesome-cloud/artifacts/AwesomeCloudHLA1.png" rel="diagram"/>
```

2024-12-04 20:49 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-has-network-architecture-diagram-link-href-target-VALID-1.xml
> +      <prop name="connection-security" value="vpn" ns="https://fedramp.gov/ns/oscal"/>
Ditto

```suggestion
      <prop name="connection-security" value="tls-1.3" ns="https://fedramp.gov/ns/oscal"/>
```

2024-12-04 22:09 UTC, aj-stein-gsa commented
@wandmagic is this ready for re-review?

2024-12-04 22:30 UTC, wandmagic commented
> @wandmagic is this ready for re-review?

yess

2024-12-04 22:37 UTC, aj-stein-gsa approved these changes

2024-12-04 22:37 UTC, aj-stein-gsa commented on src/validations/constraints/unit-tests/address-type-PASS.yaml
> +  content: ../../../content/rev5/examples/ssp/xml/fedramp-ssp-example.oscal.xml # the content to run
Non-blocking, I will approve, but having that comment one of the 200+ configuration files seems unhelpful.

```suggestion
  content: ../../../content/rev5/examples/ssp/xml/fedramp-ssp-example.oscal.xml
```

2024-12-04 22:38 UTC, Gabeblis approved these changes
LGTM

2024-12-04 23:13 UTC, aj-stein-gsa requested changes
Sorry to be that guy, but caught something working another PR. 😢 Apologies!

2024-12-04 23:13 UTC, aj-stein-gsa commented on src/validations/constraints/unit-tests/control-implementation-status-PASS.yaml
> +  content: ../content/ssp-control-implementation-status-VALID.xml
Was this intentional and not meant to change like the others?

```suggestion
  content: ../../../content/rev5/examples/ssp/xml/fedramp-ssp-example.oscal.xml
```

Context: https://github.com/wandmagic/fedramp-automation/pull/18#pullrequestreview-2480097652

2024-12-05 14:03 UTC, wandmagic commented on src/validations/constraints/unit-tests/control-implementation-status-PASS.yaml
> +  content: ../content/ssp-control-implementation-status-VALID.xml
this was intentional. the example SSP doesn't leverage the implementation status prop, and in the nature of preserving it's integrity, i kept that valid check in isolated content.

2024-12-05 14:22 UTC, aj-stein-gsa commented on src/validations/constraints/unit-tests/control-implementation-status-PASS.yaml
> +  content: ../content/ssp-control-implementation-status-VALID.xml
OK I was getting errors on my PR so I guess I will have to sort that as well.

2024-12-05 14:24 UTC, aj-stein-gsa approved these changes

2024-12-05 17:50 UTC, merged