Adjust missing-response-components, warn on misplaced response components
GSA/fedramp-automation pull request #969
Opened 2024-12-05 20:13 UTC by aj-stein-gsa

# Committer Notes

This is take three after https://github.com/wandmagic/fedramp-automation/pull/18. This tweaks missing-response-components and adds another with `level="WARN"` just to be clear general NIST practice won't work with FedRAMP.

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-12-06 15:16 UTC, kyhu65867 submitted a review, later dismissed
A few small things.

2024-12-06 15:16 UTC, kyhu65867 commented on src/validations/constraints/fedramp-external-constraints.xml
> +                    <p>A constraint violation with this warning indicates a given SSP uses one of the valid locations for all NIST use cases, not the only one FedRA</p>
```suggestion
                    <p>A constraint violation with this warning indicates a given SSP uses one of the valid locations for all NIST use cases, but not the only FedRAMP required location.</p>
```

2024-12-06 16:35 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                    <p>A constraint violation with this warning indicates a given SSP uses one of the valid locations for all NIST use cases, not the only one FedRA</p>
How did I truncate this during the rebase, thanks for the heads up!

2024-12-06 18:42 UTC, Gabeblis requested changes
This PR looks good. Just one thing we need to address regarding the `control-implementation-status` constraint.

2024-12-06 18:42 UTC, Gabeblis commented on src/validations/constraints/content/ssp-control-implementation-status-VALID.xml
>        </statement>
Is this change to the `control-implementation-status-VALID.xml` file related to this PR? This definitely looks correct in the way that it is written, but if you make this change here, you'll have to make a couple more changes.
1) `control-implementation-status-INVALID.xml` will need to have the `<status>` field added like so:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<system-security-plan xmlns="http://csrc.nist.gov/ns/oscal/1.0"
                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xsi:schemaLocation="http://csrc.nist.gov/ns/oscal/1.0 https://github.com/usnistgov/OSCAL/releases/download/v1.1.2/oscal_ssp_schema.xsd"
                      uuid="12345678-1234-4321-8765-123456789012">
  <control-implementation>
    <implemented-requirement uuid="88888888-0000-4000-9000-000000000008" control-id="ac-1">
      <statement statement-id="ac-1_stmt.a" uuid="99999999-0000-4000-9000-000000000009">
        <by-component component-uuid="55555555-0000-4000-9000-000000000005" uuid="aaaaaaaa-0000-4000-9000-00000000000a">
          <prop ns="https://fedramp.gov/ns/oscal" name="implementation-status" value="unsupported-status"/>
        </by-component>
      </statement>
    </implemented-requirement>
  </control-implementation>
</system-security-plan>
```
2) The `control-implementation-status` allowed values will need to have the target changed to:
```
target="control-implementation/implemented-requirement/statement/by-component/prop[@name='implementation-status']/@value"
```

2024-12-06 19:04 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-control-implementation-status-VALID.xml
>        </statement>
Ha! I should probably come back around to this and finish what I started. 🤦 Thanks for the very accurate feedback, sir!

2024-12-13 06:21 UTC, aj-stein-gsa commented on src/validations/constraints/content/ssp-control-implementation-status-VALID.xml
>        </statement>
Apologies, this PR was long overdue. I addressed it in https://github.com/GSA/fedramp-automation/pull/969/commits/e8c20d56a8d2a1fc9c2409e870392269787659fb.

2024-12-13 14:48 UTC, Gabeblis approved these changes

2024-12-13 14:49 UTC, Gabeblis commented
Good stuff!

2024-12-13 15:53 UTC, wandmagic approved these changes

2024-12-13 15:53 UTC, merged