Add `protocol-has-used-by-link` constraint
GSA/fedramp-automation pull request #970
Opened 2024-12-05 20:37 UTC by Gabeblis

# Committer Notes
## Purpose
This PR introduces a constraint `protocol-has-used-by-link`, which ensures that each component with a protocol assembly includes at least one `used-by` link to ensure that a component that exposes ports for other components to connect, indicates which other components use it. 

## Changes

Added Constraint:
- `protocol-has-used-by-link`: Ensures that each component with a protocol assembly includes at least one `used-by` link.

Test Data:
- **Invalid Test Data File**: Demonstrates the case where there the `used-by` link isn't included.
- **Valid Test Data File**: Demonstrates the case where the `used-by` link is included.

Added YAML Files
- **2 YAML Files**: Included pass and fail YAML files to validate the constraint:

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [x] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-12-05 20:56 UTC, DimitriZhurkin requested changes

2024-12-05 20:56 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>This component exposes ports for other components to connect; however, it MUST indicate which other components use it.</message>
Maybe replace `This component` with something like `Component {component/@uuid}` (untested)? Might be easier for users to troubleshoot:
```suggestion
                <message>Component {component/@uuid} exposes ports for other components to connect. However, it MUST indicate which other components use it.</message>
```

2024-12-05 21:02 UTC, DimitriZhurkin submitted a review, later dismissed

2024-12-05 21:29 UTC, aj-stein-gsa requested changes

2024-12-05 21:29 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Component {component/@uuid} exposes ports for other components to connect. However, it MUST indicate which other components use it.</message>
I really enjoy the team embracing the use of template text values like this. However, re [FRR113](https://github.com/GSA/fedramp-automation/blob/develop/src/validations/styleguides/STYLE.md#frr113), I would think telling downstream users, some who are not developers, to look for component at some UUID is not user friendly. It is when the users are developers, but not a downstream user that does not develop.

Messages are for users, developers leverage them for reusable messaging so they can shamelessly steal from FedRAMP. So ... I would like to noodle on this. Components require a title, right? I would think it may be ugly, but something like this may be more appropriate.

```suggestion
                <message>A FedRAMP SSP's component MUST identify which other components use it via network communication. Component {if (exists(component/title) then string(component/title} else ''} exposes ports for other components to connect, but does not identify which components use it.</message>
```

2024-12-05 21:46 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Component {component/@uuid} exposes ports for other components to connect. However, it MUST indicate which other components use it.</message>
Generally speaking, maybe we could come up with a message template, incorporating text values, whenever possible?

2024-12-05 21:48 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Component {component/@uuid} exposes ports for other components to connect. However, it MUST indicate which other components use it.</message>
@aj-stein-gsa How do you feel about this: [3cf2130](https://github.com/GSA/fedramp-automation/pull/970/commits/3cf2130ed3ec923f4e085fabdd35a4a1d7e4e1b4)

2024-12-05 21:54 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Component {component/@uuid} exposes ports for other components to connect. However, it MUST indicate which other components use it.</message>
I like that, @Gabeblis, but also there may be 20-100+ components in the real world, so I think both of you had really good intuition with including an identifier. I was just saying the UUID will not make sense to most people.

Also @DimitriZhurkin I would need to understand more about what you with text value templates, like a generic one we could use across different assembly/field/flag contexts, or did I misunderstand?

2024-12-05 22:05 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Component {component/@uuid} exposes ports for other components to connect. However, it MUST indicate which other components use it.</message>
I mean, instead of always starting with
`A FedRAMP SSP's component MUST...`
we could do something like this (short and sweet):
`Component "{string(component/title} )}" MUST specify which other components use its ports.`

2024-12-05 22:11 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Component {component/@uuid} exposes ports for other components to connect. However, it MUST indicate which other components use it.</message>
@Gabeblis Ok I used your suggestion, but this is the output of the title: 
```
Document[0, 14]
  Paragraph[0, 14]
    Text[0, 13] chars:[0, 13, "Email … rvice"]
```

2024-12-05 22:19 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Component {component/@uuid} exposes ports for other components to connect. However, it MUST indicate which other components use it.</message>
Le sigh, ok, I forgot why I started to get these, I thought that is why I wrapped them in `string()` declarations.

2024-12-06 13:41 UTC, DimitriZhurkin approved these changes

2024-12-06 15:36 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message>Component {component/@uuid} exposes ports for other components to connect. However, it MUST indicate which other components use it.</message>
@aj-stein-gsa I think we should proceed with using the uuid for now. Is that cool with you? Unless this is something that can be fixed quickly

2024-12-06 15:51 UTC, aj-stein-gsa submitted a review, later dismissed

2024-12-06 16:31 UTC, DimitriZhurkin submitted a review, later dismissed

2024-12-06 16:55 UTC, aj-stein-gsa submitted a review, later dismissed

2024-12-06 17:19 UTC, aj-stein-gsa approved these changes

2024-12-06 18:42 UTC, kyhu65867 approved these changes

2024-12-06 18:43 UTC, DimitriZhurkin approved these changes

2024-12-06 18:43 UTC, merged