re-introduce implemented-requirements constraints
GSA/fedramp-automation pull request #981
Opened 2024-12-09 22:17 UTC by wandmagic

# Committer Notes

re-introduce  two constraints for tracking implemented-requirement completion 
- extraneous-implemented-requirements
- incomplete-implemented-requirements

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-12-10 15:36 UTC, Gabeblis requested changes
This is great stuff! Just some minor comments.

2024-12-10 15:36 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                </message>
```suggestion
                <message>A FedRAMP SSP MUST NOT include extraneous controls outside of the FedRAMP baseline. Extraneous control: ({@control-id}).</message>
```

2024-12-10 15:36 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                </message>
```suggestion
                <message>A FedRAMP SSP MUST contain an implemented requirement for each imported control. Missing implemented requirement: ({@id}).</message>
```

2024-12-10 15:36 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <!-- Collect all the implemented requirements' control IDs -->
```suggestion
```

2024-12-10 15:36 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <index-has-key id='extraneous-implemented-requirements' target="//implemented-requirement" name="index-imported-controls" level="ERROR">
I get that this does the exact same thing, but could we not reuse the map here for consistency? 
```suggestion
            <index-has-key id='extraneous-implemented-requirements' target="$implemented-requirements-map" name="index-imported-controls" level="ERROR">
```

2024-12-10 15:36 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <let var="resolved-import-profile-href" expression="if (starts-with($import-profile-href, '#')) then back-matter/resource[@uuid = substring($import-profile-href, 2)]/rlink/@href else $imp
Indentation looks a little off here.

2024-12-10 15:36 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +             <index name="index-implemented-requirements" target="$implemented-requirements-map">
Indentation looks a little off here.

2024-12-10 15:41 UTC, DimitriZhurkin commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/general-concepts/implemented-requirements"/>
For the `help-url` value, I'm getting the `404` error. However, I found `implemented-requirement` at this URL:
https://automate.fedramp.gov/documentation/ssp/6-security-controls/#control-definitions

Is documentation in progress?

2024-12-10 15:48 UTC, wandmagic commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <index-has-key id='extraneous-implemented-requirements' target="//implemented-requirement" name="index-imported-controls" level="ERROR">
I'm not sure if we can re-use the map but i will try

2024-12-10 15:49 UTC, wandmagic commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <prop namespace="https://docs.oasis-open.org/sarif/sarif/v2.1.0" name="help-url" value="https://automate.fedramp.gov/documentation/general-concepts/implemented-requirements"/>
ah thank you i will update

2024-12-10 16:10 UTC, wandmagic commented
Please note, i've added a style guide constraint change help URI is now tested with doc-available to assure that the help URI exists

2024-12-10 16:43 UTC, Gabeblis submitted a review, later dismissed
Thanks for addressing my feedback. Just a couple small tweaks to the messages that I'd like to see.

2024-12-10 16:43 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message> A FedRAMP SSP MUST contain an implemented requirement for each imported control. Missing ({@id})</message>
```suggestion
                <message>A FedRAMP SSP MUST contain an implemented requirement for each imported control. Missing: ({@id}).</message>
```

2024-12-10 16:43 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +                <message> A FedRAMP SSP MUST NOT include extraneous controls outside of the FedRAMP baseline Extraneous ({@control-id})</message>
```suggestion
                <message>A FedRAMP SSP MUST NOT include extraneous controls outside of the FedRAMP baseline. Extraneous control: ({@control-id}).</message>
```

2024-12-10 16:50 UTC, wandmagic commented
> Thanks for addressing my feedback. Just a couple small tweaks to the messages that I'd like to see.

applied, thanks for your dilligence

2024-12-10 16:51 UTC, DimitriZhurkin approved these changes

2024-12-10 19:47 UTC, Gabeblis approved these changes

2024-12-10 20:08 UTC, merged

2024-12-11 00:30 UTC, aj-stein-gsa reviewed
I know I am late to the party, but I did review it a little later in the day than planned. Nice work, @wandmagic.