Revise inter-boundary-component-has-direction constraint (#930)
GSA/fedramp-automation pull request #988
Opened 2024-12-10 18:46 UTC by DimitriZhurkin

# Committer Notes

1. In `fedramp-external-constraints.xml`, modify the `target` Metapath expression (the `inter-boundary-component` variable).
2. Update `ssp-inter-boundary-component-has-direction-INVALID.xml` to reflect Metapath changes.

Related issue: [#930](https://github.com/GSA/fedramp-automation/issues/930)

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-12-10 19:33 UTC, wandmagic submitted a review, later dismissed

2024-12-10 22:41 UTC, aj-stein-gsa requested changes

2024-12-10 22:41 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <let var="inter-boundary-component" expression="component[(@type=('service', 'software') and not(prop[@name='leveraged-authorization-uuid']) and prop[@name='implementation-point' and @val
It is syntatically valid without, but I would like if we can wrap the part of the predicate with the new and its value in parentheses so we know they are grouped together in the presence of multiple `and` conditionals.

```suggestion
            <let var="inter-boundary-component" expression="component[(@type=('service', 'software') and not(prop[@name='leveraged-authorization-uuid']) and prop[@name='implementation-point' and @value='external']) or (@type='interconnection') or (@type=('service', 'software') and prop[@name='implementation-point' and @value='internal'] and (prop[@name='communicates-externally' and @value='yes') and @ns='https://fedramp.gov/ns/oscal'])]"/>
```

And yes I apologize in advance as I just read the comments to understand the latest AC, I know that is not included but makes it a little more understandable if things are added or changed in the long-run.

2024-12-11 03:51 UTC, Gabeblis submitted a review, later dismissed

2024-12-12 16:54 UTC, Gabeblis approved these changes

2024-12-12 19:16 UTC, aj-stein-gsa reviewed
I would like this PR not get merged until we confirm this implements the updated in a comment but not modified in the issue criteria per https://github.com/GSA/fedramp-automation/issues/930#issuecomment-2536711475. I just want confirmation that this is "the place" where that goes because thus far the new requirements were discussed separate of which issue, this seems like one possible place. If I get corrected by someone on the team, I will dismiss and approve.

2024-12-12 23:35 UTC, aj-stein-gsa commented
I only delinked #930 so it does not automatically close the issue because there are potentially multiple requirements for that set of constraints, I do not want to automatically close. I am about to re-review.

2024-12-12 23:55 UTC, aj-stein-gsa approved these changes

2024-12-13 14:00 UTC, merged