Issue-940 WIP
GSA/fedramp-automation pull request #991
Opened 2024-12-11 19:24 UTC by Gabeblis

# Committer Notes

{Please provide a description of what this PR accomplishes. Be sure to reference any issues addressed. If the PR is a work-in-progress submitted for early review, please submit the PR as a draft PR using the "Draft pull request" dropdown.}

### All Submissions:

- [ ] Have you selected the correct base branch per [Contributing](https://github.com/GSA/fedramp-automation/blob/master/CONTRIBUTING.md) guidance?
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/GSA/fedramp-automation/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] If applicable, have all [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.?
- [ ] If applicable, does this PR reference the issue it addresses and explain how it addresses the issue?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

2024-12-12 14:21 UTC, aj-stein-gsa requested changes

2024-12-12 14:21 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="has-authorization-boundary-diagram-link-href-target" target="." test="doc-available(resolve-uri(.[not(starts-with(@href, '#'))]/@href)) or count(../../../../back-matter/resour
OK, so I reviewed the other code and discussed the metaschema-java architecture with @david-waltermire, and he pointed out an important piece of nuance as it applies to my PR for #989 and #991 (this one). A more detailed explanation will end up in the wiki, and probably upstream in documentation at framework.metaschema.dev in the near future.

What you have to do in this situation:

1. You have to change the `context/metapath/@target` to `authorization-boundary` or `data-flow` or `network-architecture`, but you can not use the `let` `@var` and `@expression` binding anymore because it will only evaluate per `context/metapath/@target`, and that will be once for this "parent".
2. You can keep the `context/metapath/@target` as-is, but you MUST change the `expect/@target` use a predicate to filter, which I will try locally but do something similar to this approach: `target=".[ancestor::authorization-boundary]`. I am not 100% certain it is _that_ predicate, but you get the idea. I am testing locally now because I always stumble with `ancestor` and similar axes.

So your impression was correct @Gabeblis ("the constraint seems to fire on every `link` even though that's not the `context/metapath/@target`, but why? So if you want to know before wiki: external constraints attach themselves where the `context/metapath/@target` defines the constraint, but at the original definition for that field, flag, or assembly. What does that mean and why is it important? Even though for OSCAL Metaschema modules we have [original definitions](https://pages.nist.gov/metaschema/specification/syntax/definitions/) and [instances](https://pages.nist.gov/metaschema/specification/syntax/instances/). They target finds the instance, but places them on the definition (so not on its `assembly/@ref` in the models, like [`/system-security-plan/system-characteristics/authorization-boundary/diagram/link`](https://github.com/usnistgov/OSCAL/blob/v1.1.3/src/metaschema/oscal_ssp_metaschema.xml#L434-L436), it is on the original definition in the [metadata model](https://github.com/usnistgov/OSCAL/blob/v1.1.3/src/metaschema/oscal_metadata_metaschema.xml#L715-L729). To not do this would require building a logical model inside the model since some constraints are like classes can be sub-classed through inheritance and attack to every instance directly (and not the definitions) would break things. This concept is fundamental to how the constraints processing works and why the target is necessary, but the processing model and this important detail was never documented. We will fix that soon enough. I hope this helps. I will propose changes in a few minutes if I get them working locally. Then I will update wiki, in the next week or so update upstream documentation.

2024-12-12 15:07 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="has-authorization-boundary-diagram-link-href-target" target="." test="doc-available(resolve-uri(.[not(starts-with(@href, '#'))]/@href)) or count(../../../../back-matter/resour
This is closer, but I am still getting errors, not sure why as debugging shows the correct `link/@href` and `link/@rel`.

```suggestion
            <expect id="has-authorization-boundary-diagram-link-href-target" target=".[ancestor::authorization-boundary and @rel='diagram']" test="doc-available(resolve-uri(.[not(starts-with(@href, '#'))]/@href)) or count(../../../../back-matter/resource[@uuid=substring-after($authorization-boundary-href, '#') and prop[@name='type' and @value='image' and @class='authorization-boundary']]) = 1" level="ERROR">
```

2024-12-12 15:07 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="has-data-flow-diagram-link-href-target" target="." test="doc-available(resolve-uri(.[not(starts-with(@href, '#'))]/@href)) or count(../../../../back-matter/resource[@uuid=subs
Ditto here.

```suggestion
            <expect id="has-data-flow-diagram-link-href-target" target=".[ancestor::data-flow and @rel='diagram']" test="doc-available(resolve-uri(.[not(starts-with(@href, '#'))]/@href)) or count(../../../../back-matter/resource[@uuid=substring-after($data-flow-href, '#') and prop[@name='type' and @value='image' and @class='data-flow']]) = 1" level="ERROR">
```

2024-12-12 15:21 UTC, Gabeblis commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="has-authorization-boundary-diagram-link-href-target" target="." test="doc-available(resolve-uri(.[not(starts-with(@href, '#'))]/@href)) or count(../../../../back-matter/resour
I tried this yesterday. It is closer, but still grabs all 3. Also, `ancestor::authorization-boundary` does nothing here. That can be removed

2024-12-12 15:24 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="has-authorization-boundary-diagram-link-href-target" target="." test="doc-available(resolve-uri(.[not(starts-with(@href, '#'))]/@href)) or count(../../../../back-matter/resour
Maybe I am using the pre-release version of `oscal-cli`, but if that `ancestor::` axis does nothing, we have bigger problems. I'll ping you.

2024-12-12 15:25 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="has-authorization-boundary-diagram-link-href-target" target="." test="doc-available(resolve-uri(.[not(starts-with(@href, '#'))]/@href)) or count(../../../../back-matter/resour
Sigh, I need to pay more attention to the filtering, maybe we do have bigger problems ...

2024-12-12 19:11 UTC, aj-stein-gsa commented on src/validations/constraints/fedramp-external-constraints.xml
> +            <expect id="has-authorization-boundary-diagram-link-href-target" target="." test="doc-available(resolve-uri(.[not(starts-with(@href, '#'))]/@href)) or count(../../../../back-matter/resour
Understood, thanks for the confirmation, see background in [Google Chat](https://chat.google.com/room/AAAAn3vuHpo/WN3c7-a8Hy4/JBwvfvHVn3o?cls=10) and upcoming fixes in https://github.com/metaschema-framework/metaschema-java/issues/291. We can stick with your workaround, I am going to resolve this one.

2024-12-13 00:10 UTC, aj-stein-gsa approved these changes

2024-12-13 14:04 UTC, wandmagic approved these changes

2024-12-13 14:04 UTC, merged